"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import AttackActionType


class AttackLog(TornModel):
    """
    Pydantic model for the AttackLog Torn API response.

    Attributes:
        text (str): Torn API field `text`.
        timestamp (int): Torn API field `timestamp`.
        action (AttackActionType): Torn API field `action`.
        icon (str): Torn API field `icon`.
        attacker (AttackLogAttackerVariant1 | None): Torn API field `attacker`.
        defender (AttackLogDefenderVariant1 | None): Torn API field `defender`.
        attacker_item (AttackLogAttackerItem): This field only exists if the attacker is stealthed and they used a temporary item.
    """

    # <torn-sdk:custom-class AttackLog>
    # </torn-sdk:custom-class AttackLog>
    text: str
    timestamp: int
    action: AttackActionType
    icon: str
    attacker: AttackLogAttackerVariant1 | None
    defender: AttackLogDefenderVariant1 | None
    attacker_item: AttackLogAttackerItem | None = None


class AttackLogSummary(TornModel):
    """
    Pydantic model for the AttackLogSummary Torn API response.

    Attributes:
        id (int | None): Torn API field `id`.
        name (str | None): Torn API field `name`.
        hits (int): Torn API field `hits`.
        misses (int): Torn API field `misses`.
        damage (int): Torn API field `damage`.
    """

    # <torn-sdk:custom-class AttackLogSummary>
    # </torn-sdk:custom-class AttackLogSummary>
    id: int | None
    name: str | None
    hits: int
    misses: int
    damage: int


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class AttackLogAttackerItem(TornModel):
    """
    This field only exists if the attacker is stealthed and they used a temporary item.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class AttackLogAttackerItem>
    # </torn-sdk:custom-class AttackLogAttackerItem>
    id: int
    name: str


class AttackLogAttackerVariant1(TornModel):
    """
    This value could be null in stealthed attacks.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        item (AttackLogAttackerVariant1ItemVariant1 | None): Torn API field `item`.
    """

    # <torn-sdk:custom-class AttackLogAttackerVariant1>
    # </torn-sdk:custom-class AttackLogAttackerVariant1>
    id: int
    name: str
    item: AttackLogAttackerVariant1ItemVariant1 | None


class AttackLogAttackerVariant1ItemVariant1(TornModel):
    """
    This object could be null if there was no item being used in this turn or during this effect.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class AttackLogAttackerVariant1ItemVariant1>
    # </torn-sdk:custom-class AttackLogAttackerVariant1ItemVariant1>
    id: int | None = None
    name: str | None = None


class AttackLogDefenderVariant1(TornModel):
    """
    This value could be null in stealthed attacks.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class AttackLogDefenderVariant1>
    # </torn-sdk:custom-class AttackLogDefenderVariant1>
    id: int
    name: str


class AttackLogResponseAttacklog(TornModel):
    """
    Pydantic model for the AttackLogResponseAttacklog Torn API response.

    Attributes:
        log (list[AttackLog]): Torn API field `log`.
        summary (list[AttackLogSummary]): Torn API field `summary`.
    """

    # <torn-sdk:custom-class AttackLogResponseAttacklog>
    # </torn-sdk:custom-class AttackLogResponseAttacklog>
    log: list[AttackLog]
    summary: list[AttackLogSummary]


class AttackLogResponse(TornModel):
    """
    Pydantic model for the AttackLogResponse Torn API response.

    Attributes:
        attacklog (AttackLogResponseAttacklog): Torn API field `attacklog`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class AttackLogResponse>
    # </torn-sdk:custom-class AttackLogResponse>
    attacklog: AttackLogResponseAttacklog
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
