"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import AttackActionType


class AttackLog(TornModel):
    text: str
    timestamp: int
    action: AttackActionType
    icon: str
    attacker: AttackLogAttackerVariant1 | None
    defender: AttackLogDefenderVariant1 | None
    attacker_item: AttackLogAttackerItem | None = None


class AttackLogSummary(TornModel):
    id: int | None
    name: str | None
    hits: int
    misses: int
    damage: int


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    links: RequestLinks


class AttackLogAttackerItem(TornModel):
    id: int
    name: str


class AttackLogAttackerVariant1(TornModel):
    id: int
    name: str
    item: AttackLogAttackerVariant1ItemVariant1 | None


class AttackLogAttackerVariant1ItemVariant1(TornModel):
    id: int | None = None
    name: str | None = None


class AttackLogDefenderVariant1(TornModel):
    id: int
    name: str


class AttackLogResponseAttacklog(TornModel):
    log: list[AttackLog]
    summary: list[AttackLogSummary]


class AttackLogResponse(TornModel):
    attacklog: AttackLogResponseAttacklog
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")
