"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornBank(TornModel):
    """
    Pydantic model for the TornBank Torn API response.

    Attributes:
        days (int): Torn API field `days`.
        rate (float): Torn API field `rate`.
    """

    # <torn-sdk:custom-class TornBank>
    # </torn-sdk:custom-class TornBank>
    days: int
    rate: float


class TornBankResponse(TornListModel[TornBank]):
    """
    Pydantic model for the TornBankResponse Torn API response.
    """

    # <torn-sdk:custom-class TornBankResponse>
    # </torn-sdk:custom-class TornBankResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
