"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class Bounty(TornModel):
    """
    Pydantic model for the Bounty Torn API response.

    Attributes:
        target_id (int): Torn API field `target_id`.
        target_name (str): Torn API field `target_name`.
        target_level (int): Torn API field `target_level`.
        lister_id (int | None): Torn API field `lister_id`.
        lister_name (str | None): If the bounty is anonymous this field is null.
        reward (int): Torn API field `reward`.
        reason (str | None): Torn API field `reason`.
        quantity (int): Torn API field `quantity`.
        is_anonymous (bool): Torn API field `is_anonymous`.
        valid_until (int): Torn API field `valid_until`.
    """

    # <torn-sdk:custom-class Bounty>
    # </torn-sdk:custom-class Bounty>
    target_id: int
    target_name: str
    target_level: int
    lister_id: int | None
    lister_name: str | None
    reward: int
    reason: str | None
    quantity: int
    is_anonymous: bool
    valid_until: int


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndTotal Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    links: RequestLinks
    total: int | None = None


class TornBountiesResponse(TornModel):
    """
    Pydantic model for the TornBountiesResponse Torn API response.

    Attributes:
        bounties (list[Bounty]): Torn API field `bounties`.
        bounties_timestamp (int): Torn API field `bounties_timestamp`.
        bounties_delay (int): The minimum amount of time needed before the cache timestamp can change.
        metadata (RequestMetadataWithLinksAndTotal): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class TornBountiesResponse>
    # </torn-sdk:custom-class TornBountiesResponse>
    bounties: list[Bounty]
    bounties_timestamp: int
    bounties_delay: int
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
