"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornCalendarActivity(TornModel):
    title: str
    description: str
    start: int
    end: int
    fixed_start_time: bool | None = None


class TornCalendarResponse(TornModel):
    competitions: list[TornCalendarActivity]
    events: list[TornCalendarActivity]
