# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class TornCard(TornModel):
    name: str
    short_name: str
    class_: str = Field(alias='class')

class TornCardsResponse(TornListModel[TornCard]):
    pass
