"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornCompany(TornModel):
    id: int
    name: str
    cost: int
    employees: int
    positions: list[TornCompanyPosition]
    specials: list[TornCompanySpecial]
    stock: list[TornCompanyStock]


class TornCompanyPosition(TornModel):
    id: int
    name: str
    description: str
    ability: str
    working_stats: TornCompanyPositionWorkingStats


class TornCompanySpecial(TornModel):
    id: int
    name: str
    effect: str
    cost: int
    rating: int


class TornCompanyStock(TornModel):
    id: int
    name: str
    cost: int
    rrp: int


class TornCompanyPositionWorkingStats(TornModel):
    required: TornCompanyPositionWorkingStatsRequired
    daily_gains: TornCompanyPositionWorkingStatsDailyGains


class TornCompanyPositionWorkingStatsDailyGains(TornModel):
    intelligence: int
    manual_labor: int
    endurance: int


class TornCompanyPositionWorkingStatsRequired(TornModel):
    intelligence: int
    manual_labor: int
    endurance: int


class TornCompaniesResponse(TornListModel[TornCompany]):
    pass
