"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornCrime(TornModel):
    id: int
    name: str
    category_id: int
    category_name: str | None = None
    enhancer_id: int
    enhancer_name: str
    unique_outcomes_count: int
    unique_outcomes_ids: list[int]
    notes: list[str]


class TornCrimesResponse(TornListModel[TornCrime]):
    pass
