# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class TornEducation(TornModel):
    id: int
    name: str
    courses: list[TornEducationCourses]

class TornEducationCourses(TornModel):
    id: int
    code: str
    name: str
    description: str
    duration: int
    rewards: TornEducationRewards
    prerequisites: TornEducationPrerequisites

class TornEducationPrerequisites(TornModel):
    cost: int
    courses: list[int]

class TornEducationRewards(TornModel):
    working_stats: TornEducationRewardsWorkingStats
    effect: str | None
    honor: int | None

class TornEducationRewardsWorkingStats(TornModel):
    manual_labor: int | None
    intelligence: int | None
    endurance: int | None

class TornEducationResponse(TornListModel[TornEducation]):
    pass
