"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class BasicUser(TornModel):
    id: int
    name: str


class TornEliminationTeam(TornModel):
    id: int
    name: str
    participants: int
    position: int
    score: int
    lives: int
    wins: int
    losses: int
    eliminated: bool
    eliminated_timestamp: int | None
    leaders: list[TornEliminationTeamLeader]


class TornEliminationTeamLeader(TornModel):
    id: int
    name: str
    active: bool


class TornEliminationTeamsResponse(TornListModel[TornEliminationTeam]):
    pass
