"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class FactionHofValues(TornModel):
    """
    Pydantic model for the FactionHofValues Torn API response.

    Attributes:
        chain (int | None): Maximum chain achieved by the faction. Null if chosen category is 'rank' or 'respect'.
        chain_duration (int | None): The duration of the chain. Null if chosen category is 'rank' or 'respect'.
        respect (int | None): Null if chosen category is 'chain'.
    """

    # <torn-sdk:custom-class FactionHofValues>
    # </torn-sdk:custom-class FactionHofValues>
    chain: int | None
    chain_duration: int | None
    respect: int | None


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class TornFactionHof(TornModel):
    """
    Pydantic model for the TornFactionHof Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        members (int): Torn API field `members`.
        position (int): Torn API field `position`.
        rank (str): The full rank title & division of the faction.
        values (FactionHofValues): Torn API field `values`.
    """

    # <torn-sdk:custom-class TornFactionHof>
    # </torn-sdk:custom-class TornFactionHof>
    id: int
    name: str
    members: int
    position: int
    rank: str
    values: FactionHofValues


class TornFactionHofResponse(TornModel):
    """
    Pydantic model for the TornFactionHofResponse Torn API response.

    Attributes:
        factionhof (list[TornFactionHof]): Torn API field `factionhof`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class TornFactionHofResponse>
    # </torn-sdk:custom-class TornFactionHofResponse>
    factionhof: list[TornFactionHof]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
