# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionStatType

class TornFactionTree(TornModel):
    name: str
    branches: list[TornFactionTreeBranch]

class TornFactionTreeBranch(TornModel):
    id: int
    name: str
    upgrades: list[TornFactionTreeBranchUpgradesItem]

class TornFactionTreeBranchUpgradesItem(TornModel):
    name: str
    level: int
    ability: str
    cost: int
    challenge: TornFactionTreeBranchUpgradesItemChallengeVariant1 | None

class TornFactionTreeBranchUpgradesItemChallengeVariant1(TornModel):
    description: str
    amount_required: int
    stat: FactionStatType

class TornFactionTreeResponse(TornListModel[TornFactionTree]):
    pass
