# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class FactionHofValues(TornModel):
    chain: int | None
    chain_duration: int | None
    respect: int | None

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class TornFactionHof(TornModel):
    id: int
    name: str
    members: int
    position: int
    rank: str
    values: FactionHofValues

class TornFactionHofResponse(TornModel):
    factionhof: list[TornFactionHof]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
