"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionStatType


class TornFactionTree(TornModel):
    """
    Pydantic model for the TornFactionTree Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        branches (list[TornFactionTreeBranch]): Torn API field `branches`.
    """

    # <torn-sdk:custom-class TornFactionTree>
    # </torn-sdk:custom-class TornFactionTree>
    name: str
    branches: list[TornFactionTreeBranch]


class TornFactionTreeBranch(TornModel):
    """
    Pydantic model for the TornFactionTreeBranch Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        upgrades (list[TornFactionTreeBranchUpgradesItem]): Torn API field `upgrades`.
    """

    # <torn-sdk:custom-class TornFactionTreeBranch>
    # </torn-sdk:custom-class TornFactionTreeBranch>
    id: int
    name: str
    upgrades: list[TornFactionTreeBranchUpgradesItem]


class TornFactionTreeBranchUpgradesItem(TornModel):
    """
    Pydantic model for the TornFactionTreeBranchUpgradesItem Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        level (int): Torn API field `level`.
        ability (str): Torn API field `ability`.
        cost (int): Torn API field `cost`.
        challenge (TornFactionTreeBranchUpgradesItemChallengeVariant1 | None): Torn API field `challenge`.
    """

    # <torn-sdk:custom-class TornFactionTreeBranchUpgradesItem>
    # </torn-sdk:custom-class TornFactionTreeBranchUpgradesItem>
    name: str
    level: int
    ability: str
    cost: int
    challenge: TornFactionTreeBranchUpgradesItemChallengeVariant1 | None


class TornFactionTreeBranchUpgradesItemChallengeVariant1(TornModel):
    """
    Pydantic model for the TornFactionTreeBranchUpgradesItemChallengeVariant1 Torn API response.

    Attributes:
        description (str): Torn API field `description`.
        amount_required (int): Torn API field `amount_required`.
        stat (FactionStatType): Torn API field `stat`.
    """

    # <torn-sdk:custom-class TornFactionTreeBranchUpgradesItemChallengeVariant1>
    # </torn-sdk:custom-class TornFactionTreeBranchUpgradesItemChallengeVariant1>
    description: str
    amount_required: int
    stat: FactionStatType


class TornFactionTreeResponse(TornListModel[TornFactionTree]):
    """
    Pydantic model for the TornFactionTreeResponse Torn API response.
    """

    # <torn-sdk:custom-class TornFactionTreeResponse>
    # </torn-sdk:custom-class TornFactionTreeResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
