# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import GymClassType

class TornGym(TornModel):
    id: int
    name: str
    class_: GymClassType = Field(alias='class')
    energy_cost: int
    cost: int
    modifiers: TornGymModifiers
    note: str | None

class TornGymModifiers(TornModel):
    strength: float
    speed: float
    defense: float
    dexterity: float

class TornGymsResponse(TornListModel[TornGym]):
    pass
