"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field, RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import UserRankType


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class TornHofBasic(TornModel):
    """
    Pydantic model for the TornHofBasic Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        username (str): Torn API field `username`.
        faction_id (int): Torn API field `faction_id`.
        level (int): Torn API field `level`.
        last_action (int): Torn API field `last_action`.
        rank_name (UserRankType): Torn API field `rank_name`.
        rank_number (int): Torn API field `rank_number`.
        position (int): Torn API field `position`.
        signed_up (int): Torn API field `signed_up`.
        age_in_days (int): Torn API field `age_in_days`.
        value (int | str | float): Value representing the chosen category. Traveltime is shown in seconds. If the chosen category is 'rank', the value is of type string. If the chosen category is 'racingskill', the value is of type float. Otherwise it is an integer.
        rank (str): Torn API field `rank`.
    """

    # <torn-sdk:custom-class TornHofBasic>
    # </torn-sdk:custom-class TornHofBasic>
    id: int
    username: str
    faction_id: int
    level: int
    last_action: int
    rank_name: UserRankType
    rank_number: int
    position: int
    signed_up: int
    age_in_days: int
    value: int | str | float
    rank: str


class TornHofWithOffenses(TornModel):
    """
    Pydantic model for the TornHofWithOffenses Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        username (str): Torn API field `username`.
        faction_id (int): Torn API field `faction_id`.
        level (int): Torn API field `level`.
        last_action (int): Torn API field `last_action`.
        rank_name (UserRankType): Torn API field `rank_name`.
        rank_number (int): Torn API field `rank_number`.
        position (int): Torn API field `position`.
        signed_up (int): Torn API field `signed_up`.
        age_in_days (int): Torn API field `age_in_days`.
        value (int | str | float): Value representing the chosen category. Traveltime is shown in seconds. If the chosen category is 'rank', the value is of type string. If the chosen category is 'racingskill', the value is of type float. Otherwise it is an integer.
        rank (str): Torn API field `rank`.
        criminal_offenses (int): Torn API field `criminal_offenses`.
    """

    # <torn-sdk:custom-class TornHofWithOffenses>
    # </torn-sdk:custom-class TornHofWithOffenses>
    id: int
    username: str
    faction_id: int
    level: int
    last_action: int
    rank_name: UserRankType
    rank_number: int
    position: int
    signed_up: int
    age_in_days: int
    value: int | str | float
    rank: str
    criminal_offenses: int


class TornHof(RootModel[TornHofBasic | TornHofWithOffenses]):
    """
    Pydantic model for the TornHof Torn API response.
    """

    # <torn-sdk:custom-class TornHof>
    # </torn-sdk:custom-class TornHof>


class TornHofResponse(TornModel):
    """
    Pydantic model for the TornHofResponse Torn API response.

    Attributes:
        hof (list[TornHof]): Torn API field `hof`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class TornHofResponse>
    # </torn-sdk:custom-class TornHofResponse>
    hof: list[TornHof]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
