"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    AwardCrimesVersionType,
    HonorRarityType,
    HonorType,
)


class TornHonor(TornModel):
    """
    Properties 'circulation', 'equipped' & 'rarity' are only populated for honors which do not have type.id value 1.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        description (str): Torn API field `description`.
        type (TornHonorType): Torn API field `type`.
        circulation (int): Torn API field `circulation`.
        equipped (int): Torn API field `equipped`.
        rarity (HonorRarityType): Torn API field `rarity`.
        crimes_version (AwardCrimesVersionType): Populated only when the type.id is 5.
    """

    # <torn-sdk:custom-class TornHonor>
    # </torn-sdk:custom-class TornHonor>
    id: int
    name: str
    description: str
    type: TornHonorType
    circulation: int | None = None
    equipped: int | None = None
    rarity: HonorRarityType | None = None
    crimes_version: AwardCrimesVersionType | None = None


class TornHonorType(TornModel):
    """
    Pydantic model for the TornHonorType Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (HonorType): Torn API field `title`.
    """

    # <torn-sdk:custom-class TornHonorType>
    # </torn-sdk:custom-class TornHonorType>
    id: int
    title: HonorType


class TornHonorsResponse(TornListModel[TornHonor]):
    """
    Pydantic model for the TornHonorsResponse Torn API response.
    """

    # <torn-sdk:custom-class TornHonorsResponse>
    # </torn-sdk:custom-class TornHonorsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
