# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import AwardCrimesVersionType, HonorRarityType, HonorType

class TornHonor(TornModel):
    id: int
    name: str
    description: str
    type: TornHonorType
    circulation: int | None = None
    equipped: int | None = None
    rarity: HonorRarityType | None = None
    crimes_version: AwardCrimesVersionType | None = None

class TornHonorType(TornModel):
    id: int
    title: HonorType

class TornHonorsResponse(TornListModel[TornHonor]):
    pass
