"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import TornItemWeaponType


class TornItemMods(TornModel):
    """
    Pydantic model for the TornItemMods Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        image (str): Torn API field `image`.
        description (str): Torn API field `description`.
        dual_fit (bool): Whether the upgrade fits on dual weapons.
        weapons (list[TornItemWeaponType]): The weapon types this upgrade can be attached to.
    """

    # <torn-sdk:custom-class TornItemMods>
    # </torn-sdk:custom-class TornItemMods>
    id: int
    name: str
    image: str
    description: str
    dual_fit: bool
    weapons: list[TornItemWeaponType]


class TornItemModsResponse(TornListModel[TornItemMods]):
    """
    Pydantic model for the TornItemModsResponse Torn API response.
    """

    # <torn-sdk:custom-class TornItemModsResponse>
    # </torn-sdk:custom-class TornItemModsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
