"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    CountryType,
    ShopNameType,
    TornItemArmorCoveragePartType,
    TornItemType,
    TornItemWeaponCategoryType,
    TornItemWeaponType,
)


class TornItem(TornModel):
    """
    Pydantic model for the TornItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        description (str): Torn API field `description`.
        effect (str | None): Torn API field `effect`.
        requirement (str | None): Torn API field `requirement`.
        image (str): Torn API field `image`.
        type (TornItemType): Torn API field `type`.
        sub_type (TornItemWeaponType | None): Torn API field `sub_type`.
        is_masked (bool): Torn API field `is_masked`.
        is_tradable (bool): Torn API field `is_tradable`.
        is_found_in_city (bool): Torn API field `is_found_in_city`.
        value (TornItemValue): Torn API field `value`.
        circulation (int): Torn API field `circulation`.
        details (TornItemWeaponDetails | TornItemArmorDetails | None): If the item 'type' is 'Armor' then TornItemArmorDetails is returned.<br>If the item 'type' is 'Weapon' then TornItemWeaponDetails is returned.<br>Otherwise, null is returned.
    """

    # <torn-sdk:custom-class TornItem>
    # </torn-sdk:custom-class TornItem>
    id: int
    name: str
    description: str
    effect: str | None
    requirement: str | None
    image: str
    type: TornItemType
    sub_type: TornItemWeaponType | None
    is_masked: bool
    is_tradable: bool
    is_found_in_city: bool
    value: TornItemValue
    circulation: int
    details: TornItemWeaponDetails | TornItemArmorDetails | None


class TornItemArmorCoverage(TornModel):
    """
    Pydantic model for the TornItemArmorCoverage Torn API response.

    Attributes:
        name (TornItemArmorCoveragePartType): Torn API field `name`.
        value (float): Torn API field `value`.
    """

    # <torn-sdk:custom-class TornItemArmorCoverage>
    # </torn-sdk:custom-class TornItemArmorCoverage>
    name: TornItemArmorCoveragePartType
    value: float


class TornItemArmorDetails(TornModel):
    """
    Pydantic model for the TornItemArmorDetails Torn API response.

    Attributes:
        coverage (list[TornItemArmorCoverage]): Torn API field `coverage`.
        base_stats (TornItemBaseStats): Torn API field `base_stats`.
    """

    # <torn-sdk:custom-class TornItemArmorDetails>
    # </torn-sdk:custom-class TornItemArmorDetails>
    coverage: list[TornItemArmorCoverage]
    base_stats: TornItemBaseStats


class TornItemBaseStats(TornModel):
    """
    Pydantic model for the TornItemBaseStats Torn API response.

    Attributes:
        damage (int): Torn API field `damage`.
        accuracy (int): Torn API field `accuracy`.
        armor (int): Torn API field `armor`.
    """

    # <torn-sdk:custom-class TornItemBaseStats>
    # </torn-sdk:custom-class TornItemBaseStats>
    damage: int
    accuracy: int
    armor: int


class TornItemShop(TornModel):
    """
    Pydantic model for the TornItemShop Torn API response.

    Attributes:
        country (CountryType): Torn API field `country`.
        shop (ShopNameType): Torn API field `shop`.
        buy_price (int | None): Torn API field `buy_price`.
        sell_price (int | None): Torn API field `sell_price`.
    """

    # <torn-sdk:custom-class TornItemShop>
    # </torn-sdk:custom-class TornItemShop>
    country: CountryType
    shop: ShopNameType
    buy_price: int | None
    sell_price: int | None


class TornItemWeaponDetails(TornModel):
    """
    Pydantic model for the TornItemWeaponDetails Torn API response.

    Attributes:
        stealth_level (float): Torn API field `stealth_level`.
        base_stats (TornItemBaseStats): Torn API field `base_stats`.
        category (TornItemWeaponCategoryType): Torn API field `category`.
        ammo (TornItemWeaponDetailsAmmoVariant1 | None): Torn API field `ammo`.
        mods (list[int]): Torn API field `mods`.
    """

    # <torn-sdk:custom-class TornItemWeaponDetails>
    # </torn-sdk:custom-class TornItemWeaponDetails>
    stealth_level: float
    base_stats: TornItemBaseStats
    category: TornItemWeaponCategoryType
    ammo: TornItemWeaponDetailsAmmoVariant1 | None
    mods: list[int]


class TornItemValue(TornModel):
    """
    Pydantic model for the TornItemValue Torn API response.

    Attributes:
        vendor (TornItemValueVendorVariant1 | None): This field is replaced with shops array and will be removed on 1st of January 2027.
        shops (list[TornItemShop]): Torn API field `shops`.
        buy_price (int | None): This field is replaced with shops array and will be removed on 1st of January 2027.
        sell_price (int | None): This field is replaced with shops array and will be removed on 1st of January 2027.
        market_price (int): Torn API field `market_price`.
    """

    # <torn-sdk:custom-class TornItemValue>
    # </torn-sdk:custom-class TornItemValue>
    vendor: TornItemValueVendorVariant1 | None = None
    shops: list[TornItemShop]
    buy_price: int | None = None
    sell_price: int | None = None
    market_price: int


class TornItemValueVendorVariant1(TornModel):
    """
    Pydantic model for the TornItemValueVendorVariant1 Torn API response.

    Attributes:
        country (str): Torn API field `country`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class TornItemValueVendorVariant1>
    # </torn-sdk:custom-class TornItemValueVendorVariant1>
    country: str
    name: str


class TornItemWeaponDetailsAmmoVariant1(TornModel):
    """
    Pydantic model for the TornItemWeaponDetailsAmmoVariant1 Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        magazine_rounds (int): Torn API field `magazine_rounds`.
        rate_of_fire (TornItemWeaponDetailsAmmoVariant1RateOfFire): Torn API field `rate_of_fire`.
    """

    # <torn-sdk:custom-class TornItemWeaponDetailsAmmoVariant1>
    # </torn-sdk:custom-class TornItemWeaponDetailsAmmoVariant1>
    id: int
    name: str
    magazine_rounds: int
    rate_of_fire: TornItemWeaponDetailsAmmoVariant1RateOfFire


class TornItemWeaponDetailsAmmoVariant1RateOfFire(TornModel):
    """
    Pydantic model for the TornItemWeaponDetailsAmmoVariant1RateOfFire Torn API response.

    Attributes:
        minimum (int): Torn API field `minimum`.
        maximum (int): Torn API field `maximum`.
    """

    # <torn-sdk:custom-class TornItemWeaponDetailsAmmoVariant1RateOfFire>
    # </torn-sdk:custom-class TornItemWeaponDetailsAmmoVariant1RateOfFire>
    minimum: int
    maximum: int


class TornItemsResponse(TornListModel[TornItem]):
    """
    Pydantic model for the TornItemsResponse Torn API response.
    """

    # <torn-sdk:custom-class TornItemsResponse>
    # </torn-sdk:custom-class TornItemsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
