"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import TornItemWeaponType


class TornItemMods(TornModel):
    id: int
    name: str
    image: str
    description: str
    dual_fit: bool
    weapons: list[TornItemWeaponType]


class TornItemModsResponse(TornListModel[TornItemMods]):
    pass
