"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import TornItemAmmoType


class TornItemAmmo(TornModel):
    """
    Pydantic model for the TornItemAmmo Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        price (int): Torn API field `price`.
        types (list[TornItemAmmoType]): Types of ammo
    """

    # <torn-sdk:custom-class TornItemAmmo>
    # </torn-sdk:custom-class TornItemAmmo>
    id: int
    name: str
    price: int
    types: list[TornItemAmmoType]


class TornItemAmmoResponse(TornListModel[TornItemAmmo]):
    """
    Pydantic model for the TornItemAmmoResponse Torn API response.
    """

    # <torn-sdk:custom-class TornItemAmmoResponse>
    # </torn-sdk:custom-class TornItemAmmoResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
