"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornMerit(TornModel):
    """
    Pydantic model for the TornMerit Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        description (str): Torn API field `description`.
    """

    # <torn-sdk:custom-class TornMerit>
    # </torn-sdk:custom-class TornMerit>
    id: int
    name: str
    description: str


class TornMeritsResponse(TornListModel[TornMerit]):
    """
    Pydantic model for the TornMeritsResponse Torn API response.
    """

    # <torn-sdk:custom-class TornMeritsResponse>
    # </torn-sdk:custom-class TornMeritsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
