"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornMuseumSet(TornModel):
    """
    Pydantic model for the TornMuseumSet Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        points (int): Torn API field `points`.
        items (list[int]): Torn API field `items`.
    """

    # <torn-sdk:custom-class TornMuseumSet>
    # </torn-sdk:custom-class TornMuseumSet>
    name: str
    points: int
    items: list[int]


class TornMuseumResponse(TornListModel[TornMuseumSet]):
    """
    Pydantic model for the TornMuseumResponse Torn API response.
    """

    # <torn-sdk:custom-class TornMuseumResponse>
    # </torn-sdk:custom-class TornMuseumResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
