"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import TornOrganizedCrimePositionIdType


class FactionSlotPositionInfo(TornModel):
    """
    Pydantic model for the FactionSlotPositionInfo Torn API response.

    Attributes:
        id (TornOrganizedCrimePositionIdType): Torn API field `id`.
        label (str): Torn API field `label`.
        number (int): This field is no longer needed as there's 'label' field now.<br>This field will be removed on 1st of June 2026.
    """

    # <torn-sdk:custom-class FactionSlotPositionInfo>
    # </torn-sdk:custom-class FactionSlotPositionInfo>
    id: TornOrganizedCrimePositionIdType
    label: str
    number: int


class TornOrganizedCrime(TornModel):
    """
    Pydantic model for the TornOrganizedCrime Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        description (str): Torn API field `description`.
        difficulty (int): Torn API field `difficulty`.
        spawn (TornOrganizedCrimeSpawn): Torn API field `spawn`.
        scope (TornOrganizedCrimeScope): Torn API field `scope`.
        prerequisite (str | None): Torn API field `prerequisite`.
        slots (list[TornOrganizedCrimeSlot]): Torn API field `slots`.
    """

    # <torn-sdk:custom-class TornOrganizedCrime>
    # </torn-sdk:custom-class TornOrganizedCrime>
    name: str
    description: str
    difficulty: int
    spawn: TornOrganizedCrimeSpawn
    scope: TornOrganizedCrimeScope
    prerequisite: str | None
    slots: list[TornOrganizedCrimeSlot]


class TornOrganizedCrimeRequiredItem(TornModel):
    """
    Pydantic model for the TornOrganizedCrimeRequiredItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        is_used (bool): Torn API field `is_used`.
    """

    # <torn-sdk:custom-class TornOrganizedCrimeRequiredItem>
    # </torn-sdk:custom-class TornOrganizedCrimeRequiredItem>
    id: int
    name: str
    is_used: bool


class TornOrganizedCrimeScope(TornModel):
    """
    Pydantic model for the TornOrganizedCrimeScope Torn API response.

    Attributes:
        cost (int): Torn API field `cost`.
        return_ (int): Torn API field `return`.
    """

    # <torn-sdk:custom-class TornOrganizedCrimeScope>
    # </torn-sdk:custom-class TornOrganizedCrimeScope>
    cost: int
    return_: int = Field(alias="return")


class TornOrganizedCrimeSlot(TornModel):
    """
    Pydantic model for the TornOrganizedCrimeSlot Torn API response.

    Attributes:
        position_info (FactionSlotPositionInfo): Torn API field `position_info`.
        name (str): Torn API field `name`.
        required_item (TornOrganizedCrimeRequiredItem | None): Torn API field `required_item`.
    """

    # <torn-sdk:custom-class TornOrganizedCrimeSlot>
    # </torn-sdk:custom-class TornOrganizedCrimeSlot>
    position_info: FactionSlotPositionInfo
    name: str
    required_item: TornOrganizedCrimeRequiredItem | None


class TornOrganizedCrimeSpawn(TornModel):
    """
    Pydantic model for the TornOrganizedCrimeSpawn Torn API response.

    Attributes:
        level (int): Torn API field `level`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class TornOrganizedCrimeSpawn>
    # </torn-sdk:custom-class TornOrganizedCrimeSpawn>
    level: int
    name: str


class TornOrganizedCrimeResponse(TornListModel[TornOrganizedCrime]):
    """
    Pydantic model for the TornOrganizedCrimeResponse Torn API response.
    """

    # <torn-sdk:custom-class TornOrganizedCrimeResponse>
    # </torn-sdk:custom-class TornOrganizedCrimeResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
