# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import TornOrganizedCrimePositionIdType

class FactionSlotPositionInfo(TornModel):
    id: TornOrganizedCrimePositionIdType
    label: str
    number: int

class TornOrganizedCrime(TornModel):
    name: str
    description: str
    difficulty: int
    spawn: TornOrganizedCrimeSpawn
    scope: TornOrganizedCrimeScope
    prerequisite: str | None
    slots: list[TornOrganizedCrimeSlot]

class TornOrganizedCrimeRequiredItem(TornModel):
    id: int
    name: str
    is_used: bool

class TornOrganizedCrimeScope(TornModel):
    cost: int
    return_: int = Field(alias='return')

class TornOrganizedCrimeSlot(TornModel):
    position_info: FactionSlotPositionInfo
    name: str
    required_item: TornOrganizedCrimeRequiredItem | None

class TornOrganizedCrimeSpawn(TornModel):
    level: int
    name: str

class TornOrganizedCrimeResponse(TornListModel[TornOrganizedCrime]):
    pass
