# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class TornPokerTable(TornModel):
    id: int
    name: str
    blinds: TornPokerTableBlinds
    players: TornPokerTablePlayers
    speed: int

class TornPokerTableBlinds(TornModel):
    big: int
    small: int

class TornPokerTablePlayers(TornModel):
    current: int
    maximum: int

class TornPokerTablesResponse(TornListModel[TornPokerTable]):
    pass
