"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import PropertyModificationType, PropertyStaffType


class TornPropertiesItem(TornModel):
    id: int
    name: str
    cost: int
    happy: int
    upkeep: int
    modifications: list[PropertyModificationType]
    staff: list[PropertyStaffType]


class TornProperties(TornListModel[TornPropertiesItem]):
    pass
