"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class TornSearchForCash(TornModel):
    """
    Pydantic model for the TornSearchForCash Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        percentage (int): Torn API field `percentage`.
    """

    # <torn-sdk:custom-class TornSearchForCash>
    # </torn-sdk:custom-class TornSearchForCash>
    id: int
    title: str
    percentage: int


class TornSearchForCashResponse(TornListModel[TornSearchForCash]):
    """
    Pydantic model for the TornSearchForCashResponse Torn API response.
    """

    # <torn-sdk:custom-class TornSearchForCashResponse>
    # </torn-sdk:custom-class TornSearchForCashResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
