# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import TornShopliftingStatusTitleType

class TornShoplifting(TornModel):
    id: int
    status: list[TornShopliftingSecurityStatus]

class TornShopliftingSecurityStatus(TornModel):
    title: TornShopliftingStatusTitleType
    disabled: bool

class TornShopliftingResponse(TornListModel[TornShoplifting]):
    pass
