# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import RaceClassType

class RaceCar(TornModel):
    car_item_id: int
    car_item_name: str
    top_speed: int
    acceleration: int
    braking: int
    dirt: int
    handling: int
    safety: int
    tarmac: int
    class_: RaceClassType = Field(alias='class')

class RacingCarsResponse(TornListModel[RaceCar]):
    pass
