"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import RaceClassType, RaceStatusType


class Race(TornModel):
    """
    Pydantic model for the Race Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        track_id (int): Torn API field `track_id`.
        creator_id (int): Torn API field `creator_id`.
        status (RaceStatusType): Torn API field `status`.
        laps (int): Torn API field `laps`.
        participants (RaceParticipants): Torn API field `participants`.
        schedule (RaceSchedule): Torn API field `schedule`.
        requirements (RaceRequirements): Torn API field `requirements`.
        is_official (bool): Torn API field `is_official`.
    """

    # <torn-sdk:custom-class Race>
    # </torn-sdk:custom-class Race>
    id: int
    title: str
    track_id: int
    creator_id: int
    status: RaceStatusType
    laps: int
    participants: RaceParticipants
    schedule: RaceSchedule
    requirements: RaceRequirements
    is_official: bool


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class RaceParticipants(TornModel):
    """
    Pydantic model for the RaceParticipants Torn API response.

    Attributes:
        minimum (int): Torn API field `minimum`.
        maximum (int): Torn API field `maximum`.
        current (int): Torn API field `current`.
    """

    # <torn-sdk:custom-class RaceParticipants>
    # </torn-sdk:custom-class RaceParticipants>
    minimum: int
    maximum: int
    current: int


class RaceRequirements(TornModel):
    """
    Pydantic model for the RaceRequirements Torn API response.

    Attributes:
        car_class (RaceClassType | None): Torn API field `car_class`.
        driver_class (RaceClassType | None): Torn API field `driver_class`.
        car_item_id (int | None): Torn API field `car_item_id`.
        requires_stock_car (bool): Torn API field `requires_stock_car`.
        requires_password (bool): Torn API field `requires_password`.
        join_fee (int): Torn API field `join_fee`.
    """

    # <torn-sdk:custom-class RaceRequirements>
    # </torn-sdk:custom-class RaceRequirements>
    car_class: RaceClassType | None
    driver_class: RaceClassType | None
    car_item_id: int | None
    requires_stock_car: bool
    requires_password: bool
    join_fee: int


class RaceSchedule(TornModel):
    """
    Pydantic model for the RaceSchedule Torn API response.

    Attributes:
        join_from (int): Torn API field `join_from`.
        join_until (int): Torn API field `join_until`.
        start (int): Torn API field `start`.
        end (int | None): Torn API field `end`.
    """

    # <torn-sdk:custom-class RaceSchedule>
    # </torn-sdk:custom-class RaceSchedule>
    join_from: int
    join_until: int
    start: int
    end: int | None


class RacingRacesResponse(TornModel):
    """
    Pydantic model for the RacingRacesResponse Torn API response.

    Attributes:
        races (list[Race]): Torn API field `races`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class RacingRacesResponse>
    # </torn-sdk:custom-class RacingRacesResponse>
    races: list[Race]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
