"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class ForumCategoriesResponseItem(TornModel):
    """
    Pydantic model for the ForumCategoriesResponseItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        acronym (str): Torn API field `acronym`.
        threads (int): Torn API field `threads`.
    """

    # <torn-sdk:custom-class ForumCategoriesResponseItem>
    # </torn-sdk:custom-class ForumCategoriesResponseItem>
    id: int
    title: str
    acronym: str
    threads: int


class ForumCategoriesResponse(TornListModel[ForumCategoriesResponseItem]):
    """
    Pydantic model for the ForumCategoriesResponse Torn API response.
    """

    # <torn-sdk:custom-class ForumCategoriesResponse>
    # </torn-sdk:custom-class ForumCategoriesResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
