# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class ForumCategoriesResponseItem(TornModel):
    id: int
    title: str
    acronym: str
    threads: int

class ForumCategoriesResponse(TornListModel[ForumCategoriesResponseItem]):
    pass
