"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class ForumPost(TornModel):
    id: int
    thread_id: int
    author: ForumThreadAuthor
    is_legacy: bool
    is_topic: bool
    is_edited: bool
    is_pinned: bool
    created_time: int
    edited_by: int | None
    has_quote: bool
    quoted_post_id: int | None
    content: str
    likes: int
    dislikes: int


class ForumThreadAuthor(TornModel):
    id: int
    username: str
    karma: int


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    links: RequestLinks


class ForumPostsResponse(TornModel):
    posts: list[ForumPost]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")
