# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class ForumThreadAuthor(TornModel):
    id: int
    username: str
    karma: int

class ForumThreadBase(TornModel):
    id: int
    title: str
    forum_id: int
    posts: int
    rating: int
    views: int
    author: ForumThreadAuthor
    last_poster: ForumThreadAuthor | None
    first_post_time: int
    last_post_time: int | None
    has_poll: bool
    is_locked: bool
    is_sticky: bool

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class ForumThreadsResponse(TornModel):
    threads: list[ForumThreadBase]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
