"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class ForumPoll(TornModel):
    """
    Pydantic model for the ForumPoll Torn API response.

    Attributes:
        question (str): Torn API field `question`.
        answers_count (int): Torn API field `answers_count`.
        answers (list[ForumPollVote]): Torn API field `answers`.
    """

    # <torn-sdk:custom-class ForumPoll>
    # </torn-sdk:custom-class ForumPoll>
    question: str
    answers_count: int
    answers: list[ForumPollVote]


class ForumPollVote(TornModel):
    """
    Pydantic model for the ForumPollVote Torn API response.

    Attributes:
        answer (str): Torn API field `answer`.
        votes (int): Torn API field `votes`.
    """

    # <torn-sdk:custom-class ForumPollVote>
    # </torn-sdk:custom-class ForumPollVote>
    answer: str
    votes: int


class ForumThreadAuthor(TornModel):
    """
    Pydantic model for the ForumThreadAuthor Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        username (str): Torn API field `username`.
        karma (int): Torn API field `karma`.
    """

    # <torn-sdk:custom-class ForumThreadAuthor>
    # </torn-sdk:custom-class ForumThreadAuthor>
    id: int
    username: str
    karma: int


class ForumThreadBase(TornModel):
    """
    Pydantic model for the ForumThreadBase Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        forum_id (int): Torn API field `forum_id`.
        posts (int): Torn API field `posts`.
        rating (int): Torn API field `rating`.
        views (int): Total number of times players have opened this thread.
        author (ForumThreadAuthor): Torn API field `author`.
        last_poster (ForumThreadAuthor | None): Torn API field `last_poster`.
        first_post_time (int): Torn API field `first_post_time`.
        last_post_time (int | None): Torn API field `last_post_time`.
        has_poll (bool): Torn API field `has_poll`.
        is_locked (bool): Torn API field `is_locked`.
        is_sticky (bool): Torn API field `is_sticky`.
    """

    # <torn-sdk:custom-class ForumThreadBase>
    # </torn-sdk:custom-class ForumThreadBase>
    id: int
    title: str
    forum_id: int
    posts: int
    rating: int
    views: int
    author: ForumThreadAuthor
    last_poster: ForumThreadAuthor | None
    first_post_time: int
    last_post_time: int | None
    has_poll: bool
    is_locked: bool
    is_sticky: bool


class ForumThreadExtended(TornModel):
    """
    Pydantic model for the ForumThreadExtended Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        forum_id (int): Torn API field `forum_id`.
        posts (int): Torn API field `posts`.
        rating (int): Torn API field `rating`.
        views (int): Total number of times players have opened this thread.
        author (ForumThreadAuthor): Torn API field `author`.
        last_poster (ForumThreadAuthor | None): Torn API field `last_poster`.
        first_post_time (int): Torn API field `first_post_time`.
        last_post_time (int | None): Torn API field `last_post_time`.
        has_poll (bool): Torn API field `has_poll`.
        is_locked (bool): Torn API field `is_locked`.
        is_sticky (bool): Torn API field `is_sticky`.
        content (str): Torn API field `content`.
        content_raw (str): Torn API field `content_raw`.
        poll (ForumPoll | None): 'poll' is null when 'has_poll' is false.
    """

    # <torn-sdk:custom-class ForumThreadExtended>
    # </torn-sdk:custom-class ForumThreadExtended>
    id: int
    title: str
    forum_id: int
    posts: int
    rating: int
    views: int
    author: ForumThreadAuthor
    last_poster: ForumThreadAuthor | None
    first_post_time: int
    last_post_time: int | None
    has_poll: bool
    is_locked: bool
    is_sticky: bool
    content: str
    content_raw: str
    poll: ForumPoll | None


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
