"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class KeyLogResponseItem(TornModel):
    """
    Pydantic model for the KeyLogResponseItem Torn API response.

    Attributes:
        timestamp (int): Torn API field `timestamp`.
        type (str): Torn API field `type`.
        selections (str): Torn API field `selections`.
        id (int | str | None): Torn API field `id`.
        comment (str | None): Torn API field `comment`.
        ip (str): Torn API field `ip`.
    """

    # <torn-sdk:custom-class KeyLogResponseItem>
    # </torn-sdk:custom-class KeyLogResponseItem>
    timestamp: int
    type: str
    selections: str
    id: int | str | None
    comment: str | None = None
    ip: str


class KeyLogResponse(TornListModel[KeyLogResponseItem]):
    """
    Pydantic model for the KeyLogResponse Torn API response.
    """

    # <torn-sdk:custom-class KeyLogResponse>
    # </torn-sdk:custom-class KeyLogResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
