"""Resource registrations generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from .company import CompanyResource
from .company_async import AsyncCompanyResource
from .faction import FactionResource
from .faction_async import AsyncFactionResource
from .forum import ForumResource
from .forum_async import AsyncForumResource
from .key import KeyResource
from .key_async import AsyncKeyResource
from .market import MarketResource
from .market_async import AsyncMarketResource
from .property import PropertyResource
from .property_async import AsyncPropertyResource
from .racing import RacingResource
from .racing_async import AsyncRacingResource
from .torn import TornResource
from .torn_async import AsyncTornResource
from .user import UserResource
from .user_async import AsyncUserResource

__all__ = [
    "CompanyResource",
    "AsyncCompanyResource",
    "FactionResource",
    "AsyncFactionResource",
    "ForumResource",
    "AsyncForumResource",
    "KeyResource",
    "AsyncKeyResource",
    "MarketResource",
    "AsyncMarketResource",
    "PropertyResource",
    "AsyncPropertyResource",
    "RacingResource",
    "AsyncRacingResource",
    "TornResource",
    "AsyncTornResource",
    "UserResource",
    "AsyncUserResource",
]

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
