"""Public typed faction resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapperAsync
from TornAPIWrapper.endpoints_async.faction import Faction

from torn_sdk.core.resource import AsyncResource, AsyncResourceRegistry
from torn_sdk.resources._generated.faction_async import (
    GeneratedAsyncFactionResourceMixin,
)


class AsyncFactionResource(
    GeneratedAsyncFactionResourceMixin, AsyncResource[Faction]
):
    """
    Provide typed access to Torn faction endpoints.

    Attributes:
        endpoint (Faction): Underlying TornAPIWrapper faction endpoint.

    Args:
        wrapper (TornAPIWrapperAsync): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapperAsync) -> None:
        # <torn-sdk:custom-method AsyncFactionResource.__init__>
        # </torn-sdk:custom-method AsyncFactionResource.__init__>
        super().__init__(wrapper.faction)

    # <torn-sdk:custom-class AsyncFactionResource>
    # </torn-sdk:custom-class AsyncFactionResource>


AsyncResourceRegistry.register("faction", AsyncFactionResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
