"""Public typed forum resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapper
from TornAPIWrapper.endpoints.forum import Forum

from torn_sdk.core.resource import Resource, ResourceRegistry
from torn_sdk.resources._generated.forum import GeneratedForumResourceMixin


class ForumResource(GeneratedForumResourceMixin, Resource[Forum]):
    """
    Provide typed access to Torn forum endpoints.

    Attributes:
        endpoint (Forum): Underlying TornAPIWrapper forum endpoint.

    Args:
        wrapper (TornAPIWrapper): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapper) -> None:
        # <torn-sdk:custom-method ForumResource.__init__>
        # </torn-sdk:custom-method ForumResource.__init__>
        super().__init__(wrapper.forum)

    # <torn-sdk:custom-class ForumResource>
    # </torn-sdk:custom-class ForumResource>


ResourceRegistry.register("forum", ForumResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
