"""Public typed key resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapper
from TornAPIWrapper.endpoints.key import Key

from torn_sdk.core.resource import Resource, ResourceRegistry
from torn_sdk.resources._generated.key import GeneratedKeyResourceMixin


class KeyResource(GeneratedKeyResourceMixin, Resource[Key]):
    """
    Provide typed access to Torn key endpoints.

    Attributes:
        endpoint (Key): Underlying TornAPIWrapper key endpoint.

    Args:
        wrapper (TornAPIWrapper): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapper) -> None:
        # <torn-sdk:custom-method KeyResource.__init__>
        # </torn-sdk:custom-method KeyResource.__init__>
        super().__init__(wrapper.key)

    # <torn-sdk:custom-class KeyResource>
    # </torn-sdk:custom-class KeyResource>


ResourceRegistry.register("key", KeyResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
