"""Public typed market resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapperAsync
from TornAPIWrapper.endpoints_async.market import Market

from torn_sdk.core.resource import AsyncResource, AsyncResourceRegistry
from torn_sdk.resources._generated.market_async import (
    GeneratedAsyncMarketResourceMixin,
)


class AsyncMarketResource(
    GeneratedAsyncMarketResourceMixin, AsyncResource[Market]
):
    """
    Provide typed access to Torn market endpoints.

    Attributes:
        endpoint (Market): Underlying TornAPIWrapper market endpoint.

    Args:
        wrapper (TornAPIWrapperAsync): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapperAsync) -> None:
        # <torn-sdk:custom-method AsyncMarketResource.__init__>
        # </torn-sdk:custom-method AsyncMarketResource.__init__>
        super().__init__(wrapper.market)

    # <torn-sdk:custom-class AsyncMarketResource>
    # </torn-sdk:custom-class AsyncMarketResource>


AsyncResourceRegistry.register("market", AsyncMarketResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
