"""Public typed property resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapper
from TornAPIWrapper.endpoints.property import Property

from torn_sdk.core.resource import Resource, ResourceRegistry
from torn_sdk.resources._generated.property import (
    GeneratedPropertyResourceMixin,
)


class PropertyResource(GeneratedPropertyResourceMixin, Resource[Property]):
    """
    Provide typed access to Torn property endpoints.

    Attributes:
        endpoint (Property): Underlying TornAPIWrapper property endpoint.

    Args:
        wrapper (TornAPIWrapper): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapper) -> None:
        # <torn-sdk:custom-method PropertyResource.__init__>
        # </torn-sdk:custom-method PropertyResource.__init__>
        super().__init__(wrapper.property)

    # <torn-sdk:custom-class PropertyResource>
    # </torn-sdk:custom-class PropertyResource>


ResourceRegistry.register("property", PropertyResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
