"""Public typed torn resource registered with Torn SDK."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from TornAPIWrapper import TornAPIWrapper
from TornAPIWrapper.endpoints.torn import Torn

from torn_sdk.core.resource import Resource, ResourceRegistry
from torn_sdk.resources._generated.torn import GeneratedTornResourceMixin


class TornResource(GeneratedTornResourceMixin, Resource[Torn]):
    """
    Provide typed access to Torn torn endpoints.

    Attributes:
        endpoint (Torn): Underlying TornAPIWrapper torn endpoint.

    Args:
        wrapper (TornAPIWrapper): Configured TornAPIWrapper client.
    """

    def __init__(self, wrapper: TornAPIWrapper) -> None:
        # <torn-sdk:custom-method TornResource.__init__>
        # </torn-sdk:custom-method TornResource.__init__>
        super().__init__(wrapper.torn)

    # <torn-sdk:custom-class TornResource>
    # </torn-sdk:custom-class TornResource>


ResourceRegistry.register("torn", TornResource)

# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
