"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionAttackResultType


class AttackPlayerSimplified(TornModel):
    """
    Pydantic model for the AttackPlayerSimplified Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        faction_id (int | None): Torn API field `faction_id`.
    """

    # <torn-sdk:custom-class AttackPlayerSimplified>
    # </torn-sdk:custom-class AttackPlayerSimplified>
    id: int
    faction_id: int | None


class AttackSimplified(TornModel):
    """
    Pydantic model for the AttackSimplified Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        code (str): Torn API field `code`.
        started (int): Attack start timestamp.
        ended (int): Attack end timestamp.
        attacker (AttackPlayerSimplified | None): Torn API field `attacker`.
        defender (AttackPlayerSimplified): Torn API field `defender`.
        result (FactionAttackResultType): Torn API field `result`.
        respect_gain (float): Torn API field `respect_gain`.
        respect_loss (float): Torn API field `respect_loss`.
    """

    # <torn-sdk:custom-class AttackSimplified>
    # </torn-sdk:custom-class AttackSimplified>
    id: int
    code: str
    started: int
    ended: int
    attacker: AttackPlayerSimplified | None
    defender: AttackPlayerSimplified
    result: FactionAttackResultType
    respect_gain: float
    respect_loss: float


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class UserAttacksFullResponse(TornModel):
    """
    Pydantic model for the UserAttacksFullResponse Torn API response.

    Attributes:
        attacks (list[AttackSimplified]): Torn API field `attacks`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class UserAttacksFullResponse>
    # </torn-sdk:custom-class UserAttacksFullResponse>
    attacks: list[AttackSimplified]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
