"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class UserCalendar(TornModel):
    """
    Pydantic model for the UserCalendar Torn API response.

    Attributes:
        start_time (str): Event start time displayed in TCT.
    """

    # <torn-sdk:custom-class UserCalendar>
    # </torn-sdk:custom-class UserCalendar>
    start_time: str


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
