# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class UserCoolDowns(TornModel):
    drug: int
    medical: int
    booster: int
