"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import UserCrimeUniquesRewardAmmoType


class UserCrimeAttempts(TornModel):
    """
    Pydantic model for the UserCrimeAttempts Torn API response.

    Attributes:
        total (int): Torn API field `total`.
        success (int): Torn API field `success`.
        fail (int): Torn API field `fail`.
        critical_fail (int): Torn API field `critical_fail`.
        subcrimes (list[UserSubcrime]): Torn API field `subcrimes`.
    """

    # <torn-sdk:custom-class UserCrimeAttempts>
    # </torn-sdk:custom-class UserCrimeAttempts>
    total: int
    success: int
    fail: int
    critical_fail: int
    subcrimes: list[UserSubcrime]


class UserCrimeDetailsBootlegging(TornModel):
    """
    Pydantic model for the UserCrimeDetailsBootlegging Torn API response.

    Attributes:
        online_store (UserCrimeDetailsBootleggingOnlineStore): Online store statistics.
        dvd_sales (UserCrimeDetailsBootleggingDvdSales): DVD sales statistics.
        dvds_copied (int): Torn API field `dvds_copied`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsBootlegging>
    # </torn-sdk:custom-class UserCrimeDetailsBootlegging>
    online_store: UserCrimeDetailsBootleggingOnlineStore
    dvd_sales: UserCrimeDetailsBootleggingDvdSales
    dvds_copied: int | None = None


class UserCrimeDetailsCardSkimming(TornModel):
    """
    Pydantic model for the UserCrimeDetailsCardSkimming Torn API response.

    Attributes:
        card_details (UserCrimeDetailsCardSkimmingCardDetails): Torn API field `card_details`.
        skimmers (UserCrimeDetailsCardSkimmingSkimmers): Torn API field `skimmers`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsCardSkimming>
    # </torn-sdk:custom-class UserCrimeDetailsCardSkimming>
    card_details: UserCrimeDetailsCardSkimmingCardDetails
    skimmers: UserCrimeDetailsCardSkimmingSkimmers


class UserCrimeDetailsCracking(TornModel):
    """
    Pydantic model for the UserCrimeDetailsCracking Torn API response.

    Attributes:
        brute_force_cycles (int): Torn API field `brute_force_cycles`.
        encryption_layers_broken (int): Torn API field `encryption_layers_broken`.
        highest_mips (int): Torn API field `highest_mips`.
        chars_guessed (int): Torn API field `chars_guessed`.
        chars_guessed_total (int): Torn API field `chars_guessed_total`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsCracking>
    # </torn-sdk:custom-class UserCrimeDetailsCracking>
    brute_force_cycles: int
    encryption_layers_broken: int
    highest_mips: int
    chars_guessed: int
    chars_guessed_total: int


class UserCrimeDetailsGraffiti(TornModel):
    """
    Pydantic model for the UserCrimeDetailsGraffiti Torn API response.

    Attributes:
        cans_used (int): Torn API field `cans_used`.
        most_graffiti_in_one_area (int): Torn API field `most_graffiti_in_one_area`.
        most_graffiti_simultaneously (int): Torn API field `most_graffiti_simultaneously`.
        graffiti_removed (int): Torn API field `graffiti_removed`.
        cost_to_city (int): Torn API field `cost_to_city`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsGraffiti>
    # </torn-sdk:custom-class UserCrimeDetailsGraffiti>
    cans_used: int
    most_graffiti_in_one_area: int
    most_graffiti_simultaneously: int
    graffiti_removed: int
    cost_to_city: int


class UserCrimeDetailsHustling(TornModel):
    """
    Pydantic model for the UserCrimeDetailsHustling Torn API response.

    Attributes:
        total_audience_gathered (int): Torn API field `total_audience_gathered`.
        biggest_money_won (int): Torn API field `biggest_money_won`.
        shill_money_collected (int): Torn API field `shill_money_collected`.
        pickpocket_money_collected (int): Torn API field `pickpocket_money_collected`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsHustling>
    # </torn-sdk:custom-class UserCrimeDetailsHustling>
    total_audience_gathered: int
    biggest_money_won: int
    shill_money_collected: int
    pickpocket_money_collected: int


class UserCrimeDetailsScamming(TornModel):
    """
    Pydantic model for the UserCrimeDetailsScamming Torn API response.

    Attributes:
        most_responses (int): Torn API field `most_responses`.
        zones (UserCrimeDetailsScammingZones): Torn API field `zones`.
        concerns (UserCrimeDetailsScammingConcerns): Torn API field `concerns`.
        payouts (UserCrimeDetailsScammingPayouts): Torn API field `payouts`.
        emails (UserCrimeDetailsScammingEmails): Torn API field `emails`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsScamming>
    # </torn-sdk:custom-class UserCrimeDetailsScamming>
    most_responses: int = 0
    zones: UserCrimeDetailsScammingZones
    concerns: UserCrimeDetailsScammingConcerns
    payouts: UserCrimeDetailsScammingPayouts
    emails: UserCrimeDetailsScammingEmails


class UserCrimeDetailsShoplifting(TornModel):
    """
    Pydantic model for the UserCrimeDetailsShoplifting Torn API response.

    Attributes:
        average_notoriety (int): Torn API field `average_notoriety`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsShoplifting>
    # </torn-sdk:custom-class UserCrimeDetailsShoplifting>
    average_notoriety: int


class UserCrimeRewardAmmo(TornModel):
    """
    Pydantic model for the UserCrimeRewardAmmo Torn API response.

    Attributes:
        standard (int): Torn API field `standard`.
        special (int): Torn API field `special`.
    """

    # <torn-sdk:custom-class UserCrimeRewardAmmo>
    # </torn-sdk:custom-class UserCrimeRewardAmmo>
    standard: int
    special: int


class UserCrimeRewardItem(TornModel):
    """
    Pydantic model for the UserCrimeRewardItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserCrimeRewardItem>
    # </torn-sdk:custom-class UserCrimeRewardItem>
    id: int
    amount: int


class UserCrimeRewards(TornModel):
    """
    Pydantic model for the UserCrimeRewards Torn API response.

    Attributes:
        money (int): Torn API field `money`.
        ammo (UserCrimeRewardAmmo): Torn API field `ammo`.
        items (list[UserCrimeRewardItem]): Torn API field `items`.
    """

    # <torn-sdk:custom-class UserCrimeRewards>
    # </torn-sdk:custom-class UserCrimeRewards>
    money: int
    ammo: UserCrimeRewardAmmo
    items: list[UserCrimeRewardItem]


class UserCrimeUniques(TornModel):
    """
    Pydantic model for the UserCrimeUniques Torn API response.

    Attributes:
        id (int): Unique result id.
        rewards (UserCrimeUniquesReward): Torn API field `rewards`.
    """

    # <torn-sdk:custom-class UserCrimeUniques>
    # </torn-sdk:custom-class UserCrimeUniques>
    id: int
    rewards: UserCrimeUniquesReward


class UserCrimeUniquesReward(TornModel):
    """
    Pydantic model for the UserCrimeUniquesReward Torn API response.

    Attributes:
        items (list[UserCrimeRewardItem]): Torn API field `items`.
        money (UserCrimeUniquesRewardMoney | None): Torn API field `money`.
        ammo (UserCrimeUniquesRewardAmmo | None): Torn API field `ammo`.
    """

    # <torn-sdk:custom-class UserCrimeUniquesReward>
    # </torn-sdk:custom-class UserCrimeUniquesReward>
    items: list[UserCrimeRewardItem]
    money: UserCrimeUniquesRewardMoney | None
    ammo: UserCrimeUniquesRewardAmmo | None


class UserCrimeUniquesRewardAmmo(TornModel):
    """
    Pydantic model for the UserCrimeUniquesRewardAmmo Torn API response.

    Attributes:
        amount (int): Torn API field `amount`.
        type (UserCrimeUniquesRewardAmmoType): Torn API field `type`.
    """

    # <torn-sdk:custom-class UserCrimeUniquesRewardAmmo>
    # </torn-sdk:custom-class UserCrimeUniquesRewardAmmo>
    amount: int
    type: UserCrimeUniquesRewardAmmoType


class UserCrimeUniquesRewardMoney(TornModel):
    """
    Pydantic model for the UserCrimeUniquesRewardMoney Torn API response.

    Attributes:
        min (int): Torn API field `min`.
        max (int): Torn API field `max`.
    """

    # <torn-sdk:custom-class UserCrimeUniquesRewardMoney>
    # </torn-sdk:custom-class UserCrimeUniquesRewardMoney>
    min: int
    max: int


class UserSubcrime(TornModel):
    """
    Pydantic model for the UserSubcrime Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        total (int): Torn API field `total`.
        success (int): Torn API field `success`.
        fail (int): Torn API field `fail`.
    """

    # <torn-sdk:custom-class UserSubcrime>
    # </torn-sdk:custom-class UserSubcrime>
    id: int
    total: int
    success: int
    fail: int


class UserCrimeDetailsBootleggingDvdSales(TornModel):
    """
    DVD sales statistics.

    Attributes:
        action (int): Torn API field `action`.
        comedy (int): Torn API field `comedy`.
        drama (int): Torn API field `drama`.
        fantasy (int): Torn API field `fantasy`.
        horror (int): Torn API field `horror`.
        romance (int): Torn API field `romance`.
        thriller (int): Torn API field `thriller`.
        sci_fi (int): Torn API field `sci_fi`.
        total (int): Torn API field `total`.
        earnings (int): Torn API field `earnings`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsBootleggingDvdSales>
    # </torn-sdk:custom-class UserCrimeDetailsBootleggingDvdSales>
    action: int
    comedy: int
    drama: int
    fantasy: int
    horror: int
    romance: int
    thriller: int
    sci_fi: int
    total: int
    earnings: int


class UserCrimeDetailsBootleggingOnlineStore(TornModel):
    """
    Online store statistics.

    Attributes:
        earnings (int): Torn API field `earnings`.
        visits (int): Torn API field `visits`.
        customers (int): Torn API field `customers`.
        sales (int): Torn API field `sales`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsBootleggingOnlineStore>
    # </torn-sdk:custom-class UserCrimeDetailsBootleggingOnlineStore>
    earnings: int
    visits: int
    customers: int
    sales: int


class UserCrimeDetailsCardSkimmingCardDetails(TornModel):
    """
    Pydantic model for the UserCrimeDetailsCardSkimmingCardDetails Torn API response.

    Attributes:
        recoverable (int): Torn API field `recoverable`.
        recovered (int): Torn API field `recovered`.
        sold (int): Torn API field `sold`.
        lost (int): Torn API field `lost`.
        areas (list[UserCrimeDetailsCardSkimmingCardDetailsAreasItem]): Torn API field `areas`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsCardSkimmingCardDetails>
    # </torn-sdk:custom-class UserCrimeDetailsCardSkimmingCardDetails>
    recoverable: int
    recovered: int
    sold: int
    lost: int
    areas: list[UserCrimeDetailsCardSkimmingCardDetailsAreasItem]


class UserCrimeDetailsCardSkimmingCardDetailsAreasItem(TornModel):
    """
    Pydantic model for the UserCrimeDetailsCardSkimmingCardDetailsAreasItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsCardSkimmingCardDetailsAreasItem>
    # </torn-sdk:custom-class UserCrimeDetailsCardSkimmingCardDetailsAreasItem>
    id: int
    amount: int


class UserCrimeDetailsCardSkimmingSkimmers(TornModel):
    """
    Pydantic model for the UserCrimeDetailsCardSkimmingSkimmers Torn API response.

    Attributes:
        active (int): Torn API field `active`.
        most_lucrative (int): Torn API field `most_lucrative`.
        oldest_recovered (int): Torn API field `oldest_recovered`.
        lost (int): Torn API field `lost`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsCardSkimmingSkimmers>
    # </torn-sdk:custom-class UserCrimeDetailsCardSkimmingSkimmers>
    active: int
    most_lucrative: int
    oldest_recovered: int
    lost: int


class UserCrimeDetailsScammingConcerns(TornModel):
    """
    Pydantic model for the UserCrimeDetailsScammingConcerns Torn API response.

    Attributes:
        attempts (int): Torn API field `attempts`.
        resolved (int): Torn API field `resolved`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsScammingConcerns>
    # </torn-sdk:custom-class UserCrimeDetailsScammingConcerns>
    attempts: int = 0
    resolved: int = 0


class UserCrimeDetailsScammingEmails(TornModel):
    """
    Pydantic model for the UserCrimeDetailsScammingEmails Torn API response.

    Attributes:
        scraper (int): Torn API field `scraper`.
        phisher (int): Torn API field `phisher`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsScammingEmails>
    # </torn-sdk:custom-class UserCrimeDetailsScammingEmails>
    scraper: int = 0
    phisher: int = 0


class UserCrimeDetailsScammingPayouts(TornModel):
    """
    Pydantic model for the UserCrimeDetailsScammingPayouts Torn API response.

    Attributes:
        low (int): Torn API field `low`.
        medium (int): Torn API field `medium`.
        high (int): Torn API field `high`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsScammingPayouts>
    # </torn-sdk:custom-class UserCrimeDetailsScammingPayouts>
    low: int = 0
    medium: int = 0
    high: int = 0


class UserCrimeDetailsScammingZones(TornModel):
    """
    Pydantic model for the UserCrimeDetailsScammingZones Torn API response.

    Attributes:
        red (int): Torn API field `red`.
        neutral (int): Torn API field `neutral`.
        concern (int): Torn API field `concern`.
        sensitivity (int): Torn API field `sensitivity`.
        temptation (int): Torn API field `temptation`.
        hesitation (int): Torn API field `hesitation`.
        low_reward (int): Torn API field `low_reward`.
        medium_reward (int): Torn API field `medium_reward`.
        high_reward (int): Torn API field `high_reward`.
    """

    # <torn-sdk:custom-class UserCrimeDetailsScammingZones>
    # </torn-sdk:custom-class UserCrimeDetailsScammingZones>
    red: int = 0
    neutral: int = 0
    concern: int = 0
    sensitivity: int = 0
    temptation: int = 0
    hesitation: int = 0
    low_reward: int = 0
    medium_reward: int = 0
    high_reward: int = 0


class UserCrime(TornModel):
    """
    Pydantic model for the UserCrime Torn API response.

    Attributes:
        nerve_spent (int): Torn API field `nerve_spent`.
        skill (int): Torn API field `skill`.
        progression_bonus (int): Torn API field `progression_bonus`.
        rewards (UserCrimeRewards): Torn API field `rewards`.
        attempts (UserCrimeAttempts): Torn API field `attempts`.
        uniques (list[UserCrimeUniques]): Torn API field `uniques`.
        miscellaneous (UserCrimeDetailsBootlegging | UserCrimeDetailsGraffiti | UserCrimeDetailsShoplifting | UserCrimeDetailsCardSkimming | UserCrimeDetailsHustling | UserCrimeDetailsCracking | UserCrimeDetailsScamming | None): Miscellaneous stats for specific crime. Results differ based on the cat id.
    """

    # <torn-sdk:custom-class UserCrime>
    # </torn-sdk:custom-class UserCrime>
    nerve_spent: int
    skill: int
    progression_bonus: int
    rewards: UserCrimeRewards
    attempts: UserCrimeAttempts
    uniques: list[UserCrimeUniques]
    miscellaneous: (
        UserCrimeDetailsBootlegging
        | UserCrimeDetailsGraffiti
        | UserCrimeDetailsShoplifting
        | UserCrimeDetailsCardSkimming
        | UserCrimeDetailsHustling
        | UserCrimeDetailsCracking
        | UserCrimeDetailsScamming
        | None
    )


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
