"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import RaceClassType


class RaceCar(TornModel):
    car_item_id: int
    car_item_name: str
    top_speed: int
    acceleration: int
    braking: int
    dirt: int
    handling: int
    safety: int
    tarmac: int
    class_: RaceClassType = Field(alias="class")


class UserRaceCarDetails(TornModel):
    car_item_id: int
    car_item_name: str
    top_speed: int
    acceleration: int
    braking: int
    dirt: int
    handling: int
    safety: int
    tarmac: int
    class_: RaceClassType = Field(alias="class")
    id: int
    car_name: str | None
    worth: int
    points_spent: int
    races_entered: int
    races_won: int
    is_removed: bool
    parts: list[int]


class UserEnlistedCars(TornListModel[UserRaceCarDetails]):
    pass
