"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    ItemMarketListingItemDetailsRarityVariant1Type,
    TornItemAmmoType,
    TornItemType,
    TornItemWeaponType,
)


class ItemMarketListingItemBonus(TornModel):
    """
    Pydantic model for the ItemMarketListingItemBonus Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        description (str): Torn API field `description`.
        value (int): Torn API field `value`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemBonus>
    # </torn-sdk:custom-class ItemMarketListingItemBonus>
    id: int
    title: str
    description: str
    value: int


class ItemMarketListingItemDetails(TornModel):
    """
    Pydantic model for the ItemMarketListingItemDetails Torn API response.

    Attributes:
        uid (int): Torn API field `uid`.
        stats (ItemMarketListingItemStats): Torn API field `stats`.
        bonuses (list[ItemMarketListingItemBonus]): Torn API field `bonuses`.
        rarity (ItemMarketListingItemDetailsRarityVariant1Type | None): Torn API field `rarity`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemDetails>
    # </torn-sdk:custom-class ItemMarketListingItemDetails>
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None


class ItemMarketListingItemStats(TornModel):
    """
    Pydantic model for the ItemMarketListingItemStats Torn API response.

    Attributes:
        damage (float | None): Torn API field `damage`.
        accuracy (float | None): Torn API field `accuracy`.
        armor (float | None): Torn API field `armor`.
        quality (float): Torn API field `quality`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemStats>
    # </torn-sdk:custom-class ItemMarketListingItemStats>
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float


class TornItemDetails(TornModel):
    """
    Pydantic model for the TornItemDetails Torn API response.

    Attributes:
        uid (int): Torn API field `uid`.
        stats (ItemMarketListingItemStats): Torn API field `stats`.
        bonuses (list[ItemMarketListingItemBonus]): Torn API field `bonuses`.
        rarity (ItemMarketListingItemDetailsRarityVariant1Type | None): Torn API field `rarity`.
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        type (TornItemType): Torn API field `type`.
        sub_type (TornItemWeaponType | None): Torn API field `sub_type`.
    """

    # <torn-sdk:custom-class TornItemDetails>
    # </torn-sdk:custom-class TornItemDetails>
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    id: int
    name: str
    type: TornItemType
    sub_type: TornItemWeaponType | None


class UserClothing(TornModel):
    """
    Pydantic model for the UserClothing Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        uid (int): Torn API field `uid`.
        type (TornItemType): Torn API field `type`.
    """

    # <torn-sdk:custom-class UserClothing>
    # </torn-sdk:custom-class UserClothing>
    id: int
    name: str
    uid: int
    type: TornItemType


class UserEquipment(TornModel):
    """
    Pydantic model for the UserEquipment Torn API response.

    Attributes:
        uid (int): Torn API field `uid`.
        stats (ItemMarketListingItemStats): Torn API field `stats`.
        bonuses (list[ItemMarketListingItemBonus]): Torn API field `bonuses`.
        rarity (ItemMarketListingItemDetailsRarityVariant1Type | None): Torn API field `rarity`.
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        type (TornItemType): Torn API field `type`.
        sub_type (TornItemWeaponType | None): Torn API field `sub_type`.
        slot (int): Torn API field `slot`.
        mods (list[UserEquipmentItemMod]): Torn API field `mods`.
        ammo (UserEquipmentAmmo | None): Torn API field `ammo`.
    """

    # <torn-sdk:custom-class UserEquipment>
    # </torn-sdk:custom-class UserEquipment>
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    id: int
    name: str
    type: TornItemType
    sub_type: TornItemWeaponType | None
    slot: int
    mods: list[UserEquipmentItemMod]
    ammo: UserEquipmentAmmo | None


class UserEquipmentAmmo(TornModel):
    """
    Pydantic model for the UserEquipmentAmmo Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        quantity (int): Torn API field `quantity`.
        type (TornItemAmmoType): Torn API field `type`.
    """

    # <torn-sdk:custom-class UserEquipmentAmmo>
    # </torn-sdk:custom-class UserEquipmentAmmo>
    id: int
    name: str
    quantity: int
    type: TornItemAmmoType


class UserEquipmentItemMod(TornModel):
    """
    Pydantic model for the UserEquipmentItemMod Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class UserEquipmentItemMod>
    # </torn-sdk:custom-class UserEquipmentItemMod>
    id: int
    name: str


class UserEquipmentResponse(TornModel):
    """
    Pydantic model for the UserEquipmentResponse Torn API response.

    Attributes:
        equipment (list[UserEquipment]): Torn API field `equipment`.
        clothing (list[UserClothing]): Torn API field `clothing`.
    """

    # <torn-sdk:custom-class UserEquipmentResponse>
    # </torn-sdk:custom-class UserEquipmentResponse>
    equipment: list[UserEquipment]
    clothing: list[UserClothing]


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
