# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import ItemMarketListingItemDetailsRarityVariant1Type, TornItemAmmoType, TornItemType, TornItemWeaponType

class ItemMarketListingItemBonus(TornModel):
    id: int
    title: str
    description: str
    value: int

class ItemMarketListingItemDetails(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None

class ItemMarketListingItemStats(TornModel):
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float

class TornItemDetails(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    id: int
    name: str
    type: TornItemType
    sub_type: TornItemWeaponType | None

class UserClothing(TornModel):
    id: int
    name: str
    uid: int
    type: TornItemType

class UserEquipment(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    id: int
    name: str
    type: TornItemType
    sub_type: TornItemWeaponType | None
    slot: int
    mods: list[UserEquipmentItemMod]
    ammo: UserEquipmentAmmo | None

class UserEquipmentAmmo(TornModel):
    id: int
    name: str
    quantity: int
    type: TornItemAmmoType

class UserEquipmentItemMod(TornModel):
    id: int
    name: str

class UserEquipmentResponse(TornModel):
    equipment: list[UserEquipment]
    clothing: list[UserClothing]
