# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class UserEvent(TornModel):
    id: str
    timestamp: int
    event: str

class UserEventsResponse(TornModel):
    events: list[UserEvent]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
