"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel


class UserFaction(TornModel):
    id: int
    name: str
    tag: str
    tag_image: str
    position: str
    days_in_faction: int


class UserFactionResponse(RootModel[UserFaction | None]):
    pass
