"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class UserGymResponse(TornModel):
    """
    Pydantic model for the UserGymResponse Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class UserGymResponse>
    # </torn-sdk:custom-class UserGymResponse>
    id: int
    name: str


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
