"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class HofValue(TornModel):
    """
    Pydantic model for the HofValue Torn API response.

    Attributes:
        value (int): Torn API field `value`.
        rank (int): Torn API field `rank`.
    """

    # <torn-sdk:custom-class HofValue>
    # </torn-sdk:custom-class HofValue>
    value: int
    rank: int


class HofValueFloat(TornModel):
    """
    Pydantic model for the HofValueFloat Torn API response.

    Attributes:
        value (float): Torn API field `value`.
        rank (int): Torn API field `rank`.
    """

    # <torn-sdk:custom-class HofValueFloat>
    # </torn-sdk:custom-class HofValueFloat>
    value: float
    rank: int


class UserHofStats(TornModel):
    """
    Pydantic model for the UserHofStats Torn API response.

    Attributes:
        attacks (HofValue): Torn API field `attacks`.
        busts (HofValue): Torn API field `busts`.
        defends (HofValue): Torn API field `defends`.
        networth (HofValue): Torn API field `networth`.
        offences (HofValue): Torn API field `offences`.
        revives (HofValue): Torn API field `revives`.
        level (HofValue): Torn API field `level`.
        rank (HofValue): Torn API field `rank`.
        awards (HofValue): Torn API field `awards`.
        racing_skill (HofValueFloat): Torn API field `racing_skill`.
        racing_points (HofValue): Torn API field `racing_points`.
        racing_wins (HofValue): Torn API field `racing_wins`.
        travel_time (HofValue): Torn API field `travel_time`.
        working_stats (HofValue): Torn API field `working_stats`.
        battle_stats (HofValue | None): Torn API field `battle_stats`.
    """

    # <torn-sdk:custom-class UserHofStats>
    # </torn-sdk:custom-class UserHofStats>
    attacks: HofValue
    busts: HofValue
    defends: HofValue
    networth: HofValue
    offences: HofValue
    revives: HofValue
    level: HofValue
    rank: HofValue
    awards: HofValue
    racing_skill: HofValueFloat
    racing_points: HofValue
    racing_wins: HofValue
    travel_time: HofValue
    working_stats: HofValue
    battle_stats: HofValue | None


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
