# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import RootModel

class UserIconPrivate(TornModel):
    id: int
    title: str
    description: str | None
    until: int | None

class UserIconPublic(TornModel):
    id: int
    title: str
    description: str | None

class UserIconsResponse(RootModel[list[UserIconPrivate] | list[UserIconPublic]]):
    pass
