"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel


class UserIconPrivate(TornModel):
    """
    Pydantic model for the UserIconPrivate Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        description (str | None): Torn API field `description`.
        until (int | None): Torn API field `until`.
    """

    # <torn-sdk:custom-class UserIconPrivate>
    # </torn-sdk:custom-class UserIconPrivate>
    id: int
    title: str
    description: str | None
    until: int | None


class UserIconPublic(TornModel):
    """
    Pydantic model for the UserIconPublic Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        description (str | None): Torn API field `description`.
    """

    # <torn-sdk:custom-class UserIconPublic>
    # </torn-sdk:custom-class UserIconPublic>
    id: int
    title: str
    description: str | None


class UserIconsResponse(
    RootModel[list[UserIconPrivate] | list[UserIconPublic]]
):
    """
    Pydantic model for the UserIconsResponse Torn API response.
    """

    # <torn-sdk:custom-class UserIconsResponse>
    # </torn-sdk:custom-class UserIconsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
