"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndTotal Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    links: RequestLinks
    total: int | None = None


class UserInventory(TornModel):
    """
    Pydantic model for the UserInventory Torn API response.

    Attributes:
        items (list[UserInventoryItem]): Torn API field `items`.
        timestamp (int): Torn API field `timestamp`.
    """

    # <torn-sdk:custom-class UserInventory>
    # </torn-sdk:custom-class UserInventory>
    items: list[UserInventoryItem]
    timestamp: int


class UserInventoryItem(TornModel):
    """
    Pydantic model for the UserInventoryItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        amount (int): Torn API field `amount`.
        equipped (bool): Torn API field `equipped`.
        name (str): Torn API field `name`.
        faction_owned (bool): Torn API field `faction_owned`.
        uid (int | None): Torn API field `uid`.
    """

    # <torn-sdk:custom-class UserInventoryItem>
    # </torn-sdk:custom-class UserInventoryItem>
    id: int
    amount: int
    equipped: bool
    name: str
    faction_owned: bool
    uid: int | None


class UserInventoryResponse(TornModel):
    """
    Pydantic model for the UserInventoryResponse Torn API response.

    Attributes:
        inventory (UserInventory): Torn API field `inventory`.
        metadata (RequestMetadataWithLinksAndTotal): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class UserInventoryResponse>
    # </torn-sdk:custom-class UserInventoryResponse>
    inventory: UserInventory
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
