"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    links: RequestLinks
    total: int | None = None


class UserInventory(TornModel):
    items: list[UserInventoryItem]
    timestamp: int


class UserInventoryItem(TornModel):
    id: int
    amount: int
    equipped: bool
    name: str
    faction_owned: bool
    uid: int | None


class UserInventoryResponse(TornModel):
    inventory: UserInventory
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")
