# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import ItemMarketListingItemDetailsRarityVariant1Type

class ItemMarketListingItemBonus(TornModel):
    id: int
    title: str
    description: str
    value: int

class ItemMarketListingItemStats(TornModel):
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class UserItemMarkeListingItemDetails(TornModel):
    id: int
    name: str
    type: str
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    uid: int | None
    stats: ItemMarketListingItemStats | None
    bonuses: list[ItemMarketListingItemBonus]

class UserItemMarketListing(TornModel):
    id: int
    price: int
    average_price: int
    amount: int
    is_anonymous: bool
    available: int
    item: UserItemMarkeListingItemDetails

class UserItemMarketResponse(TornModel):
    itemmarket: list[UserItemMarketListing]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
