"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class UserCompanyPoints(TornModel):
    company: UserCompanyPointsCompany
    points: int


class UserCompanyPointsCompany(TornModel):
    id: int
    name: str


class UserJobPointsResponseJobs(TornModel):
    army: int
    casino: int
    education: int
    grocer: int
    law: int
    medical: int


class UserJobPointsResponse(TornModel):
    jobs: UserJobPointsResponseJobs
    companies: list[UserCompanyPoints]
