"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    JobPositionArmyType,
    JobPositionCasinoType,
    JobPositionEducationType,
    JobPositionGrocerType,
    JobPositionLawType,
    JobPositionMedicalType,
)


class UserJobRanks(TornModel):
    """
    Pydantic model for the UserJobRanks Torn API response.

    Attributes:
        army (JobPositionArmyType): Torn API field `army`.
        grocer (JobPositionGrocerType): Torn API field `grocer`.
        casino (JobPositionCasinoType): Torn API field `casino`.
        medical (JobPositionMedicalType): Torn API field `medical`.
        law (JobPositionLawType): Torn API field `law`.
        education (JobPositionEducationType): Torn API field `education`.
    """

    # <torn-sdk:custom-class UserJobRanks>
    # </torn-sdk:custom-class UserJobRanks>
    army: JobPositionArmyType
    grocer: JobPositionGrocerType
    casino: JobPositionCasinoType
    medical: JobPositionMedicalType
    law: JobPositionLawType
    education: JobPositionEducationType


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
