# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import UserLastActionStatusType, UserPlaneImageType, UserStatusStateType

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class UserLastAction(TornModel):
    status: UserLastActionStatusType
    timestamp: int
    relative: str

class UserList(TornModel):
    id: int
    name: str
    level: int
    faction_id: int | None
    last_action: UserLastAction
    status: UserStatus

class UserStatus(TornModel):
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None

class UserListResponse(TornModel):
    list: list[UserList]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
