"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndNanostamp(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndNanostamp Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        nanostamp (str): Use to bypass system limitation when 100 or more logs were inserted within the same second.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndNanostamp>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndNanostamp>
    links: RequestLinks
    nanostamp: str | None = None


class UserLog(TornModel):
    """
    Pydantic model for the UserLog Torn API response.

    Attributes:
        id (str): Torn API field `id`.
        timestamp (int): Torn API field `timestamp`.
        details (UserLogDetails): Torn API field `details`.
        data (UserLogData): Dynamic key-value pairs related to the log.
        params (UserLogParams): Dynamic key-value pairs related to the log.
    """

    # <torn-sdk:custom-class UserLog>
    # </torn-sdk:custom-class UserLog>
    id: str
    timestamp: int
    details: UserLogDetails
    data: UserLogData
    params: UserLogParams


class UserLogData(TornModel):
    """
    Dynamic key-value pairs related to the log.
    """

    # <torn-sdk:custom-class UserLogData>
    # </torn-sdk:custom-class UserLogData>
    pass


class UserLogDetails(TornModel):
    """
    Pydantic model for the UserLogDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        category (str): Torn API field `category`.
    """

    # <torn-sdk:custom-class UserLogDetails>
    # </torn-sdk:custom-class UserLogDetails>
    id: int
    title: str
    category: str


class UserLogParams(TornModel):
    """
    Dynamic key-value pairs related to the log.
    """

    # <torn-sdk:custom-class UserLogParams>
    # </torn-sdk:custom-class UserLogParams>
    pass


class UserLogsResponse(TornModel):
    """
    Pydantic model for the UserLogsResponse Torn API response.

    Attributes:
        log (list[UserLog]): Torn API field `log`.
        metadata (RequestMetadataWithLinksAndNanostamp): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class UserLogsResponse>
    # </torn-sdk:custom-class UserLogsResponse>
    log: list[UserLog]
    metadata: RequestMetadataWithLinksAndNanostamp = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
