# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class UserMeritUpgrade(TornModel):
    id: int
    level: int

class UserMerits(TornModel):
    upgrades: list[UserMeritUpgrade]
    available: int
    used: int
    medals: int
    honors: int
