"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class UserMoneyResponseCityBankVariant1(TornModel):
    amount: int
    profit: int
    duration: int
    interest_rate: float
    until: int
    invested_at: int


class UserMoneyResponseFactionVariant1(TornModel):
    money: int
    points: int


class UserMoneyResponse(TornModel):
    points: int
    wallet: int
    company: int
    vault: int
    cayman_bank: int
    city_bank: UserMoneyResponseCityBankVariant1 | None
    faction: UserMoneyResponseFactionVariant1 | None
    daily_networth: int
