"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    ReviveSettingType,
    UserDonatorStatusType,
    UserGenderType,
    UserLastActionStatusType,
    UserMaritalStatusType,
    UserPlaneImageType,
    UserRankType,
    UserRoleType,
    UserStatusStateType,
    UserTitleType,
)


class ProfileSpouse(TornModel):
    """
    The property 'days_married' is not present if the status is 'Engaged'

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        status (UserMaritalStatusType): Torn API field `status`.
        days_married (int): Torn API field `days_married`.
    """

    # <torn-sdk:custom-class ProfileSpouse>
    # </torn-sdk:custom-class ProfileSpouse>
    id: int
    name: str
    status: UserMaritalStatusType
    days_married: int | None = None


class UserLastAction(TornModel):
    """
    Details about a user's last action.

    Attributes:
        status (UserLastActionStatusType): Torn API field `status`.
        timestamp (int): Torn API field `timestamp`.
        relative (str): Torn API field `relative`.
    """

    # <torn-sdk:custom-class UserLastAction>
    # </torn-sdk:custom-class UserLastAction>
    status: UserLastActionStatusType
    timestamp: int
    relative: str


class UserStatus(TornModel):
    """
    Details about a user's status.

    Attributes:
        description (str): Torn API field `description`.
        details (str | None): Torn API field `details`.
        state (UserStatusStateType | str): Torn API field `state`.
        color (str): Torn API field `color`.
        until (int | None): Torn API field `until`.
        plane_image_type (UserPlaneImageType): This field is populated only if the state is 'Traveling'.
    """

    # <torn-sdk:custom-class UserStatus>
    # </torn-sdk:custom-class UserStatus>
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None


class UserProfileResponseLife(TornModel):
    """
    Pydantic model for the UserProfileResponseLife Torn API response.

    Attributes:
        current (int): Torn API field `current`.
        maximum (int): Torn API field `maximum`.
    """

    # <torn-sdk:custom-class UserProfileResponseLife>
    # </torn-sdk:custom-class UserProfileResponseLife>
    current: int
    maximum: int


class UserProfileResponseProperty(TornModel):
    """
    Pydantic model for the UserProfileResponseProperty Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class UserProfileResponseProperty>
    # </torn-sdk:custom-class UserProfileResponseProperty>
    id: int
    name: str


class UserProfileResponse(TornModel):
    """
    Pydantic model for the UserProfileResponse Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        level (int): Torn API field `level`.
        rank (UserRankType | str): Torn API field `rank`.
        title (UserTitleType | str): Torn API field `title`.
        donator_status (UserDonatorStatusType | None): Torn API field `donator_status`.
        age (int): Age in days.
        signed_up (int): Torn API field `signed_up`.
        faction_id (int | None): Torn API field `faction_id`.
        honor_id (int): Torn API field `honor_id`.
        revive_setting (ReviveSettingType): This field is shown only for 'Limited' or 'Full' access keys and only for the key owner, otherwise, the status is 'Unknown'.
        property (UserProfileResponseProperty): Torn API field `property`.
        image (str | None): Torn API field `image`.
        gender (UserGenderType): Torn API field `gender`.
        revivable (bool): Torn API field `revivable`.
        role (UserRoleType): Torn API field `role`.
        status (UserStatus): Torn API field `status`.
        spouse (ProfileSpouse | None): Torn API field `spouse`.
        awards (int): Torn API field `awards`.
        friends (int): Torn API field `friends`.
        enemies (int): Torn API field `enemies`.
        forum_posts (int): Torn API field `forum_posts`.
        karma (int): Torn API field `karma`.
        last_action (UserLastAction): Torn API field `last_action`.
        life (UserProfileResponseLife): Torn API field `life`.
    """

    # <torn-sdk:custom-class UserProfileResponse>
    # </torn-sdk:custom-class UserProfileResponse>
    id: int
    name: str
    level: int
    rank: UserRankType | str
    title: UserTitleType | str
    donator_status: UserDonatorStatusType | None
    age: int
    signed_up: int
    faction_id: int | None
    honor_id: int
    revive_setting: ReviveSettingType
    property: UserProfileResponseProperty
    image: str | None
    gender: UserGenderType
    revivable: bool
    role: UserRoleType
    status: UserStatus
    spouse: ProfileSpouse | None
    awards: int
    friends: int
    enemies: int
    forum_posts: int
    karma: int
    last_action: UserLastAction
    life: UserProfileResponseLife


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
