"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    PropertyModificationType,
    PropertyStaffType,
    UserPropertyDetailsExtendedForRentStatusType,
    UserPropertyDetailsExtendedForSaleStatusType,
    UserPropertyDetailsExtendedRentedStatusType,
    UserPropertyDetailsExtendedStatusType,
)


class BasicProperty(TornModel):
    """
    Pydantic model for the BasicProperty Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class BasicProperty>
    # </torn-sdk:custom-class BasicProperty>
    id: int
    name: str


class BasicUser(TornModel):
    """
    Pydantic model for the BasicUser Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class BasicUser>
    # </torn-sdk:custom-class BasicUser>
    id: int
    name: str


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class UserPropertyBasicDetails(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyBasicDetailsUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyBasicDetailsStaffItem]): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetails>
    # </torn-sdk:custom-class UserPropertyBasicDetails>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyBasicDetailsUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyBasicDetailsStaffItem]


class UserPropertyDetailsExtended(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtended Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyDetailsExtendedUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyDetailsExtendedStaffItem]): Torn API field `staff`.
        used_by (list[BasicUser]): Torn API field `used_by`.
        status (UserPropertyDetailsExtendedStatusType): Torn API field `status`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtended>
    # </torn-sdk:custom-class UserPropertyDetailsExtended>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedStatusType


class UserPropertyDetailsExtendedForRent(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForRent Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyDetailsExtendedForRentUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyDetailsExtendedForRentStaffItem]): Torn API field `staff`.
        used_by (list[BasicUser]): Torn API field `used_by`.
        status (UserPropertyDetailsExtendedForRentStatusType): Torn API field `status`.
        cost (int): Torn API field `cost`.
        cost_per_day (int): Torn API field `cost_per_day`.
        rental_period (int): Torn API field `rental_period`.
        renter_asked (BasicUser): Torn API field `renter_asked`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForRent>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForRent>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedForRentUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedForRentStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedForRentStatusType
    cost: int
    cost_per_day: int
    rental_period: int
    renter_asked: BasicUser | None = None


class UserPropertyDetailsExtendedForSale(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForSale Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyDetailsExtendedForSaleUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyDetailsExtendedForSaleStaffItem]): Torn API field `staff`.
        used_by (list[BasicUser]): Torn API field `used_by`.
        status (UserPropertyDetailsExtendedForSaleStatusType): Torn API field `status`.
        cost (int): Torn API field `cost`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForSale>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForSale>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedForSaleUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedForSaleStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedForSaleStatusType
    cost: int


class UserPropertyDetailsExtendedRented(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedRented Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyDetailsExtendedRentedUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyDetailsExtendedRentedStaffItem]): Torn API field `staff`.
        used_by (list[BasicUser]): Torn API field `used_by`.
        status (UserPropertyDetailsExtendedRentedStatusType): Torn API field `status`.
        cost (int): Torn API field `cost`.
        cost_per_day (int): Torn API field `cost_per_day`.
        rental_period (int): Torn API field `rental_period`.
        rental_period_remaining (int): Torn API field `rental_period_remaining`.
        rented_by (BasicUser): Torn API field `rented_by`.
        lease_extension (UserPropertyDetailsExtendedRentedLeaseExtensionVariant1 | None): Torn API field `lease_extension`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedRented>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedRented>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedRentedUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedRentedStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedRentedStatusType
    cost: int
    cost_per_day: int
    rental_period: int
    rental_period_remaining: int
    rented_by: BasicUser
    lease_extension: (
        UserPropertyDetailsExtendedRentedLeaseExtensionVariant1 | None
    )


class UserPropertyBasicDetailsStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetailsStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetailsStaffItem>
    # </torn-sdk:custom-class UserPropertyBasicDetailsStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyBasicDetailsUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetailsUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetailsUpkeep>
    # </torn-sdk:custom-class UserPropertyBasicDetailsUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedForRentStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForRentStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForRentStaffItem>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForRentStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyDetailsExtendedForRentUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForRentUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForRentUpkeep>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForRentUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedForSaleStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForSaleStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForSaleStaffItem>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForSaleStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyDetailsExtendedForSaleUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedForSaleUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedForSaleUpkeep>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedForSaleUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedRentedLeaseExtensionVariant1(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedRentedLeaseExtensionVariant1 Torn API response.

    Attributes:
        cost (int): Torn API field `cost`.
        period (int): Torn API field `period`.
        created_at (int): Torn API field `created_at`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedRentedLeaseExtensionVariant1>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedRentedLeaseExtensionVariant1>
    cost: int
    period: int
    created_at: int


class UserPropertyDetailsExtendedRentedStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedRentedStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedRentedStaffItem>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedRentedStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyDetailsExtendedRentedUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedRentedUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedRentedUpkeep>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedRentedUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedStaffItem>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyDetailsExtendedUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedUpkeep>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedUpkeep>
    property: int
    staff: int


class UserPropertiesResponse(TornModel):
    """
    Pydantic model for the UserPropertiesResponse Torn API response.

    Attributes:
        properties (list[UserPropertyBasicDetails | UserPropertyDetailsExtended | UserPropertyDetailsExtendedRented | UserPropertyDetailsExtendedForRent | UserPropertyDetailsExtendedForSale]): Torn API field `properties`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class UserPropertiesResponse>
    # </torn-sdk:custom-class UserPropertiesResponse>
    properties: list[
        UserPropertyBasicDetails
        | UserPropertyDetailsExtended
        | UserPropertyDetailsExtendedRented
        | UserPropertyDetailsExtendedForRent
        | UserPropertyDetailsExtendedForSale
    ]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
