# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import RaceClassType, RaceStatusType

class Race(TornModel):
    id: int
    title: str
    track_id: int
    creator_id: int
    status: RaceStatusType
    laps: int
    participants: RaceParticipants
    schedule: RaceSchedule
    requirements: RaceRequirements
    is_official: bool

class RacerDetails(TornModel):
    driver_id: int
    position: int | None
    car_id: int
    car_item_id: int
    car_item_name: str
    car_class: RaceClassType
    has_crashed: bool | None
    best_lap_time: float | None
    race_time: float | None
    time_ended: int | None

class RacingRaceDetails(TornModel):
    id: int
    title: str
    track_id: int
    creator_id: int
    status: RaceStatusType
    laps: int
    participants: RacingRaceDetailsParticipants
    schedule: RacingRaceDetailsSchedule
    requirements: RacingRaceDetailsRequirements
    is_official: bool
    results: list[RacerDetails]

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class UserRaceDetails(TornModel):
    id: int
    title: str
    track_id: int
    creator_id: int
    status: RaceStatusType
    laps: int
    participants: UserRaceDetailsParticipants
    schedule: UserRaceDetailsSchedule
    requirements: UserRaceDetailsRequirements
    is_official: bool
    results: list[RacerDetails]
    skill_gain: float | None

class RaceParticipants(TornModel):
    minimum: int
    maximum: int
    current: int

class RaceRequirements(TornModel):
    car_class: RaceClassType | None
    driver_class: RaceClassType | None
    car_item_id: int | None
    requires_stock_car: bool
    requires_password: bool
    join_fee: int

class RaceSchedule(TornModel):
    join_from: int
    join_until: int
    start: int
    end: int | None

class RacingRaceDetailsParticipants(TornModel):
    minimum: int
    maximum: int
    current: int

class RacingRaceDetailsRequirements(TornModel):
    car_class: RaceClassType | None
    driver_class: RaceClassType | None
    car_item_id: int | None
    requires_stock_car: bool
    requires_password: bool
    join_fee: int

class RacingRaceDetailsSchedule(TornModel):
    join_from: int
    join_until: int
    start: int
    end: int | None

class UserRaceDetailsParticipants(TornModel):
    minimum: int
    maximum: int
    current: int

class UserRaceDetailsRequirements(TornModel):
    car_class: RaceClassType | None
    driver_class: RaceClassType | None
    car_item_id: int | None
    requires_stock_car: bool
    requires_password: bool
    join_fee: int

class UserRaceDetailsSchedule(TornModel):
    join_from: int
    join_until: int
    start: int
    end: int | None

class UserRacesResponse(TornModel):
    races: list[UserRaceDetails]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
