# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import UserLastActionStatusType

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinksAndTotal(TornModel):
    links: RequestLinks
    total: int | None = None

class UserIconPublic(TornModel):
    id: int
    title: str
    description: str | None

class UserSearch(TornModel):
    id: int
    name: str
    level: int
    online: UserLastActionStatusType
    faction_id: int
    icons: list[UserIconPublic]

class UserSearchResponse(TornModel):
    search: list[UserSearch]
    metadata: RequestMetadataWithLinksAndTotal = Field(alias='_metadata')
