"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class UserStock(TornModel):
    """
    Pydantic model for the UserStock Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        shares (int): Torn API field `shares`.
        transactions (list[UserStockTransaction]): Torn API field `transactions`.
        bonus (UserStockBonus): Torn API field `bonus`.
    """

    # <torn-sdk:custom-class UserStock>
    # </torn-sdk:custom-class UserStock>
    id: int
    shares: int
    transactions: list[UserStockTransaction]
    bonus: UserStockBonus


class UserStockTransaction(TornModel):
    """
    Pydantic model for the UserStockTransaction Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        shares (int): Torn API field `shares`.
        price (float): Torn API field `price`.
        timestamp (int): Torn API field `timestamp`.
    """

    # <torn-sdk:custom-class UserStockTransaction>
    # </torn-sdk:custom-class UserStockTransaction>
    id: int
    shares: int
    price: float
    timestamp: int


class UserStockBonus(TornModel):
    """
    Pydantic model for the UserStockBonus Torn API response.

    Attributes:
        available (bool): Torn API field `available`.
        increment (int): Torn API field `increment`.
        progress (int): Torn API field `progress`.
        frequency (int): Torn API field `frequency`.
    """

    # <torn-sdk:custom-class UserStockBonus>
    # </torn-sdk:custom-class UserStockBonus>
    available: bool
    increment: int
    progress: int
    frequency: int


class UserStocksResponse(TornListModel[UserStock]):
    """
    Pydantic model for the UserStocksResponse Torn API response.
    """

    # <torn-sdk:custom-class UserStocksResponse>
    # </torn-sdk:custom-class UserStocksResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
