"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    TradeItemCompanyType,
    TradeItemFactionType,
    TradeItemItemType,
    TradeItemMoneyType,
    TradeItemNapType,
    TradeItemPropertyType,
)


class TradeItemCompany(TornModel):
    """
    Pydantic model for the TradeItemCompany Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemCompanyType): Torn API field `type`.
        details (TradeItemCompanyDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemCompany>
    # </torn-sdk:custom-class TradeItemCompany>
    user_id: int
    type: TradeItemCompanyType
    details: TradeItemCompanyDetails


class TradeItemFaction(TornModel):
    """
    Pydantic model for the TradeItemFaction Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemFactionType): Torn API field `type`.
        details (TradeItemFactionDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemFaction>
    # </torn-sdk:custom-class TradeItemFaction>
    user_id: int
    type: TradeItemFactionType
    details: TradeItemFactionDetails


class TradeItemItem(TornModel):
    """
    Pydantic model for the TradeItemItem Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemItemType): Torn API field `type`.
        details (TradeItemItemDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemItem>
    # </torn-sdk:custom-class TradeItemItem>
    user_id: int
    type: TradeItemItemType
    details: TradeItemItemDetails


class TradeItemMoney(TornModel):
    """
    Pydantic model for the TradeItemMoney Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemMoneyType): Torn API field `type`.
        details (TradeItemMoneyDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemMoney>
    # </torn-sdk:custom-class TradeItemMoney>
    user_id: int
    type: TradeItemMoneyType
    details: TradeItemMoneyDetails


class TradeItemNap(TornModel):
    """
    Pydantic model for the TradeItemNap Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemNapType): Torn API field `type`.
        details (TradeItemNapDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemNap>
    # </torn-sdk:custom-class TradeItemNap>
    user_id: int
    type: TradeItemNapType
    details: TradeItemNapDetails


class TradeItemProperty(TornModel):
    """
    Pydantic model for the TradeItemProperty Torn API response.

    Attributes:
        user_id (int): Torn API field `user_id`.
        type (TradeItemPropertyType): Torn API field `type`.
        details (TradeItemPropertyDetails): Torn API field `details`.
    """

    # <torn-sdk:custom-class TradeItemProperty>
    # </torn-sdk:custom-class TradeItemProperty>
    user_id: int
    type: TradeItemPropertyType
    details: TradeItemPropertyDetails


class TradeItem(
    RootModel[
        TradeItemMoney
        | TradeItemItem
        | TradeItemFaction
        | TradeItemCompany
        | TradeItemProperty
        | TradeItemNap
    ]
):
    """
    Pydantic model for the TradeItem Torn API response.
    """

    # <torn-sdk:custom-class TradeItem>
    # </torn-sdk:custom-class TradeItem>


class UserFactionBasic(TornModel):
    """
    Pydantic model for the UserFactionBasic Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class UserFactionBasic>
    # </torn-sdk:custom-class UserFactionBasic>
    id: int
    name: str


class UserTrade(TornModel):
    """
    Pydantic model for the UserTrade Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        timestamp (int): This field is depracted and replaced with 'completed_at' field.
        completed_at (int | None): Populated when selected category is 'finished'.
        expires_at (int | None): Populated when selected category is 'ongoing'.
        modified_at (int | None): Populated when selected category is 'ongoing'.
        user (UserTradeParticipant): Torn API field `user`.
        trader (UserTradeParticipant): Torn API field `trader`.
    """

    # <torn-sdk:custom-class UserTrade>
    # </torn-sdk:custom-class UserTrade>
    id: int
    timestamp: int | None = None
    completed_at: int | None
    expires_at: int | None
    modified_at: int | None
    user: UserTradeParticipant
    trader: UserTradeParticipant


class UserTradeParticipant(TornModel):
    """
    Pydantic model for the UserTradeParticipant Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class UserTradeParticipant>
    # </torn-sdk:custom-class UserTradeParticipant>
    id: int
    name: str


class TradeItemCompanyDetails(TornModel):
    """
    Pydantic model for the TradeItemCompanyDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        value (int): Torn API field `value`.
    """

    # <torn-sdk:custom-class TradeItemCompanyDetails>
    # </torn-sdk:custom-class TradeItemCompanyDetails>
    id: int
    name: str
    value: int


class TradeItemFactionDetails(TornModel):
    """
    Pydantic model for the TradeItemFactionDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        respect (int): Torn API field `respect`.
    """

    # <torn-sdk:custom-class TradeItemFactionDetails>
    # </torn-sdk:custom-class TradeItemFactionDetails>
    id: int
    name: str
    respect: int


class TradeItemItemDetails(TornModel):
    """
    Pydantic model for the TradeItemItemDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        uid (int | None): Torn API field `uid`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class TradeItemItemDetails>
    # </torn-sdk:custom-class TradeItemItemDetails>
    id: int
    uid: int | None
    amount: int


class TradeItemMoneyDetails(TornModel):
    """
    Pydantic model for the TradeItemMoneyDetails Torn API response.

    Attributes:
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class TradeItemMoneyDetails>
    # </torn-sdk:custom-class TradeItemMoneyDetails>
    amount: int


class TradeItemNapDetails(TornModel):
    """
    Pydantic model for the TradeItemNapDetails Torn API response.

    Attributes:
        days (int): Torn API field `days`.
        factions (list[UserFactionBasic]): Torn API field `factions`.
    """

    # <torn-sdk:custom-class TradeItemNapDetails>
    # </torn-sdk:custom-class TradeItemNapDetails>
    days: int
    factions: list[UserFactionBasic]


class TradeItemPropertyDetails(TornModel):
    """
    Pydantic model for the TradeItemPropertyDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        happiness (int): Torn API field `happiness`.
    """

    # <torn-sdk:custom-class TradeItemPropertyDetails>
    # </torn-sdk:custom-class TradeItemPropertyDetails>
    id: int
    happiness: int


class UserTradeDetailed(TornModel):
    """
    Pydantic model for the UserTradeDetailed Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        timestamp (int): This field is depracted and replaced with 'completed_at' field.
        completed_at (int | None): Populated when selected category is 'finished'.
        expires_at (int | None): Populated when selected category is 'ongoing'.
        modified_at (int | None): Populated when selected category is 'ongoing'.
        user (UserTradeParticipant): Torn API field `user`.
        trader (UserTradeParticipant): Torn API field `trader`.
        items (list[TradeItem]): Torn API field `items`.
    """

    # <torn-sdk:custom-class UserTradeDetailed>
    # </torn-sdk:custom-class UserTradeDetailed>
    id: int
    timestamp: int | None = None
    completed_at: int | None
    expires_at: int | None
    modified_at: int | None
    user: UserTradeParticipant
    trader: UserTradeParticipant
    items: list[TradeItem]


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
