# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class UserTrade(TornModel):
    id: int
    timestamp: int | None = None
    completed_at: int | None
    expires_at: int | None
    modified_at: int | None
    user: UserTradeParticipant
    trader: UserTradeParticipant

class UserTradeParticipant(TornModel):
    id: int
    name: str

class UserTradesResponse(TornModel):
    trades: list[UserTrade]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
