# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field
from torn_sdk.models.types import FactionAttackResultType

class AttackPlayerSimplified(TornModel):
    id: int
    faction_id: int | None

class AttackSimplified(TornModel):
    id: int
    code: str
    started: int
    ended: int
    attacker: AttackPlayerSimplified | None
    defender: AttackPlayerSimplified
    result: FactionAttackResultType
    respect_gain: float
    respect_loss: float

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class AttacksFullResponse(TornModel):
    attacks: list[AttackSimplified]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
