"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class FactionBalanceFaction(TornModel):
    money: int
    points: int
    scope: int


class FactionBalanceMembersItem(TornModel):
    id: int
    username: str
    money: int
    points: int


class FactionBalance(TornModel):
    faction: FactionBalanceFaction
    members: list[FactionBalanceMembersItem]
