"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel


class FactionCrimeExpResponse(RootModel[list[int]]):
    """
    Pydantic model for the FactionCrimeExpResponse Torn API response.
    """

    # <torn-sdk:custom-class FactionCrimeExpResponse>
    # </torn-sdk:custom-class FactionCrimeExpResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
