"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    FactionCrimeItemOutcomeType,
    FactionCrimeStatusType,
    FactionCrimeUserItemOutcomeType,
    FactionCrimeUserOutcomeType,
    FactionOrganizedCrimePayoutType,
    TornOrganizedCrimePositionIdType,
)


class FactionCrimeReward(TornModel):
    money: int
    items: list[FactionCrimeRewardItem]
    respect: int
    scope: int
    payout: FactionCrimeRewardPayout | None


class FactionCrimeRewardItem(TornModel):
    id: int
    quantity: int


class FactionCrimeRewardPayout(TornModel):
    type: FactionOrganizedCrimePayoutType
    percentage: float
    paid_by: int
    paid_at: int


class FactionCrimeSlot(TornModel):
    position: str
    position_info: FactionSlotPositionInfo
    item_requirement: FactionCrimeSlotItemRequirementVariant1 | None
    user: FactionCrimeUser | None
    checkpoint_pass_rate: int


class FactionCrimeUser(TornModel):
    id: int
    outcome: FactionCrimeUserOutcomeType | None
    outcome_duration: int | None = None
    item_outcome: FactionCrimeUserItemOutcome | None
    joined_at: int
    progress: float


class FactionCrimeUserItemOutcome(TornModel):
    owned_by: FactionCrimeUserItemOutcomeType
    item_id: int
    item_uid: int
    outcome: FactionCrimeItemOutcomeType


class FactionSlotPositionInfo(TornModel):
    id: TornOrganizedCrimePositionIdType
    label: str
    number: int


class FactionCrimeSlotItemRequirementVariant1(TornModel):
    id: int
    is_reusable: bool
    is_available: bool


class FactionCrime(TornModel):
    id: int
    previous_crime_id: int | None
    name: str
    difficulty: int
    status: FactionCrimeStatusType
    created_at: int
    planning_at: int | None
    ready_at: int | None
    expired_at: int
    executed_at: int | None
    slots: list[FactionCrimeSlot]
    rewards: FactionCrimeReward | None
