"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class FactionWarfareDirtyBomb(TornModel):
    """
    Pydantic model for the FactionWarfareDirtyBomb Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        planted_at (int): Torn API field `planted_at`.
        detonated_at (int): Torn API field `detonated_at`.
        faction (FactionWarfareDirtyBombTargetFaction): Torn API field `faction`.
        user (FactionWarfareDirtyBombPlanter | None): Torn API field `user`.
    """

    # <torn-sdk:custom-class FactionWarfareDirtyBomb>
    # </torn-sdk:custom-class FactionWarfareDirtyBomb>
    id: int
    planted_at: int
    detonated_at: int
    faction: FactionWarfareDirtyBombTargetFaction
    user: FactionWarfareDirtyBombPlanter | None


class FactionWarfareDirtyBombPlanter(TornModel):
    """
    Pydantic model for the FactionWarfareDirtyBombPlanter Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class FactionWarfareDirtyBombPlanter>
    # </torn-sdk:custom-class FactionWarfareDirtyBombPlanter>
    id: int
    name: str


class FactionWarfareDirtyBombTargetFaction(TornModel):
    """
    Pydantic model for the FactionWarfareDirtyBombTargetFaction Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        respect_lost (int): Torn API field `respect_lost`.
    """

    # <torn-sdk:custom-class FactionWarfareDirtyBombTargetFaction>
    # </torn-sdk:custom-class FactionWarfareDirtyBombTargetFaction>
    id: int
    name: str
    respect_lost: int


class FactionWarfareDirtyBombsResponse(TornListModel[FactionWarfareDirtyBomb]):
    """
    Pydantic model for the FactionWarfareDirtyBombsResponse Torn API response.
    """

    # <torn-sdk:custom-class FactionWarfareDirtyBombsResponse>
    # </torn-sdk:custom-class FactionWarfareDirtyBombsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
