"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import MarketSpecializedBazaarCategoryType


class FactionInventoryItem(TornModel):
    """
    Pydantic model for the FactionInventoryItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        type (MarketSpecializedBazaarCategoryType): Torn API field `type`.
        amount (int): Torn API field `amount`.
        uids (list[int]): Returns up to 250 uids.
        loaned (FactionInventoryItemLoanedVariant1 | None): Torn API field `loaned`.
    """

    # <torn-sdk:custom-class FactionInventoryItem>
    # </torn-sdk:custom-class FactionInventoryItem>
    id: int
    name: str
    type: MarketSpecializedBazaarCategoryType
    amount: int
    uids: list[int]
    loaned: FactionInventoryItemLoanedVariant1 | None


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndTotal Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    links: RequestLinks
    total: int | None = None


class FactionInventoryItemLoanedVariant1(TornModel):
    """
    Pydantic model for the FactionInventoryItemLoanedVariant1 Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class FactionInventoryItemLoanedVariant1>
    # </torn-sdk:custom-class FactionInventoryItemLoanedVariant1>
    id: int
    name: str


class FactionInventoryResponse(TornModel):
    """
    Pydantic model for the FactionInventoryResponse Torn API response.

    Attributes:
        inventory_timestamp (int): Torn API field `inventory_timestamp`.
        inventory (list[FactionInventoryItem]): Torn API field `inventory`.
        metadata (RequestMetadataWithLinksAndTotal): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class FactionInventoryResponse>
    # </torn-sdk:custom-class FactionInventoryResponse>
    inventory_timestamp: int
    inventory: list[FactionInventoryItem]
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
