"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import MarketSpecializedBazaarCategoryType


class FactionInventoryItem(TornModel):
    id: int
    name: str
    type: MarketSpecializedBazaarCategoryType
    amount: int
    uids: list[int]
    loaned: FactionInventoryItemLoanedVariant1 | None


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    links: RequestLinks
    total: int | None = None


class FactionInventoryItemLoanedVariant1(TornModel):
    id: int
    name: str


class FactionInventoryResponse(TornModel):
    inventory_timestamp: int
    inventory: list[FactionInventoryItem]
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")
