"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class FactionRaidReportAttacker(TornModel):
    user: FactionRaidReportUser
    attacks: int
    damage: float


class FactionRaidReportFaction(TornModel):
    id: int
    name: str
    score: float
    attackers: list[FactionRaidReportAttacker]
    non_attackers: list[FactionRaidReportUser]


class FactionRaidReportUser(TornModel):
    id: int
    name: str


class FactionRaidReport(TornModel):
    id: int
    start: int
    end: int
    aggressor: FactionRaidReportFaction
    defender: FactionRaidReportFaction
