"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionStatType


class FactionStat(TornModel):
    """
    Pydantic model for the FactionStat Torn API response.

    Attributes:
        name (FactionStatType): Torn API field `name`.
        value (int): Torn API field `value`.
    """

    # <torn-sdk:custom-class FactionStat>
    # </torn-sdk:custom-class FactionStat>
    name: FactionStatType
    value: int


class FactionStatsResponse(TornListModel[FactionStat]):
    """
    Pydantic model for the FactionStatsResponse Torn API response.
    """

    # <torn-sdk:custom-class FactionStatsResponse>
    # </torn-sdk:custom-class FactionStatsResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
