"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    FactionTerritoryType,
    FactionTerritoryWarResultType,
)


class FactionTerritoryWarFinished(TornModel):
    """
    Pydantic model for the FactionTerritoryWarFinished Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        territory (FactionTerritoryType): Torn API field `territory`.
        start (int): Torn API field `start`.
        end (int): Torn API field `end`.
        target (int): Torn API field `target`.
        result (FactionTerritoryWarResultType): Torn API field `result`.
        factions (list[FactionTerritoryWarFinishedFaction]): Torn API field `factions`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarFinished>
    # </torn-sdk:custom-class FactionTerritoryWarFinished>
    id: int
    territory: FactionTerritoryType
    start: int
    end: int
    target: int
    result: FactionTerritoryWarResultType
    factions: list[FactionTerritoryWarFinishedFaction]


class FactionTerritoryWarFinishedFaction(TornModel):
    """
    Pydantic model for the FactionTerritoryWarFinishedFaction Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        is_aggressor (bool): Torn API field `is_aggressor`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarFinishedFaction>
    # </torn-sdk:custom-class FactionTerritoryWarFinishedFaction>
    id: int
    name: str
    score: int
    is_aggressor: bool


class FactionTerritoryWarsHistoryResponse(
    TornListModel[FactionTerritoryWarFinished]
):
    """
    Pydantic model for the FactionTerritoryWarsHistoryResponse Torn API response.
    """

    # <torn-sdk:custom-class FactionTerritoryWarsHistoryResponse>
    # </torn-sdk:custom-class FactionTerritoryWarsHistoryResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
