"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionTerritoryType, TornRacketType


class FactionTerritory(TornModel):
    """
    Pydantic model for the FactionTerritory Torn API response.

    Attributes:
        id (FactionTerritoryType): Torn API field `id`.
        acquired_at (int): Torn API field `acquired_at`.
        sector (int): Torn API field `sector`.
        size (int): Torn API field `size`.
        density (int): Torn API field `density`.
        slots (int): Torn API field `slots`.
        respect (int): Torn API field `respect`.
        coordinates (TornTerritoryCoordinates): Torn API field `coordinates`.
        racket (TornRacket | None): Torn API field `racket`.
    """

    # <torn-sdk:custom-class FactionTerritory>
    # </torn-sdk:custom-class FactionTerritory>
    id: FactionTerritoryType
    acquired_at: int
    sector: int
    size: int
    density: int
    slots: int
    respect: int
    coordinates: TornTerritoryCoordinates
    racket: TornRacket | None


class TornRacket(TornModel):
    """
    Pydantic model for the TornRacket Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        level (int): Torn API field `level`.
        description (str): Torn API field `description`.
        reward (TornRacketReward): Torn API field `reward`.
        created_at (int): Torn API field `created_at`.
        changed_at (int): Torn API field `changed_at`.
    """

    # <torn-sdk:custom-class TornRacket>
    # </torn-sdk:custom-class TornRacket>
    name: str
    level: int
    description: str
    reward: TornRacketReward
    created_at: int
    changed_at: int


class TornRacketReward(TornModel):
    """
    Pydantic model for the TornRacketReward Torn API response.

    Attributes:
        type (TornRacketType): Torn API field `type`.
        quantity (int): Torn API field `quantity`.
        id (int | None): Torn API field `id`.
    """

    # <torn-sdk:custom-class TornRacketReward>
    # </torn-sdk:custom-class TornRacketReward>
    type: TornRacketType
    quantity: int
    id: int | None


class TornTerritoryCoordinates(TornModel):
    """
    Pydantic model for the TornTerritoryCoordinates Torn API response.

    Attributes:
        x (float): Torn API field `x`.
        y (float): Torn API field `y`.
    """

    # <torn-sdk:custom-class TornTerritoryCoordinates>
    # </torn-sdk:custom-class TornTerritoryCoordinates>
    x: float
    y: float


class FactionTerritoriesResponse(TornListModel[FactionTerritory]):
    """
    Pydantic model for the FactionTerritoriesResponse Torn API response.
    """

    # <torn-sdk:custom-class FactionTerritoriesResponse>
    # </torn-sdk:custom-class FactionTerritoriesResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
