"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionTerritoryType


class FactionTerritoryWarReportFaction(TornModel):
    """
    Pydantic model for the FactionTerritoryWarReportFaction Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        joins (int): Torn API field `joins`.
        clears (int): Torn API field `clears`.
        is_aggressor (bool): Torn API field `is_aggressor`.
        members (list[FactionTerritoryWarReportMembers]): Torn API field `members`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarReportFaction>
    # </torn-sdk:custom-class FactionTerritoryWarReportFaction>
    id: int
    name: str
    score: int
    joins: int
    clears: int
    is_aggressor: bool
    members: list[FactionTerritoryWarReportMembers]


class FactionTerritoryWarReportMembers(TornModel):
    """
    Pydantic model for the FactionTerritoryWarReportMembers Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        username (str): Torn API field `username`.
        level (int): Torn API field `level`.
        score (int): Torn API field `score`.
        joins (int): Torn API field `joins`.
        clears (int): Torn API field `clears`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarReportMembers>
    # </torn-sdk:custom-class FactionTerritoryWarReportMembers>
    id: int
    username: str
    level: int
    score: int
    joins: int
    clears: int


class FactionTerritoryWarReport(TornModel):
    """
    Pydantic model for the FactionTerritoryWarReport Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        territory (FactionTerritoryType): Torn API field `territory`.
        started_at (int): Torn API field `started_at`.
        ended_at (int): Torn API field `ended_at`.
        winner (int): Winning faction id.
        result (str): Torn API field `result`.
        factions (list[FactionTerritoryWarReportFaction]): Torn API field `factions`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarReport>
    # </torn-sdk:custom-class FactionTerritoryWarReport>
    id: int
    territory: FactionTerritoryType
    started_at: int
    ended_at: int
    winner: int
    result: str
    factions: list[FactionTerritoryWarReportFaction]


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
