"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionBranchStateType


class FactionBranchDetails(TornModel):
    """
    Pydantic model for the FactionBranchDetails Torn API response.

    Attributes:
        name (str): Torn API field `name`.
        order (int): Torn API field `order`.
        multiplier (int): Respect cost multiplier.
        upgrades (list[FactionUpgradeDetails]): Torn API field `upgrades`.
    """

    # <torn-sdk:custom-class FactionBranchDetails>
    # </torn-sdk:custom-class FactionBranchDetails>
    name: str
    order: int
    multiplier: int
    upgrades: list[FactionUpgradeDetails]


class FactionUpgradeDetails(TornModel):
    """
    Pydantic model for the FactionUpgradeDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        ability (str): Torn API field `ability`.
        level (int): Torn API field `level`.
        cost (int): Torn API field `cost`.
        unlocked_at (int): Torn API field `unlocked_at`.
    """

    # <torn-sdk:custom-class FactionUpgradeDetails>
    # </torn-sdk:custom-class FactionUpgradeDetails>
    id: int
    name: str
    ability: str
    level: int
    cost: int
    unlocked_at: int


class FactionUpgrades(TornModel):
    """
    Pydantic model for the FactionUpgrades Torn API response.

    Attributes:
        core (FactionUpgradesCore): Torn API field `core`.
        peace (list[FactionBranchDetails]): Torn API field `peace`.
        war (list[FactionBranchDetails]): Torn API field `war`.
    """

    # <torn-sdk:custom-class FactionUpgrades>
    # </torn-sdk:custom-class FactionUpgrades>
    core: FactionUpgradesCore
    peace: list[FactionBranchDetails]
    war: list[FactionBranchDetails]


class FactionUpgradesCore(TornModel):
    """
    Pydantic model for the FactionUpgradesCore Torn API response.

    Attributes:
        upgrades (list[FactionUpgradeDetails]): Torn API field `upgrades`.
    """

    # <torn-sdk:custom-class FactionUpgradesCore>
    # </torn-sdk:custom-class FactionUpgradesCore>
    upgrades: list[FactionUpgradeDetails] | None = None


class FactionUpgradesResponse(TornModel):
    """
    Pydantic model for the FactionUpgradesResponse Torn API response.

    Attributes:
        upgrades (FactionUpgrades): Torn API field `upgrades`.
        state (FactionBranchStateType): Torn API field `state`.
    """

    # <torn-sdk:custom-class FactionUpgradesResponse>
    # </torn-sdk:custom-class FactionUpgradesResponse>
    upgrades: FactionUpgrades
    state: FactionBranchStateType


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
