"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionTerritoryType


class FactionTerritoryWarFaction(TornModel):
    id: int
    name: str
    score: int
    chain: int | None = None
    players_on_wall: list[FactionTerritoryWarFactionWallPlayers] | None = None


class FactionTerritoryWarFactionWallPlayers(TornModel):
    id: int
    name: str


class FactionTerritoryWarfare(TornModel):
    id: int
    territory: FactionTerritoryType
    start: int
    end: int
    target: int
    aggressor: FactionTerritoryWarFaction
    defender: FactionTerritoryWarFaction
    result: str


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    links: RequestLinks


class FactionWarfareTerritoryWarsResponse(TornModel):
    warfareterritory: list[FactionTerritoryWarfare]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")
