# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class FactionRankedWarDetails(TornModel):
    id: int
    start: int
    end: int
    target: int
    winner: int | None
    factions: list[FactionRankedWarDetailsFactionsItem]

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class FactionRankedWarDetailsFactionsItem(TornModel):
    id: int
    name: str
    score: int
    chain: int

class FactionWarfareRankedResponse(TornModel):
    warfareranked: list[FactionRankedWarDetails]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
