# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class FactionChain(TornModel):
    id: int
    chain: int
    respect: float
    start: int
    end: int

class FactionChainWarfare(TornModel):
    id: int
    chain: int
    respect: float
    start: int
    end: int
    faction: FactionChainWarfareFaction

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class FactionChainWarfareFaction(TornModel):
    id: int
    name: str

class FactionWarfareChainsResponse(TornModel):
    warfarechains: list[FactionChainWarfare]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
