"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import FactionTerritoryType


class FactionTerritoryWarFaction(TornModel):
    """
    The fields 'chain' and 'players_on_wall' exist only for wars with the result 'in_progress'.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        chain (int): Torn API field `chain`.
        players_on_wall (list[FactionTerritoryWarFactionWallPlayers]): Torn API field `players_on_wall`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarFaction>
    # </torn-sdk:custom-class FactionTerritoryWarFaction>
    id: int
    name: str
    score: int
    chain: int | None = None
    players_on_wall: list[FactionTerritoryWarFactionWallPlayers] | None = None


class FactionTerritoryWarFactionWallPlayers(TornModel):
    """
    Pydantic model for the FactionTerritoryWarFactionWallPlayers Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarFactionWallPlayers>
    # </torn-sdk:custom-class FactionTerritoryWarFactionWallPlayers>
    id: int
    name: str


class FactionTerritoryWarfare(TornModel):
    """
    Pydantic model for the FactionTerritoryWarfare Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        territory (FactionTerritoryType): Torn API field `territory`.
        start (int): Torn API field `start`.
        end (int): Torn API field `end`.
        target (int): Torn API field `target`.
        aggressor (FactionTerritoryWarFaction): Torn API field `aggressor`.
        defender (FactionTerritoryWarFaction): Torn API field `defender`.
        result (str): Torn API field `result`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarfare>
    # </torn-sdk:custom-class FactionTerritoryWarfare>
    id: int
    territory: FactionTerritoryType
    start: int
    end: int
    target: int
    aggressor: FactionTerritoryWarFaction
    defender: FactionTerritoryWarFaction
    result: str


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinks(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinks Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinks>
    # </torn-sdk:custom-class RequestMetadataWithLinks>
    links: RequestLinks


class FactionWarfareTerritoryWarsResponse(TornModel):
    """
    Pydantic model for the FactionWarfareTerritoryWarsResponse Torn API response.

    Attributes:
        warfareterritory (list[FactionTerritoryWarfare]): Torn API field `warfareterritory`.
        metadata (RequestMetadataWithLinks): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class FactionWarfareTerritoryWarsResponse>
    # </torn-sdk:custom-class FactionWarfareTerritoryWarsResponse>
    warfareterritory: list[FactionTerritoryWarfare]
    metadata: RequestMetadataWithLinks = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
