"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel


class FactionPact(TornModel):
    """
    Pydantic model for the FactionPact Torn API response.

    Attributes:
        faction_id (int): Torn API field `faction_id`.
        faction_name (str): Torn API field `faction_name`.
        until (int): The duration until when is the non-aggression pact valid.
    """

    # <torn-sdk:custom-class FactionPact>
    # </torn-sdk:custom-class FactionPact>
    faction_id: int
    faction_name: str
    until: int


class FactionRaidWar(TornModel):
    """
    Pydantic model for the FactionRaidWar Torn API response.

    Attributes:
        war_id (int): Torn API field `war_id`.
        start (int): Torn API field `start`.
        end (int | None): Torn API field `end`.
        factions (list[FactionRaidWarParticipant]): The factions involved in the raid war.
    """

    # <torn-sdk:custom-class FactionRaidWar>
    # </torn-sdk:custom-class FactionRaidWar>
    war_id: int
    start: int
    end: int | None
    factions: list[FactionRaidWarParticipant]


class FactionRaidWarParticipant(TornModel):
    """
    Pydantic model for the FactionRaidWarParticipant Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        chain (int): Faction's current chain.
        is_aggressor (bool): Torn API field `is_aggressor`.
    """

    # <torn-sdk:custom-class FactionRaidWarParticipant>
    # </torn-sdk:custom-class FactionRaidWarParticipant>
    id: int
    name: str
    score: int
    chain: int
    is_aggressor: bool


class FactionRankedWar(TornModel):
    """
    Pydantic model for the FactionRankedWar Torn API response.

    Attributes:
        war_id (int): Torn API field `war_id`.
        start (int): Torn API field `start`.
        end (int | None): Torn API field `end`.
        target (int): The score target of the war.
        winner (int | None): Torn API field `winner`.
        factions (list[FactionRankedWarParticipant]): The factions involved in the ranked war.
    """

    # <torn-sdk:custom-class FactionRankedWar>
    # </torn-sdk:custom-class FactionRankedWar>
    war_id: int
    start: int
    end: int | None
    target: int
    winner: int | None
    factions: list[FactionRankedWarParticipant]


class FactionRankedWarParticipant(TornModel):
    """
    Pydantic model for the FactionRankedWarParticipant Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        chain (int): Faction's current chain.
    """

    # <torn-sdk:custom-class FactionRankedWarParticipant>
    # </torn-sdk:custom-class FactionRankedWarParticipant>
    id: int
    name: str
    score: int
    chain: int


class FactionTerritoryWar(TornModel):
    """
    Pydantic model for the FactionTerritoryWar Torn API response.

    Attributes:
        war_id (int): Torn API field `war_id`.
        territory (str): Torn API field `territory`.
        start (int): Torn API field `start`.
        end (int | None): Torn API field `end`.
        target (int): The score target of the war.
        winner (int | None): Torn API field `winner`.
        factions (list[FactionTerritoryWarParticipant]): The factions involved in the territory war.
    """

    # <torn-sdk:custom-class FactionTerritoryWar>
    # </torn-sdk:custom-class FactionTerritoryWar>
    war_id: int
    territory: str
    start: int
    end: int | None
    target: int
    winner: int | None = None
    factions: list[FactionTerritoryWarParticipant]


class FactionTerritoryWarParticipant(TornModel):
    """
    Pydantic model for the FactionTerritoryWarParticipant Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        score (int): Torn API field `score`.
        chain (int): Faction's current chain.
        is_aggressor (bool): Torn API field `is_aggressor`.
        player_ids (list[int]): Torn API field `playerIds`.
    """

    # <torn-sdk:custom-class FactionTerritoryWarParticipant>
    # </torn-sdk:custom-class FactionTerritoryWarParticipant>
    id: int
    name: str
    score: int
    chain: int
    is_aggressor: bool
    player_ids: list[int] = Field(alias="playerIds")


class FactionWars(TornModel):
    """
    Pydantic model for the FactionWars Torn API response.

    Attributes:
        ranked (FactionRankedWar | None): Torn API field `ranked`.
        raids (list[FactionRaidWar]): Torn API field `raids`.
        territory (list[FactionTerritoryWar]): Torn API field `territory`.
    """

    # <torn-sdk:custom-class FactionWars>
    # </torn-sdk:custom-class FactionWars>
    ranked: FactionRankedWar | None
    raids: list[FactionRaidWar]
    territory: list[FactionTerritoryWar]


class FactionWarsResponse(TornModel):
    """
    Pydantic model for the FactionWarsResponse Torn API response.

    Attributes:
        pacts (list[FactionPact]): Torn API field `pacts`.
        wars (FactionWars): Torn API field `wars`.
    """

    # <torn-sdk:custom-class FactionWarsResponse>
    # </torn-sdk:custom-class FactionWarsResponse>
    pacts: list[FactionPact]
    wars: FactionWars


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
