# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.company import (
    CompaniesResponse,
    CompaniesSearchResponse,
    CompanyApplicationsResponse,
    CompanyEmployeesResponse,
    CompanyLookupResponse,
    CompanyProfileResponse,
    CompanyStockResponse,
    CompanyTimestampResponse,
    NewsResponse,
)
from torn_sdk.models.types import (
    CompanyNewsCategoryType,
    CompanySearchFilterItemVariant1Type,
    SortDescType,
)


class GeneratedCompanyResourceMixin:
    @endpoint(extract='applications')
    def applications(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyApplicationsResponse:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def companies(
        self,
        company_type_id: int,
        *,
        striptags: bool = True,
        limit: int = 20,
        offset: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompaniesResponse:
        raise NotImplementedError

    @endpoint(extract='employees')
    def employees(
        self,
        company_id: int | None = None,
        *,
        striptags: bool = True,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyEmployeesResponse:
        raise NotImplementedError

    @endpoint(extract='selections')
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyLookupResponse:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def news(
        self,
        *,
        news_category: CompanyNewsCategoryType,
        striptags: bool = False,
        limit: int = 100,
        sort: SortDescType = 'DESC',
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> NewsResponse:
        raise NotImplementedError

    @endpoint(extract='profile')
    def profile(
        self,
        company_id: int | None = None,
        *,
        striptags: bool = True,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyProfileResponse:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def search(
        self,
        *,
        company_name: str | None = None,
        filters: list[CompanySearchFilterItemVariant1Type | str] | None = None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompaniesSearchResponse:
        raise NotImplementedError

    @endpoint(extract='stock')
    def stock(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyStockResponse:
        raise NotImplementedError

    @endpoint(extract='timestamp')
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> CompanyTimestampResponse:
        raise NotImplementedError
