"""Typed faction resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.faction import (
    AttacksFullResponse,
    AttacksResponse,
    FactionApplicationsResponse,
    FactionBalance,
    FactionBasic,
    FactionChainReport,
    FactionChainsResponse,
    FactionContributorsResponse,
    FactionCrime,
    FactionCrimeExpResponse,
    FactionCrimesResponse,
    FactionHofStats,
    FactionInventoryResponse,
    FactionLookupResponse,
    FactionMembersResponse,
    FactionOngoingChain,
    FactionPositionsResponse,
    FactionRacketsResponse,
    FactionRaidReport,
    FactionRaidsResponse,
    FactionRankedWarReportResponse,
    FactionRankedWarResponse,
    FactionSearchResponse,
    FactionStatsResponse,
    FactionTerritoriesOwnershipResponse,
    FactionTerritoriesResponse,
    FactionTerritoryWarReport,
    FactionTerritoryWarsHistoryResponse,
    FactionTimestampResponse,
    FactionUpgradesResponse,
    FactionWarfareChainsResponse,
    FactionWarfareDirtyBombsResponse,
    FactionWarfareRaidsResponse,
    FactionWarfareRankedResponse,
    FactionWarfareTerritoryWarsResponse,
    FactionWarsResponse,
    NewsResponse,
    ReportsResponse,
    RevivesFullResponse,
    RevivesResponse,
)
from torn_sdk.models.types import (
    FactionArmoryCategoryType,
    FactionBalanceCatType,
    FactionCrimesCatType,
    FactionCrimesFiltersType,
    FactionNewsCategoryType,
    FactionSearchFilterItemVariant1Type,
    FactionStatType,
    FactionWarfarechainsCatType,
    ReportType,
    SortDescType,
    SortType,
    UserAttacksRequestFilterType,
)


class GeneratedFactionResourceMixin:
    """
    Typed faction endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @endpoint(extract="applications")
    def applications(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionApplicationsResponse:
        """
                Get your faction's applications

        Requires minimal access key with faction API access permissions. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionApplicationsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method applications>
        # </torn-sdk:custom-method applications>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def attacks(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AttacksResponse:
        """
                Get your faction's detailed attacks

        Requires limited access key with faction API access permissions. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    AttacksResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method attacks>
        # </torn-sdk:custom-method attacks>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def attacksfull(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        limit: int = 1000,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AttacksFullResponse:
        """
                Get your faction's simplified attacks

        Requires limited access key with faction API access permissions. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    AttacksFullResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method attacksfull>
        # </torn-sdk:custom-method attacksfull>
        raise NotImplementedError

    @endpoint(extract="balance")
    def balance(
        self,
        *,
        balance_category: FactionBalanceCatType | None = "current",
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionBalance:
        """
                Get your faction's & member's balance details

        Requires limited access key with faction API access permissions. <br>

                Args:
                    balance_category (FactionBalanceCatType | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionBalance: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method balance>
        # </torn-sdk:custom-method balance>
        raise NotImplementedError

    @endpoint(extract="basic")
    def basic(
        self,
        faction_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionBasic:
        """
                Get a faction's basic details Get your faction's basic details

        Requires public access key. <br> The 'is_enlisted' value will be populated if you have API faction permissions (with custom, limited or full access keys), otherwise it will be set as null.

        Requires public access key. <br> The 'is_enlisted' value will be populated if you're requesting data for your faction and have faction permissions (with custom, limited or full access keys), otherwise it will be set as null.

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionBasic: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method basic>
        # </torn-sdk:custom-method basic>
        raise NotImplementedError

    @endpoint(extract="chain")
    def chain(
        self,
        faction_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionOngoingChain:
        """
                Get a faction's current chain Get your faction's current chain

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionOngoingChain: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method chain>
        # </torn-sdk:custom-method chain>
        raise NotImplementedError

    @endpoint(extract="chainreport")
    def chainreport(
        self,
        chain_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionChainReport:
        """
                Get a chain report Get your faction's latest chain report

        Requires public access key. <br> Chain reports for ongoing chains are available only for your own faction.

        Requires public access key. <br> This includes currently ongoing chains.

                Args:
                    chain_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionChainReport: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method chainreport>
        # </torn-sdk:custom-method chainreport>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def chains(
        self,
        faction_id: int | None = None,
        *,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionChainsResponse:
        """
                Get a list of a faction's completed chains Get a list of your faction's completed chains

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionChainsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method chains>
        # </torn-sdk:custom-method chains>
        raise NotImplementedError

    @endpoint(extract="contributors")
    def contributors(
        self,
        *,
        stat_key: FactionStatType,
        contributors_category: FactionBalanceCatType | None = "current",
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionContributorsResponse:
        """
                Get your faction's challenge contributors

        Requires limiteed access key with faction API access permissions. <br>

                Args:
                    stat_key (FactionStatType): Query parameter for this endpoint.
                    contributors_category (FactionBalanceCatType | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionContributorsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method contributors>
        # </torn-sdk:custom-method contributors>
        raise NotImplementedError

    @endpoint(extract="crime")
    def crime(
        self,
        crime_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionCrime:
        """
                Get a specific organized crime

        Requires minimal access key with faction API access permissions. <br>

                Args:
                    crime_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionCrime: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method crime>
        # </torn-sdk:custom-method crime>
        raise NotImplementedError

    @endpoint(extract="crimeexp")
    def crimeexp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionCrimeExpResponse:
        """
                Get your faction members crime experience

        Requires minimal access key. <br>Members are ordered descending, from highest crime experience to lowest.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionCrimeExpResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method crimeexp>
        # </torn-sdk:custom-method crimeexp>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def crimes(
        self,
        *,
        crimes_category: FactionCrimesCatType | None = "all",
        crimes_filter: FactionCrimesFiltersType | None = None,
        limit: int = 20,
        offset: int = 0,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionCrimesResponse:
        """
                Get your faction's organized crimes

        Requires minimal access key with faction API access permissions. <br> It's possible to get older entries either by timestamp range (from, to) or with offset.<br> Crimes are ordered depending on the category chosen:
         * For categories 'all' & 'available', the ordering field is 'created_at'.
         * For categories 'successful', 'failed' & 'completed', the ordering field is 'executed_at'.
         * For categories 'recruiting' & 'expired', the ordering field is 'expired_at'.
         * For category 'planning', the ordering field is 'ready_at'.

                Args:
                    crimes_category (FactionCrimesCatType | None): Query parameter for this endpoint.
                    crimes_filter (FactionCrimesFiltersType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionCrimesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method crimes>
        # </torn-sdk:custom-method crimes>
        raise NotImplementedError

    @endpoint(extract="dirtybombs")
    def dirtybombs(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarfareDirtyBombsResponse:
        """
                Get all dirty bombs

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarfareDirtyBombsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method dirtybombs>
        # </torn-sdk:custom-method dirtybombs>
        raise NotImplementedError

    @endpoint(extract="hof")
    def hof(
        self,
        faction_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionHofStats:
        """
                Get a faction's hall of fame rankings. Get your faction's hall of fame rankings.

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionHofStats: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method hof>
        # </torn-sdk:custom-method hof>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def inventory(
        self,
        *,
        armory_category: FactionArmoryCategoryType,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionInventoryResponse:
        """
                Get your faction's inventory items.

        <b>Cached selection (1 hour, all items cached at once).</b><br><br>Requires limited access key. <br>

                Args:
                    armory_category (FactionArmoryCategoryType): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionInventoryResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method inventory>
        # </torn-sdk:custom-method inventory>
        raise NotImplementedError

    @endpoint(extract="selections")
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionLookupResponse:
        """
        Requires public access key. <br>

        Args:
            timestamp (int | str | None): Query parameter for this endpoint.
            comment (str | None): Query parameter for this endpoint.

        Returns:
            FactionLookupResponse: Parsed API response.

        Raises:
            TornAPIWrapper.errors.APIError: If Torn rejects the request.
            pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method lookup>
        # </torn-sdk:custom-method lookup>
        raise NotImplementedError

    @endpoint(extract="members")
    def members(
        self,
        faction_id: int | None = None,
        *,
        striptags: bool = True,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionMembersResponse:
        """
                Get a list of a faction's members Get a list of your faction's members

        Requires public access key. <br> The 'revive_setting' value will be populated (not Unknown) if you have faction permissions (with custom, limited or full access keys), otherwise it will be set as 'Unknown'.

        Requires public access key. <br> The 'revive_setting' value will be populated (not Unknown) if you're requesting data for your own faction and have faction permissions (with custom, limited or full access keys), otherwise it will be set as 'Unknown'.

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionMembersResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method members>
        # </torn-sdk:custom-method members>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def news(
        self,
        *,
        news_category: FactionNewsCategoryType,
        striptags: bool = False,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> NewsResponse:
        """
                Get your faction's news details

        Requires minimal access key with faction API access permissions. <br> It is possible to pass up to 10 categories at the time (comma separated). Categories 'attack', 'depositFunds' and 'giveFunds' are only available with 'Custom', 'Limited' or 'Full' access keys.

                Args:
                    news_category (FactionNewsCategoryType): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    NewsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method news>
        # </torn-sdk:custom-method news>
        raise NotImplementedError

    @endpoint(extract="positions")
    def positions(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionPositionsResponse:
        """
                Get your faction's positions details

        Requires minimal access key with faction API access permissions. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionPositionsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method positions>
        # </torn-sdk:custom-method positions>
        raise NotImplementedError

    @endpoint(extract="rackets")
    def rackets(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionRacketsResponse:
        """
                Get a list of current rackets

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionRacketsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method rackets>
        # </torn-sdk:custom-method rackets>
        raise NotImplementedError

    @endpoint(extract="raidreport")
    def raidreport(
        self,
        raid_war_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionRaidReport:
        """
                Get raid war details

        Requires public access key. <br>

                Args:
                    raid_war_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionRaidReport: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method raidreport>
        # </torn-sdk:custom-method raidreport>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def raids(
        self,
        faction_id: int | None = None,
        *,
        limit: int = 20,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionRaidsResponse:
        """
                Get a faction's raids history Get raids history for your faction

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionRaidsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method raids>
        # </torn-sdk:custom-method raids>
        raise NotImplementedError

    @endpoint(extract="rankedwarreport")
    def rankedwarreport(
        self,
        ranked_war_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionRankedWarReportResponse:
        """
                Get ranked war details

        Requires public access key. <br>

                Args:
                    ranked_war_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionRankedWarReportResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method rankedwarreport>
        # </torn-sdk:custom-method rankedwarreport>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def rankedwars(
        self,
        faction_id: int | None = None,
        *,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionRankedWarResponse:
        """
                Get a faction's ranked wars history Get ranked wars history for your faction

        Requires public access key. <br> Use offset to get older results which are always ordered descending.

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionRankedWarResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method rankedwars>
        # </torn-sdk:custom-method rankedwars>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def reports(
        self,
        *,
        report_category: ReportType | None = None,
        target_id: int | None = None,
        limit: int = 20,
        offset: int = 0,
        sort: SortDescType = "DESC",
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ReportsResponse:
        """
                Get faction reports

        Requires limited access key. <br>
        The limit is set to 25 when requesting any category other than 'stats'.<br>
        When requesting the 'stats' category, limit can be increased up to 100.

                Args:
                    report_category (ReportType | None): Query parameter for this endpoint.
                    target_id (int | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ReportsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method reports>
        # </torn-sdk:custom-method reports>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def revives(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        striptags: bool = True,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RevivesResponse:
        """
                Get your faction's detailed revives

        Requires limited access key with faction API access permissions. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RevivesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method revives>
        # </torn-sdk:custom-method revives>
        raise NotImplementedError

    @endpoint(method="get_revivesfull", extract_default=False)
    def revives_full(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        striptags: bool = True,
        limit: int = 1000,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RevivesFullResponse:
        """
                Get your faction's simplified revives

        Requires limited access key with faction API access permissions. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RevivesFullResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method revives_full>
        # </torn-sdk:custom-method revives_full>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def search(
        self,
        *,
        faction_name: str | None = None,
        filters: list[FactionSearchFilterItemVariant1Type | str] | None = None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionSearchResponse:
        """
                Search factions by name or other criteria

        Requires public access key. <br>This selection is standalone and cannot be used together with other selections.

                Args:
                    faction_name (str | None): Query parameter for this endpoint.
                    filters (list[FactionSearchFilterItemVariant1Type | str] | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionSearchResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method search>
        # </torn-sdk:custom-method search>
        raise NotImplementedError

    @endpoint(extract="stats")
    def stats(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionStatsResponse:
        """
                Get your faction's challenges stats

        Requires minimal access key with faction API access permissions. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionStatsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method stats>
        # </torn-sdk:custom-method stats>
        raise NotImplementedError

    @endpoint(extract="territory")
    def territory(
        self,
        faction_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionTerritoriesResponse:
        """
                Get a list of a faction's territories Get a list of your faction's territories

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionTerritoriesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method territory>
        # </torn-sdk:custom-method territory>
        raise NotImplementedError

    @endpoint(extract="territoryOwnership")
    def territoryownership(
        self,
        *,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionTerritoriesOwnershipResponse:
        """
                Get a list territory ownership

        Requires public access key. <br>

                Args:
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionTerritoriesOwnershipResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method territoryownership>
        # </torn-sdk:custom-method territoryownership>
        raise NotImplementedError

    @endpoint(extract="territorywarreport")
    def territorywarreport(
        self,
        territory_war_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionTerritoryWarReport:
        """
                Get territory war details

        Requires public access key. <br>

                Args:
                    territory_war_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionTerritoryWarReport: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method territorywarreport>
        # </torn-sdk:custom-method territorywarreport>
        raise NotImplementedError

    @endpoint(extract="territorywars")
    def territorywars(
        self,
        faction_id: int | None = None,
        *,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionTerritoryWarsHistoryResponse:
        """
                Get a faction's territory wars history Get territory wars history for your faction

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionTerritoryWarsHistoryResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method territorywars>
        # </torn-sdk:custom-method territorywars>
        raise NotImplementedError

    @endpoint(extract="timestamp")
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionTimestampResponse:
        """
                Get current server time

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionTimestampResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method timestamp>
        # </torn-sdk:custom-method timestamp>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def upgrades(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionUpgradesResponse:
        """
                Get your faction's upgrades

        Requires minimal access key with faction API access permissions. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionUpgradesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method upgrades>
        # </torn-sdk:custom-method upgrades>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def warfarechains(
        self,
        *,
        warfare_chains_category: FactionWarfarechainsCatType = "active",
        limit: int = 100,
        sort: SortType | None = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarfareChainsResponse:
        """
                Get all chains

        Requires public access key. <br>By default, active chains are returned.

                Args:
                    warfare_chains_category (FactionWarfarechainsCatType): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarfareChainsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method warfarechains>
        # </torn-sdk:custom-method warfarechains>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def warfareraids(
        self,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarfareRaidsResponse:
        """
                Get all raids

        Requires public access key. <br>

                Args:
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarfareRaidsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method warfareraids>
        # </torn-sdk:custom-method warfareraids>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def warfareranked(
        self,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarfareRankedResponse:
        """
                Get all ranked wars

        Requires public access key. <br>

                Args:
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarfareRankedResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method warfareranked>
        # </torn-sdk:custom-method warfareranked>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def warfareterritory(
        self,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarfareTerritoryWarsResponse:
        """
                Get all territory wars

        Requires public access key. <br>

                Args:
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarfareTerritoryWarsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method warfareterritory>
        # </torn-sdk:custom-method warfareterritory>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def wars(
        self,
        faction_id: int | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> FactionWarsResponse:
        """
                Get a faction's wars & pacts details Get your faction's wars & pacts details

        Requires public access key. <br>

                Args:
                    faction_id (int | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    FactionWarsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method wars>
        # </torn-sdk:custom-method wars>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedFactionResourceMixin>
    # </torn-sdk:custom-class GeneratedFactionResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
