"""Typed forum resource mixins generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.forum import (
    ForumCategoriesResponse,
    ForumLookupResponse,
    ForumPostsResponse,
    ForumThreadExtended,
    ForumThreadsResponse,
    ForumTimestampResponse,
)
from torn_sdk.models.types import SortType


class GeneratedForumResourceMixin:
    """Typed forum endpoints generated from Torn OpenAPI."""

    @endpoint(extract="categories")
    def categories(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumCategoriesResponse:
        """
        Get publicly available forum categories

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="selections")
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumLookupResponse:
        """
        Get all available forum selections

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def posts(
        self,
        thread_id: int,
        *,
        striptags: bool = True,
        offset: int | None = None,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumPostsResponse:
        """
        Get specific forum thread posts

        Requires public access key. <br>Returns 20 posts per page for a specific thread. <br> By default, it uses 'offset', but it's possible to filter posts with 'from' & 'to' parameters.
        """
        raise NotImplementedError

    @endpoint(extract="thread")
    def thread(
        self,
        thread_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadExtended:
        """
        Get specific thread details

        Requires public access key. <br>Contains details of a thread including topic content and poll (if any).
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def threads(
        self,
        category_ids: list[int] | None = None,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadsResponse:
        """
        Get threads across all forum categories Get threads for specific public forum category or categories

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="timestamp")
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumTimestampResponse:
        """
        Get current server time

        Requires public access key. <br>
        """
        raise NotImplementedError
