"""Typed forum resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import async_endpoint
from torn_sdk.models.forum import (
    ForumCategoriesResponse,
    ForumLookupResponse,
    ForumPostsResponse,
    ForumThreadExtended,
    ForumThreadsResponse,
    ForumTimestampResponse,
)
from torn_sdk.models.types import SortType


class GeneratedAsyncForumResourceMixin:
    """
    Typed forum endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @async_endpoint(extract="categories")
    async def categories(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumCategoriesResponse:
        """
                Get publicly available forum categories

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumCategoriesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method categories>
        # </torn-sdk:custom-method categories>
        raise NotImplementedError

    @async_endpoint(extract="selections")
    async def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumLookupResponse:
        """
                Get all available forum selections

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumLookupResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method lookup>
        # </torn-sdk:custom-method lookup>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def posts(
        self,
        thread_id: int,
        *,
        striptags: bool = True,
        offset: int | None = None,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumPostsResponse:
        """
                Get specific forum thread posts

        Requires public access key. <br>Returns 20 posts per page for a specific thread. <br> By default, it uses 'offset', but it's possible to filter posts with 'from' & 'to' parameters.

                Args:
                    thread_id (int): Path parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    offset (int | None): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumPostsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method posts>
        # </torn-sdk:custom-method posts>
        raise NotImplementedError

    @async_endpoint(extract="thread")
    async def thread(
        self,
        thread_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadExtended:
        """
                Get specific thread details

        Requires public access key. <br>Contains details of a thread including topic content and poll (if any).

                Args:
                    thread_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumThreadExtended: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method thread>
        # </torn-sdk:custom-method thread>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def threads(
        self,
        category_ids: list[int] | None = None,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadsResponse:
        """
                Get threads across all forum categories Get threads for specific public forum category or categories

        Requires public access key. <br>

                Args:
                    category_ids (list[int] | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumThreadsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method threads>
        # </torn-sdk:custom-method threads>
        raise NotImplementedError

    @async_endpoint(extract="timestamp")
    async def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumTimestampResponse:
        """
                Get current server time

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ForumTimestampResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method timestamp>
        # </torn-sdk:custom-method timestamp>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedAsyncForumResourceMixin>
    # </torn-sdk:custom-class GeneratedAsyncForumResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
