# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.forum import (
    ForumCategoriesResponse,
    ForumLookupResponse,
    ForumPostsResponse,
    ForumThreadExtended,
    ForumThreadsResponse,
    ForumTimestampResponse,
)
from torn_sdk.models.types import (
    SortType,
)


class GeneratedForumResourceMixin:
    @endpoint(extract='categories')
    def categories(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumCategoriesResponse:
        raise NotImplementedError

    @endpoint(extract='selections')
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumLookupResponse:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def posts(
        self,
        thread_id: int,
        *,
        striptags: bool = True,
        offset: int | None = None,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumPostsResponse:
        raise NotImplementedError

    @endpoint(extract='thread')
    def thread(
        self,
        thread_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadExtended:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def threads(
        self,
        category_ids: list[int] | None = None,
        *,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumThreadsResponse:
        raise NotImplementedError

    @endpoint(extract='timestamp')
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ForumTimestampResponse:
        raise NotImplementedError
