"""Typed key resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.key import KeyInfoResponse, KeyLogResponse


class GeneratedKeyResourceMixin:
    """
    Typed key endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @endpoint(extract="info")
    def info(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> KeyInfoResponse:
        """
                Get current key info

        Available for any key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    KeyInfoResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method info>
        # </torn-sdk:custom-method info>
        raise NotImplementedError

    @endpoint(extract="log")
    def log(
        self,
        *,
        limit: int = 100,
        offset: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> KeyLogResponse:
        """
                Get current key log history

        Available for any key. <br>
         * This selection contains up to last 250 request logs.

                Args:
                    limit (int): Query parameter for this endpoint.
                    offset (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    KeyLogResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method log>
        # </torn-sdk:custom-method log>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedKeyResourceMixin>
    # </torn-sdk:custom-class GeneratedKeyResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
