"""Typed market resource mixins generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.market import (
    AuctionHouseListing,
    AuctionHouseResponse,
    MarketBazaarResponse,
    MarketItemMarketResponse,
    MarketLookupResponse,
    MarketPointsmarketResponse,
    MarketPropertiesResponse,
    MarketRentalsResponse,
    MarketTimestampResponse,
)
from torn_sdk.models.types import (
    MarketSpecializedBazaarCategoryType,
    SortType,
    WeaponBonusType,
)


class GeneratedMarketResourceMixin:
    """Typed market endpoints generated from Torn OpenAPI."""

    @endpoint(extract_default=False)
    def auctionhouse(
        self,
        item_id: int | None = None,
        *,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AuctionHouseResponse:
        """
        Get auction house listings Get specific item auction house listings

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="auctionhouselisting")
    def auctionhouselisting(
        self,
        listing_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AuctionHouseListing:
        """
        Get specific item auction house listings

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="bazaar")
    def bazaar(
        self,
        item_id: int | None = None,
        *,
        bazaar_category: MarketSpecializedBazaarCategoryType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketBazaarResponse:
        """
        Get bazaar directory Get item specialized bazaar directory

        Requires public access key. <br>

        Requires public access key. <br> The default response is of type 'BazaarWeekly', but if a category is chosen, the response will be of type 'BazaarSpecialized'.
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def itemmarket(
        self,
        item_id: int,
        *,
        bonus: WeaponBonusType | None = None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketItemMarketResponse:
        """
        Get item market listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="selections")
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketLookupResponse:
        """
        Get all available market selections

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="pointsmarket")
    def pointsmarket(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketPointsmarketResponse:
        """
        Get points market listings

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def properties(
        self,
        property_type_id: int,
        *,
        limit: int = 20,
        offset: int = 0,
        sort: SortType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketPropertiesResponse:
        """
        Get properties market listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def rentals(
        self,
        property_type_id: int,
        *,
        limit: int = 20,
        offset: int = 0,
        sort: SortType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketRentalsResponse:
        """
        Get properties rental listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="timestamp")
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketTimestampResponse:
        """
        Get current server time

        Requires public access key. <br>
        """
        raise NotImplementedError
