"""Typed market resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import async_endpoint
from torn_sdk.models.market import (
    AuctionHouseListing,
    AuctionHouseResponse,
    MarketBazaarResponse,
    MarketItemMarketResponse,
    MarketLookupResponse,
    MarketPointsmarketResponse,
    MarketPropertiesResponse,
    MarketRentalsResponse,
    MarketTimestampResponse,
)
from torn_sdk.models.types import (
    MarketSpecializedBazaarCategoryType,
    SortType,
    WeaponBonusType,
)


class GeneratedAsyncMarketResourceMixin:
    """
    Typed market endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @async_endpoint(extract_default=False)
    async def auctionhouse(
        self,
        item_id: int | None = None,
        *,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AuctionHouseResponse:
        """
                Get auction house listings Get specific item auction house listings

        Requires public access key. <br>

                Args:
                    item_id (int | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    AuctionHouseResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method auctionhouse>
        # </torn-sdk:custom-method auctionhouse>
        raise NotImplementedError

    @async_endpoint(extract="auctionhouselisting")
    async def auctionhouselisting(
        self,
        listing_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> AuctionHouseListing:
        """
                Get specific item auction house listings

        Requires public access key. <br>

                Args:
                    listing_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    AuctionHouseListing: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method auctionhouselisting>
        # </torn-sdk:custom-method auctionhouselisting>
        raise NotImplementedError

    @async_endpoint(extract="bazaar")
    async def bazaar(
        self,
        item_id: int | None = None,
        *,
        bazaar_category: MarketSpecializedBazaarCategoryType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketBazaarResponse:
        """
                Get bazaar directory Get item specialized bazaar directory

        Requires public access key. <br>

        Requires public access key. <br> The default response is of type 'BazaarWeekly', but if a category is chosen, the response will be of type 'BazaarSpecialized'.

                Args:
                    item_id (int | None): Path parameter for this endpoint.
                    bazaar_category (MarketSpecializedBazaarCategoryType | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketBazaarResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method bazaar>
        # </torn-sdk:custom-method bazaar>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def itemmarket(
        self,
        item_id: int,
        *,
        bonus: WeaponBonusType | None = None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketItemMarketResponse:
        """
                Get item market listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>

                Args:
                    item_id (int): Path parameter for this endpoint.
                    bonus (WeaponBonusType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketItemMarketResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method itemmarket>
        # </torn-sdk:custom-method itemmarket>
        raise NotImplementedError

    @async_endpoint(extract="selections")
    async def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketLookupResponse:
        """
                Get all available market selections

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketLookupResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method lookup>
        # </torn-sdk:custom-method lookup>
        raise NotImplementedError

    @async_endpoint(extract="pointsmarket")
    async def pointsmarket(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketPointsmarketResponse:
        """
                Get points market listings

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketPointsmarketResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method pointsmarket>
        # </torn-sdk:custom-method pointsmarket>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def properties(
        self,
        property_type_id: int,
        *,
        limit: int = 20,
        offset: int = 0,
        sort: SortType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketPropertiesResponse:
        """
                Get properties market listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>

                Args:
                    property_type_id (int): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketPropertiesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method properties>
        # </torn-sdk:custom-method properties>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def rentals(
        self,
        property_type_id: int,
        *,
        limit: int = 20,
        offset: int = 0,
        sort: SortType | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketRentalsResponse:
        """
                Get properties rental listings

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>

                Args:
                    property_type_id (int): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketRentalsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method rentals>
        # </torn-sdk:custom-method rentals>
        raise NotImplementedError

    @async_endpoint(extract="timestamp")
    async def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> MarketTimestampResponse:
        """
                Get current server time

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    MarketTimestampResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method timestamp>
        # </torn-sdk:custom-method timestamp>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedAsyncMarketResourceMixin>
    # </torn-sdk:custom-class GeneratedAsyncMarketResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
