# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.racing import (
    RacingCarUpgradesResponse,
    RacingCarsResponse,
    RacingLookupResponse,
    RacingRaceDetails,
    RacingRacesResponse,
    RacingTimestampResponse,
    RacingTrackRecordsResponse,
    RacingTracksResponse,
)
from torn_sdk.models.types import (
    RaceClassType,
    RacingRaceType,
    SortDescType,
)


class GeneratedRacingResourceMixin:
    @endpoint(extract='cars')
    def cars(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarsResponse:
        raise NotImplementedError

    @endpoint(extract='carupgrades')
    def carupgrades(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarUpgradesResponse:
        raise NotImplementedError

    @endpoint(extract='selections')
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingLookupResponse:
        raise NotImplementedError

    @endpoint(extract='race')
    def race(
        self,
        race_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRaceDetails:
        raise NotImplementedError

    @endpoint(extract_default=False)
    def races(
        self,
        *,
        race_category: RacingRaceType | None = None,
        limit: int = 100,
        sort: SortDescType = 'DESC',
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRacesResponse:
        raise NotImplementedError

    @endpoint(extract='records')
    def records(
        self,
        track_id: int,
        *,
        car_category: RaceClassType,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTrackRecordsResponse:
        raise NotImplementedError

    @endpoint(extract='timestamp')
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTimestampResponse:
        raise NotImplementedError

    @endpoint(extract='tracks')
    def tracks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTracksResponse:
        raise NotImplementedError
