"""Typed racing resource mixins generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.racing import (
    RacingCarsResponse,
    RacingCarUpgradesResponse,
    RacingLookupResponse,
    RacingRaceDetails,
    RacingRacesResponse,
    RacingTimestampResponse,
    RacingTrackRecordsResponse,
    RacingTracksResponse,
)
from torn_sdk.models.types import RaceClassType, RacingRaceType, SortDescType


class GeneratedRacingResourceMixin:
    """Typed racing endpoints generated from Torn OpenAPI."""

    @endpoint(extract="cars")
    def cars(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarsResponse:
        """
        Get cars and their racing stats

        Requires public access key. <br>Returns the stat details about racing cars.
        """
        raise NotImplementedError

    @endpoint(extract="carupgrades")
    def carupgrades(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarUpgradesResponse:
        """
        Get all possible car upgrades

        Requires public access key. <br>Returns the details about all possible car upgrades.
        """
        raise NotImplementedError

    @endpoint(extract="selections")
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingLookupResponse:
        """
        Get all available racing selections

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="race")
    def race(
        self,
        race_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRaceDetails:
        """
        Get specific race details

        Requires public access key. <br>Returns the details of a race.
        """
        raise NotImplementedError

    @endpoint(extract_default=False)
    def races(
        self,
        *,
        race_category: RacingRaceType | None = None,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRacesResponse:
        """
        Get races

        Requires public access key. <br>Returns a list of races, ordered by race start timestamp.
        """
        raise NotImplementedError

    @endpoint(extract="records")
    def records(
        self,
        track_id: int,
        *,
        car_category: RaceClassType,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTrackRecordsResponse:
        """
        Get track records

        Requires public access key. <br>Returns a list of 5 best lap records for the chosen track and car class.
        """
        raise NotImplementedError

    @endpoint(extract="timestamp")
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTimestampResponse:
        """
        Get current server time

        Requires public access key. <br>
        """
        raise NotImplementedError

    @endpoint(extract="tracks")
    def tracks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTracksResponse:
        """
        Get race tracks and descriptions

        Requires public access key. <br>Returns the details about racing tracks.
        """
        raise NotImplementedError
