"""Typed racing resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import endpoint
from torn_sdk.models.racing import (
    RacingCarsResponse,
    RacingCarUpgradesResponse,
    RacingLookupResponse,
    RacingRaceDetails,
    RacingRacesResponse,
    RacingTimestampResponse,
    RacingTrackRecordsResponse,
    RacingTracksResponse,
)
from torn_sdk.models.types import RaceClassType, RacingRaceType, SortDescType


class GeneratedRacingResourceMixin:
    """
    Typed racing endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @endpoint(extract="cars")
    def cars(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarsResponse:
        """
                Get cars and their racing stats

        Requires public access key. <br>Returns the stat details about racing cars.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingCarsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method cars>
        # </torn-sdk:custom-method cars>
        raise NotImplementedError

    @endpoint(extract="carupgrades")
    def carupgrades(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingCarUpgradesResponse:
        """
                Get all possible car upgrades

        Requires public access key. <br>Returns the details about all possible car upgrades.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingCarUpgradesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method carupgrades>
        # </torn-sdk:custom-method carupgrades>
        raise NotImplementedError

    @endpoint(extract="selections")
    def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingLookupResponse:
        """
                Get all available racing selections

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingLookupResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method lookup>
        # </torn-sdk:custom-method lookup>
        raise NotImplementedError

    @endpoint(extract="race")
    def race(
        self,
        race_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRaceDetails:
        """
                Get specific race details

        Requires public access key. <br>Returns the details of a race.

                Args:
                    race_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingRaceDetails: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method race>
        # </torn-sdk:custom-method race>
        raise NotImplementedError

    @endpoint(extract_default=False)
    def races(
        self,
        *,
        race_category: RacingRaceType | None = None,
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingRacesResponse:
        """
                Get races

        Requires public access key. <br>Returns a list of races, ordered by race start timestamp.

                Args:
                    race_category (RacingRaceType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingRacesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method races>
        # </torn-sdk:custom-method races>
        raise NotImplementedError

    @endpoint(extract="records")
    def records(
        self,
        track_id: int,
        *,
        car_category: RaceClassType,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTrackRecordsResponse:
        """
                Get track records

        Requires public access key. <br>Returns a list of 5 best lap records for the chosen track and car class.

                Args:
                    track_id (int): Path parameter for this endpoint.
                    car_category (RaceClassType): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingTrackRecordsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method records>
        # </torn-sdk:custom-method records>
        raise NotImplementedError

    @endpoint(extract="timestamp")
    def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTimestampResponse:
        """
                Get current server time

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingTimestampResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method timestamp>
        # </torn-sdk:custom-method timestamp>
        raise NotImplementedError

    @endpoint(extract="tracks")
    def tracks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RacingTracksResponse:
        """
                Get race tracks and descriptions

        Requires public access key. <br>Returns the details about racing tracks.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RacingTracksResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method tracks>
        # </torn-sdk:custom-method tracks>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedRacingResourceMixin>
    # </torn-sdk:custom-class GeneratedRacingResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
