"""Typed user resource mixins generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.core.decorators import async_endpoint
from torn_sdk.models.types import (
    FiltersUserPropertiesType,
    PersonalStatsCategoryType,
    PersonalStatsStatNameType,
    RacingRaceType,
    ReportType,
    SortDescType,
    SortType,
    TornInventoryItemType,
    TradeCategoryType,
    UserAttacksRequestFilterType,
    UserListType,
    UserSearchFilterItemVariant1Type,
)
from torn_sdk.models.user import (
    ReportsResponse,
    RevivesFullResponse,
    RevivesResponse,
    UserAmmoResponse,
    UserAttacksFullResponse,
    UserAttacksResponse,
    UserBars,
    UserBasic,
    UserBattlestats,
    UserBounties,
    UserCalendar,
    UserCasino,
    UserCompetition,
    UserCoolDowns,
    UserCrime,
    UserDiscord,
    UserEducation,
    UserEnlistedCars,
    UserEquipmentResponse,
    UserEventsResponse,
    UserFactionResponse,
    UserForumFeedResponse,
    UserForumFriendsResponse,
    UserForumPostsResponse,
    UserForumSubscribedThreadsResponse,
    UserForumThreadsResponse,
    UserGymResponse,
    UserHofStats,
    UserHonorsResponse,
    UserIconsResponse,
    UserInventoryResponse,
    UserItemMarketResponse,
    UserItemModsResponse,
    UserJobPointsResponse,
    UserJobRanks,
    UserJobResponse,
    UserListResponse,
    UserLogsResponse,
    UserLookupResponse,
    UserMedalsResponse,
    UserMerits,
    UserMessagesResponse,
    UserMissionsResponse,
    UserMoneyResponse,
    UserNetworthResponse,
    UserNewEventsResponse,
    UserNewMessagesResponse,
    UserNotificationsResponse,
    UserOrganizedCrimeResponse,
    UserOrganizedCrimesResponse,
    UserPerksResponse,
    UserPersonalStatsResponse,
    UserProfileResponse,
    UserPropertiesResponse,
    UserPropertyDetails,
    UserRacesResponse,
    UserRacingRecordsResponse,
    UserRefillsResponse,
    UserSearchResponse,
    UserSkillsResponse,
    UserStocksResponse,
    UserTimestampResponse,
    UserTradeDetailed,
    UserTradesResponse,
    UserTravelResponse,
    UserVirusResponse,
    UserWeaponExpResponse,
    UserWorkStatsResponse,
)


class GeneratedAsyncUserResourceMixin:
    """
    Typed user endpoints generated from Torn OpenAPI.

    Attributes:
        endpoint (object): Underlying TornAPIWrapper endpoint.

    Args:
        endpoint (object): Endpoint supplied by the public resource class.
    """

    @async_endpoint(extract="ammo")
    async def ammo(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserAmmoResponse:
        """
                Get your ammo information

        Requires minimal key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserAmmoResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method ammo>
        # </torn-sdk:custom-method ammo>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def attacks(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        limit: int = 100,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserAttacksResponse:
        """
                Get your detailed attacks

        Requires limited access key. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserAttacksResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method attacks>
        # </torn-sdk:custom-method attacks>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def attacksfull(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        limit: int = 1000,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserAttacksFullResponse:
        """
                Get your simplified attacks

        Requires limited access key. <br>Returns up to 1,000 rows. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserAttacksFullResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method attacksfull>
        # </torn-sdk:custom-method attacksfull>
        raise NotImplementedError

    @async_endpoint(extract="bars")
    async def bars(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserBars:
        """
                Get your bars information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserBars: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method bars>
        # </torn-sdk:custom-method bars>
        raise NotImplementedError

    @async_endpoint(extract="profile")
    async def basic(
        self,
        user_id: int | str | None = None,
        *,
        striptags: bool = True,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserBasic:
        """
                Get basic profile information for a specific user Get your basic profile information

        Requires public access key. <br>

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserBasic: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method basic>
        # </torn-sdk:custom-method basic>
        raise NotImplementedError

    @async_endpoint(extract="battlestats")
    async def battlestats(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserBattlestats:
        """
                Get your battlestats

        Requires limited access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserBattlestats: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method battlestats>
        # </torn-sdk:custom-method battlestats>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def bounties(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserBounties:
        """
                Get bounties placed on a specific user Get bounties placed on you

        <b>Globally cached selection.</b><br><br>Requires public access key. <br>

        Requires public access key. <br>

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserBounties: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method bounties>
        # </torn-sdk:custom-method bounties>
        raise NotImplementedError

    @async_endpoint(extract="calendar")
    async def calendar(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserCalendar:
        """
                Get your calendar events start time

        Requires minimal access key. <br>Only available to yourself.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserCalendar: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method calendar>
        # </torn-sdk:custom-method calendar>
        raise NotImplementedError

    @async_endpoint(extract="casino")
    async def casino(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserCasino:
        """
                Get your casino streak & tokens

        Requires limited access key. <br>Only available to yourself.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserCasino: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method casino>
        # </torn-sdk:custom-method casino>
        raise NotImplementedError

    @async_endpoint(extract="competition")
    async def competition(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserCompetition:
        """
                Get competition information for a specific player Get your competition information

        Requires public access key.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserCompetition: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method competition>
        # </torn-sdk:custom-method competition>
        raise NotImplementedError

    @async_endpoint(extract="cooldowns")
    async def cooldowns(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserCoolDowns:
        """
                Get your cooldowns information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserCoolDowns: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method cooldowns>
        # </torn-sdk:custom-method cooldowns>
        raise NotImplementedError

    @async_endpoint(extract="crimes")
    async def crimes(
        self,
        crime_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserCrime:
        """
                Get your crime statistics

        Requires minimal access key. <br>Return the details and statistics about for a specific crime.

                Args:
                    crime_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserCrime: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method crimes>
        # </torn-sdk:custom-method crimes>
        raise NotImplementedError

    @async_endpoint(extract="discord")
    async def discord(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserDiscord:
        """
                Get discord information for a specific user Get your discord information

        Requires public access key. <br>

        Requires public key. <br>

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserDiscord: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method discord>
        # </torn-sdk:custom-method discord>
        raise NotImplementedError

    @async_endpoint(extract="education")
    async def education(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserEducation:
        """
                Get your education information

        Requires minimal access key. <br>The response contains a list of complete eduactions and of a current education (if any).

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserEducation: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method education>
        # </torn-sdk:custom-method education>
        raise NotImplementedError

    @async_endpoint(extract="enlistedcars")
    async def enlistedcars(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserEnlistedCars:
        """
                Get your enlisted cars

        Requires minimal access key. <br>Returns a list of all user enlisted cars.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserEnlistedCars: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method enlistedcars>
        # </torn-sdk:custom-method enlistedcars>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def equipment(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserEquipmentResponse:
        """
                Get your equipment & clothing

        Requires minimal access key.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserEquipmentResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method equipment>
        # </torn-sdk:custom-method equipment>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def events(
        self,
        *,
        striptags: bool = False,
        limit: int = 20,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserEventsResponse:
        """
                Get your events

        Requires limited access key. <br> Unfortunately, the 'sort' parameter is not available for this selection.

                Args:
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserEventsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method events>
        # </torn-sdk:custom-method events>
        raise NotImplementedError

    @async_endpoint(extract="faction")
    async def faction(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserFactionResponse:
        """
                Get faction information for a specific player Get your faction information

        Requires public access key.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserFactionResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method faction>
        # </torn-sdk:custom-method faction>
        raise NotImplementedError

    @async_endpoint(extract="forumFeed")
    async def forumfeed(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserForumFeedResponse:
        """
                Get updates on your threads and posts

        Requires minimal access key. <br>This selection returns data visible in 'Feed' section on forum page. Feed is sorted by timestamp descending. Only a maximum of 100 rows are returned.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserForumFeedResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method forumfeed>
        # </torn-sdk:custom-method forumfeed>
        raise NotImplementedError

    @async_endpoint(extract="forumFriends")
    async def forumfriends(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserForumFriendsResponse:
        """
                Get updates on your friends' activity

        Requires minimal access key. <br>This selection returns data visible in 'Friends' section on forum page. Feed is sorted by timestamp descending. Only a maximum of 100 rows are returned.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserForumFriendsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method forumfriends>
        # </torn-sdk:custom-method forumfriends>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def forumposts(
        self,
        user_id: int | str | None = None,
        *,
        striptags: bool = True,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserForumPostsResponse:
        """
                Get posts for a specific player Get your posts

        Requires public access key. <br>Returns 20 posts per page for a specific player.

        Requires public access key. <br>Returns 20 posts per page.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserForumPostsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method forumposts>
        # </torn-sdk:custom-method forumposts>
        raise NotImplementedError

    @async_endpoint(extract="forumSubscribedThreads")
    async def forumsubscribedthreads(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserForumSubscribedThreadsResponse:
        """
                Get updates on threads you subscribed to

        Requires minimal access key. <br>This selection returns data visible in 'Subscribed Threads' section on forum page. Threads are sorted in the same way as on site.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserForumSubscribedThreadsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method forumsubscribedthreads>
        # </torn-sdk:custom-method forumsubscribedthreads>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def forumthreads(
        self,
        user_id: int | str | None = None,
        *,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserForumThreadsResponse:
        """
                Get threads for a specific player Get your threads

        Requires public access key. <br>Returns 100 threads per page for a specific player. When requesting data for the key owner, a field 'new_posts' is also available, indicating the amount of unread posts. Minimum API key is required for that.

        Requires public access key. <br>Returns 100 threads per page. The field 'new_posts' is also available, indicating the amount of unread posts with a Minimum API key (or higher).

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserForumThreadsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method forumthreads>
        # </torn-sdk:custom-method forumthreads>
        raise NotImplementedError

    @async_endpoint(extract="gym")
    async def gym(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserGymResponse:
        """
                Get your currently active gym

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserGymResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method gym>
        # </torn-sdk:custom-method gym>
        raise NotImplementedError

    @async_endpoint(extract="hof")
    async def hof(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserHofStats:
        """
                Get hall of fame rankings for a specific player Get your hall of fame rankings

        Requires public access key. <br>The battle_stats selection will be populated only when requesting selection with Limited, Full or Custom key and for yourself.

        Requires public access key. <br>When requesting selection with Limited, Full or Custom key, battle_stats selection will be populated.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserHofStats: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method hof>
        # </torn-sdk:custom-method hof>
        raise NotImplementedError

    @async_endpoint(extract="honors")
    async def honors(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserHonorsResponse:
        """
                Get your achieved honors

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserHonorsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method honors>
        # </torn-sdk:custom-method honors>
        raise NotImplementedError

    @async_endpoint(extract="icons")
    async def icons(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserIconsResponse:
        """
                Get icons information for a specific player Get your icons information

        Requires public access key. <br> When requesting data for yourself with 'Limited' or 'Full' access keys, the response will be of type UserIconPrivate, otherwise UserIconPublic.

        Requires public access key.<br> When requesting data for yourself with 'Custom', 'Limited' or 'Full' access keys, the response will be of type UserIconPrivate, otherwise UserIconPublic.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserIconsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method icons>
        # </torn-sdk:custom-method icons>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def inventory(
        self,
        *,
        inventory_category: TornInventoryItemType | None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserInventoryResponse:
        """
                Get your inventory

        <b>Cached selection (1 hour per category).</b><br><br>Requires minimal access key. <br>

                Args:
                    inventory_category (TornInventoryItemType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserInventoryResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method inventory>
        # </torn-sdk:custom-method inventory>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def itemmarket(
        self,
        *,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserItemMarketResponse:
        """
                Get your item market listings

        Requires limited access key. <br>

                Args:
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserItemMarketResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method itemmarket>
        # </torn-sdk:custom-method itemmarket>
        raise NotImplementedError

    @async_endpoint(extract="itemmods")
    async def itemmods(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserItemModsResponse:
        """
                Get your information about available item mods

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserItemModsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method itemmods>
        # </torn-sdk:custom-method itemmods>
        raise NotImplementedError

    @async_endpoint(extract="job")
    async def job(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserJobResponse:
        """
                Get job information for a specific player Get your job information

        Requires public access key.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserJobResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method job>
        # </torn-sdk:custom-method job>
        raise NotImplementedError

    @async_endpoint(extract="jobpoints")
    async def jobpoints(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserJobPointsResponse:
        """
                Get your jobpoints

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserJobPointsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method jobpoints>
        # </torn-sdk:custom-method jobpoints>
        raise NotImplementedError

    @async_endpoint(extract="jobranks")
    async def jobranks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserJobRanks:
        """
                Get your starter job positions

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserJobRanks: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method jobranks>
        # </torn-sdk:custom-method jobranks>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def list(
        self,
        *,
        list_category: UserListType,
        striptags: bool = True,
        limit: int = 50,
        offset: int | None = None,
        sort: SortDescType = "ASC",
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserListResponse:
        """
                Get your friends, enemies or targets list

        Requires limited access key. <br>

                Args:
                    list_category (UserListType): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int | None): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserListResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method list>
        # </torn-sdk:custom-method list>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def log(
        self,
        *,
        log_id: list[int] | None = None,
        log_category_id: int | None = None,
        target_id: int | None = None,
        limit: int = 20,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserLogsResponse:
        """
                Get your logs

        Requires full access key. <br> It's possible to pass a list of log ids or a log category id.<br>This selection is standalone and cannot be used together with other selections.

                Args:
                    log_id (list[int] | None): Query parameter for this endpoint.
                    log_category_id (int | None): Query parameter for this endpoint.
                    target_id (int | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserLogsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method log>
        # </torn-sdk:custom-method log>
        raise NotImplementedError

    @async_endpoint(extract="selections")
    async def lookup(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserLookupResponse:
        """
                Get all available user selections

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserLookupResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method lookup>
        # </torn-sdk:custom-method lookup>
        raise NotImplementedError

    @async_endpoint(extract="medals")
    async def medals(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserMedalsResponse:
        """
                Get all your achieved medals Get medals achieved by a specific player

        Requires public access key. <br>

        Requires public access key.<br>Returns only highest medal in each category (just like profiles on site).

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserMedalsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method medals>
        # </torn-sdk:custom-method medals>
        raise NotImplementedError

    @async_endpoint(extract="merits")
    async def merits(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserMerits:
        """
                Get your merits

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserMerits: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method merits>
        # </torn-sdk:custom-method merits>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def messages(
        self,
        *,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserMessagesResponse:
        """
                Get your messages

        Requires limited access key. <br>

                Args:
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserMessagesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method messages>
        # </torn-sdk:custom-method messages>
        raise NotImplementedError

    @async_endpoint(extract="missions")
    async def missions(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserMissionsResponse:
        """
                Get your current missions information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserMissionsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method missions>
        # </torn-sdk:custom-method missions>
        raise NotImplementedError

    @async_endpoint(extract="money")
    async def money(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserMoneyResponse:
        """
                Get your current wealth

        Requires limited access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserMoneyResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method money>
        # </torn-sdk:custom-method money>
        raise NotImplementedError

    @async_endpoint(extract="networth")
    async def networth(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserNetworthResponse:
        """
                Get your networth

        Requires limited access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserNetworthResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method networth>
        # </torn-sdk:custom-method networth>
        raise NotImplementedError

    @async_endpoint(extract="events")
    async def newevents(
        self,
        *,
        striptags: bool = False,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserNewEventsResponse:
        """
                Get your unseen events

        Requires limited access key. <br>

                Args:
                    striptags (bool): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserNewEventsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method newevents>
        # </torn-sdk:custom-method newevents>
        raise NotImplementedError

    @async_endpoint(extract="messages")
    async def newmessages(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserNewMessagesResponse:
        """
                Get your unseen messages

        Requires limited access key. <br>This selection is cached for 1 hour.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserNewMessagesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method newmessages>
        # </torn-sdk:custom-method newmessages>
        raise NotImplementedError

    @async_endpoint(extract="notifications")
    async def notifications(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserNotificationsResponse:
        """
                Get your notifications

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserNotificationsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method notifications>
        # </torn-sdk:custom-method notifications>
        raise NotImplementedError

    @async_endpoint(extract="organizedCrime")
    async def organizedcrime(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserOrganizedCrimeResponse:
        """
                Get your current ongoing organized crime

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserOrganizedCrimeResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method organizedcrime>
        # </torn-sdk:custom-method organizedcrime>
        raise NotImplementedError

    @async_endpoint(extract="organizedcrimes")
    async def organizedcrimes(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserOrganizedCrimesResponse:
        """
                Get your available slots for organized crimes with status 'Recruiting'

        Requires minimal access key. <br>Unlike 'faction' -> 'crimes', this selection only shows empty slots, and only for crimes with the 'Recruiting' status.

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserOrganizedCrimesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method organizedcrimes>
        # </torn-sdk:custom-method organizedcrimes>
        raise NotImplementedError

    @async_endpoint(extract="perks")
    async def perks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserPerksResponse:
        """
                Get your current perks

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserPerksResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method perks>
        # </torn-sdk:custom-method perks>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def personalstats(
        self,
        user_id: int | str | None = None,
        *,
        stat_category: PersonalStatsCategoryType | None = None,
        stat_keys: list[PersonalStatsStatNameType] | None = None,
        timestamp: int | None = None,
        comment: str | None = None,
    ) -> UserPersonalStatsResponse:
        """
                Get a player's personal stats Get your personal stats

        Requires public access key. <br>
         *  UserPersonalStatsFull is returned only when this selection is requested for the key owner with Limited, Full or Custom key.
         *  UserPersonalStatsFullPublic is returned when the requested category is 'all'.
         *  UserPersonalStatsPopular is returned when the requested category is 'popular'. Please try to use UserPersonalStatsPopular over UserPersonalStatsFullPublic wherever possible in order to reduce the server load.
         *  Otherwise, UserPersonalStatsCategory is returned for the matched category.
         *  It's possible to request specific stats via 'stat' parameter. In this case the response will vary depending on the stats requested. Private stats are still available only to the key owner (with Limited or higher key).
         *  Additionally, historical stats can also be fetched via 'stat' query parameter, but 'timestamp' parameter must be provided as well. It's only possible to pass up to 10 historical stats at once (the rest is trimmed). When requesting historical stats the response will be of type UserPersonalStatsHistoric.

        Requires public access key. <br>
         * UserPersonalStatsFull is returned only when this selection is requested with Limited, Full or Custom key access key.
         * UserPersonalStatsFullPublic is returned when the requested category is 'all'.
         * UserPersonalStatsPopular is returned when the requested category is 'popular'. Please try to use UserPersonalStatsPopular over UserPersonalStatsFullPublic wherever possible in order to reduce the server load.
         * Otherwise, UserPersonalStatsCategory is returned for the matched category.
         * Historical stats can be fetched via 'stat' query parameter. It's only possible to pass up to 10 historical stats at once (the rest is trimmed). When requesting historical stats the response will be of type UserPersonalStatsHistoric.
         * Use 'timestamp' query parameter to get historical stats at the certain point in time. It's possible some historical stats didn't exist at the given timestamp, and for such stats you will not receive anything back.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    stat_category (PersonalStatsCategoryType | None): Query parameter for this endpoint.
                    stat_keys (list[PersonalStatsStatNameType] | None): Query parameter for this endpoint.
                    timestamp (int | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserPersonalStatsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method personalstats>
        # </torn-sdk:custom-method personalstats>
        raise NotImplementedError

    @async_endpoint(extract="profile")
    async def profile(
        self,
        user_id: int | str | None = None,
        *,
        striptags: bool = True,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserProfileResponse:
        """
                Get profile information for a specific player Get your own profile

        Requires public access key.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserProfileResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method profile>
        # </torn-sdk:custom-method profile>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def properties(
        self,
        user_id: int | str | None = None,
        *,
        property_filters: FiltersUserPropertiesType | None = None,
        limit: int = 20,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserPropertiesResponse:
        """
                Get specific user's properties Get your own properties

        Requires public access key. <br>Extended responses are available when requesting the data with Limited or higher access keys for yourself or your spouse.

        Requires public access key. <br>Extended responses are available when requesting the data with Limited or higher access keys.

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    property_filters (FiltersUserPropertiesType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserPropertiesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method properties>
        # </torn-sdk:custom-method properties>
        raise NotImplementedError

    @async_endpoint(extract="property")
    async def property(
        self,
        user_id: int | str | None = None,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserPropertyDetails:
        """
                Get specific user's property Get your current property

        Requires public access key. <br>

                Args:
                    user_id (int | str | None): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserPropertyDetails: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method property>
        # </torn-sdk:custom-method property>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def races(
        self,
        *,
        race_category: RacingRaceType | None = None,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserRacesResponse:
        """
                Get your races

        Requires minimal access key. <br>Returns a list of user races, ordered by race start timestamp.

                Args:
                    race_category (RacingRaceType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserRacesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method races>
        # </torn-sdk:custom-method races>
        raise NotImplementedError

    @async_endpoint(extract="racingrecords")
    async def racingrecords(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserRacingRecordsResponse:
        """
                Get your current racing records

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserRacingRecordsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method racingrecords>
        # </torn-sdk:custom-method racingrecords>
        raise NotImplementedError

    @async_endpoint(extract="refills")
    async def refills(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserRefillsResponse:
        """
                Get your refills information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserRefillsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method refills>
        # </torn-sdk:custom-method refills>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def reports(
        self,
        *,
        report_category: ReportType | None = None,
        target_id: int | None = None,
        limit: int = 20,
        offset: int = 0,
        sort: SortDescType = "DESC",
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> ReportsResponse:
        """
                Get your reports

        Requires limited access key. <br>
        The limit is set to 25 when requesting any category other than 'stats'.<br>
        When requesting the 'stats' category, limit can be increased up to 100.

                Args:
                    report_category (ReportType | None): Query parameter for this endpoint.
                    target_id (int | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    ReportsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method reports>
        # </torn-sdk:custom-method reports>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def revives(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        striptags: bool = True,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RevivesResponse:
        """
                Get your detailed revives

        Requires limited access key. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RevivesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method revives>
        # </torn-sdk:custom-method revives>
        raise NotImplementedError

    @async_endpoint(method="get_revivesfull", extract_default=False)
    async def revives_full(
        self,
        *,
        attack_filters: list[UserAttacksRequestFilterType] | None = None,
        striptags: bool = True,
        limit: int = 20,
        sort: SortType | None = None,
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> RevivesFullResponse:
        """
                Get your simplified revives

        Requires limited access key. <br>

                Args:
                    attack_filters (list[UserAttacksRequestFilterType] | None): Query parameter for this endpoint.
                    striptags (bool): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortType | None): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    RevivesFullResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method revives_full>
        # </torn-sdk:custom-method revives_full>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def search(
        self,
        *,
        user_name: str | None = None,
        filters: list[UserSearchFilterItemVariant1Type | str] | None = None,
        offset: int = 0,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserSearchResponse:
        """
                Search users by name or other criteria

        Requires public access key. <br>This selection is standalone and cannot be used together with other selections.<br>It's always limited to return just 25 records.

                Args:
                    user_name (str | None): Query parameter for this endpoint.
                    filters (list[UserSearchFilterItemVariant1Type | str] | None): Query parameter for this endpoint.
                    offset (int): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserSearchResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method search>
        # </torn-sdk:custom-method search>
        raise NotImplementedError

    @async_endpoint(extract="skills")
    async def skills(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserSkillsResponse:
        """
                Get your skills

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserSkillsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method skills>
        # </torn-sdk:custom-method skills>
        raise NotImplementedError

    @async_endpoint(extract="stocks")
    async def stocks(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserStocksResponse:
        """
                Get your stocks

        Requires limited access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserStocksResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method stocks>
        # </torn-sdk:custom-method stocks>
        raise NotImplementedError

    @async_endpoint(extract="timestamp")
    async def timestamp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserTimestampResponse:
        """
                Get current server time

        Requires public access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserTimestampResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method timestamp>
        # </torn-sdk:custom-method timestamp>
        raise NotImplementedError

    @async_endpoint(extract="trade")
    async def trade(
        self,
        trade_id: int,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserTradeDetailed:
        """
                Get your detailed trade

        Requires limited access key. <br>Only possible to get trades you participated in.

                Args:
                    trade_id (int): Path parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserTradeDetailed: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method trade>
        # </torn-sdk:custom-method trade>
        raise NotImplementedError

    @async_endpoint(extract_default=False)
    async def trades(
        self,
        *,
        trade_category: TradeCategoryType | None = "ongoing",
        limit: int = 100,
        sort: SortDescType = "DESC",
        to: int | None = None,
        from_: int | None = None,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserTradesResponse:
        """
                Get your trades

        Requires limited access key. <br> When requesting 'ongoing' trades (default), limit/offset/sort are not being used.

                Args:
                    trade_category (TradeCategoryType | None): Query parameter for this endpoint.
                    limit (int): Query parameter for this endpoint.
                    sort (SortDescType): Query parameter for this endpoint.
                    to (int | None): Query parameter for this endpoint.
                    from_ (int | None): Query parameter for this endpoint.
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserTradesResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method trades>
        # </torn-sdk:custom-method trades>
        raise NotImplementedError

    @async_endpoint(extract="travel")
    async def travel(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserTravelResponse:
        """
                Get your travel information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserTravelResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method travel>
        # </torn-sdk:custom-method travel>
        raise NotImplementedError

    @async_endpoint(extract="virus")
    async def virus(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserVirusResponse:
        """
                Get your virus coding information

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserVirusResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method virus>
        # </torn-sdk:custom-method virus>
        raise NotImplementedError

    @async_endpoint(extract="weaponexp")
    async def weaponexp(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserWeaponExpResponse:
        """
                Get your weapon experience information

        Requires minimal key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserWeaponExpResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method weaponexp>
        # </torn-sdk:custom-method weaponexp>
        raise NotImplementedError

    @async_endpoint(extract="workstats")
    async def workstats(
        self,
        *,
        timestamp: int | str | None = None,
        comment: str | None = None,
    ) -> UserWorkStatsResponse:
        """
                Get your working stats

        Requires minimal access key. <br>

                Args:
                    timestamp (int | str | None): Query parameter for this endpoint.
                    comment (str | None): Query parameter for this endpoint.

                Returns:
                    UserWorkStatsResponse: Parsed API response.

                Raises:
                    TornAPIWrapper.errors.APIError: If Torn rejects the request.
                    pydantic.ValidationError: If the response does not match the model.
        """
        # <torn-sdk:custom-method workstats>
        # </torn-sdk:custom-method workstats>
        raise NotImplementedError

    # <torn-sdk:custom-class GeneratedAsyncUserResourceMixin>
    # </torn-sdk:custom-class GeneratedAsyncUserResourceMixin>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
