# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import ItemMarketListingItemDetailsRarityVariant1Type, TornItemType, TornItemWeaponType

class AuctionHouseStackableItem(TornModel):
    id: int
    uid: int
    name: str
    type: TornItemType

class BasicUser(TornModel):
    id: int
    name: str

class ItemMarketListingItemBonus(TornModel):
    id: int
    title: str
    description: str
    value: int

class ItemMarketListingItemDetails(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None

class ItemMarketListingItemStats(TornModel):
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float

class TornItemDetails(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None
    id: int
    name: str
    type: TornItemType
    sub_type: TornItemWeaponType | None

class AuctionHouseListing(TornModel):
    id: int
    seller: BasicUser
    buyer: BasicUser
    timestamp: int
    price: int
    bids: int
    item: AuctionHouseStackableItem | TornItemDetails
