"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    ItemMarketListingItemDetailsRarityVariant1Type,
)


class ItemMarket(TornModel):
    """
    Pydantic model for the ItemMarket Torn API response.

    Attributes:
        item (ItemMarketItem): Torn API field `item`.
        listings (list[ItemMarketListingNonstackable | ItemMarketListingStackable]): Torn API field `listings`.
        cache_timestamp (int): Timestamp when the data was globally cached at.
        cache_delay (int): The minimum amount of time needed before the cache timestamp can change.
    """

    # <torn-sdk:custom-class ItemMarket>
    # </torn-sdk:custom-class ItemMarket>
    item: ItemMarketItem
    listings: list[ItemMarketListingNonstackable | ItemMarketListingStackable]
    cache_timestamp: int
    cache_delay: int | None = None


class ItemMarketItem(TornModel):
    """
    Pydantic model for the ItemMarketItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        type (str): Torn API field `type`.
        average_price (int): Torn API field `average_price`.
    """

    # <torn-sdk:custom-class ItemMarketItem>
    # </torn-sdk:custom-class ItemMarketItem>
    id: int
    name: str
    type: str
    average_price: int


class ItemMarketListingItemBonus(TornModel):
    """
    Pydantic model for the ItemMarketListingItemBonus Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        title (str): Torn API field `title`.
        description (str): Torn API field `description`.
        value (int): Torn API field `value`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemBonus>
    # </torn-sdk:custom-class ItemMarketListingItemBonus>
    id: int
    title: str
    description: str
    value: int


class ItemMarketListingItemDetails(TornModel):
    """
    Pydantic model for the ItemMarketListingItemDetails Torn API response.

    Attributes:
        uid (int): Torn API field `uid`.
        stats (ItemMarketListingItemStats): Torn API field `stats`.
        bonuses (list[ItemMarketListingItemBonus]): Torn API field `bonuses`.
        rarity (ItemMarketListingItemDetailsRarityVariant1Type | None): Torn API field `rarity`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemDetails>
    # </torn-sdk:custom-class ItemMarketListingItemDetails>
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None


class ItemMarketListingItemStats(TornModel):
    """
    Pydantic model for the ItemMarketListingItemStats Torn API response.

    Attributes:
        damage (float | None): Torn API field `damage`.
        accuracy (float | None): Torn API field `accuracy`.
        armor (float | None): Torn API field `armor`.
        quality (float): Torn API field `quality`.
    """

    # <torn-sdk:custom-class ItemMarketListingItemStats>
    # </torn-sdk:custom-class ItemMarketListingItemStats>
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float


class ItemMarketListingNonstackable(TornModel):
    """
    Pydantic model for the ItemMarketListingNonstackable Torn API response.

    Attributes:
        price (int): Torn API field `price`.
        amount (int): Torn API field `amount`.
        item_details (ItemMarketListingItemDetails): Torn API field `item_details`.
    """

    # <torn-sdk:custom-class ItemMarketListingNonstackable>
    # </torn-sdk:custom-class ItemMarketListingNonstackable>
    price: int
    amount: int
    item_details: ItemMarketListingItemDetails


class ItemMarketListingStackable(TornModel):
    """
    Pydantic model for the ItemMarketListingStackable Torn API response.

    Attributes:
        price (int): Torn API field `price`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class ItemMarketListingStackable>
    # </torn-sdk:custom-class ItemMarketListingStackable>
    price: int
    amount: int


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndTotal Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    links: RequestLinks
    total: int | None = None


class MarketItemMarketResponse(TornModel):
    """
    Pydantic model for the MarketItemMarketResponse Torn API response.

    Attributes:
        itemmarket (ItemMarket): Torn API field `itemmarket`.
        metadata (RequestMetadataWithLinksAndTotal): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class MarketItemMarketResponse>
    # </torn-sdk:custom-class MarketItemMarketResponse>
    itemmarket: ItemMarket
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
