"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    ItemMarketListingItemDetailsRarityVariant1Type,
)


class ItemMarket(TornModel):
    item: ItemMarketItem
    listings: list[ItemMarketListingNonstackable | ItemMarketListingStackable]
    cache_timestamp: int
    cache_delay: int | None = None


class ItemMarketItem(TornModel):
    id: int
    name: str
    type: str
    average_price: int


class ItemMarketListingItemBonus(TornModel):
    id: int
    title: str
    description: str
    value: int


class ItemMarketListingItemDetails(TornModel):
    uid: int
    stats: ItemMarketListingItemStats
    bonuses: list[ItemMarketListingItemBonus]
    rarity: ItemMarketListingItemDetailsRarityVariant1Type | None


class ItemMarketListingItemStats(TornModel):
    damage: float | None
    accuracy: float | None
    armor: float | None
    quality: float


class ItemMarketListingNonstackable(TornModel):
    price: int
    amount: int
    item_details: ItemMarketListingItemDetails


class ItemMarketListingStackable(TornModel):
    price: int
    amount: int


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    links: RequestLinks
    total: int | None = None


class MarketItemMarketResponse(TornModel):
    itemmarket: ItemMarket
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")
