"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import MarketSelectionNameVariant1Type


class MarketLookupResponse(
    RootModel[list[MarketSelectionNameVariant1Type | str]]
):
    pass
