"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel


class MarketPointsmarketResponseItem(TornModel):
    """
    Pydantic model for the MarketPointsmarketResponseItem Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        quantity (int): Torn API field `quantity`.
        cost (int): Torn API field `cost`.
        total_cost (int): Torn API field `total_cost`.
    """

    # <torn-sdk:custom-class MarketPointsmarketResponseItem>
    # </torn-sdk:custom-class MarketPointsmarketResponseItem>
    id: int
    quantity: int
    cost: int
    total_cost: int


class MarketPointsmarketResponse(
    TornListModel[MarketPointsmarketResponseItem]
):
    """
    Pydantic model for the MarketPointsmarketResponse Torn API response.
    """

    # <torn-sdk:custom-class MarketPointsmarketResponse>
    # </torn-sdk:custom-class MarketPointsmarketResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
