"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import PropertyModificationType


class BasicProperty(TornModel):
    """
    Pydantic model for the BasicProperty Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class BasicProperty>
    # </torn-sdk:custom-class BasicProperty>
    id: int
    name: str


class MarketPropertyDetails(TornModel):
    """
    Pydantic model for the MarketPropertyDetails Torn API response.

    Attributes:
        listings (list[MarketPropertyDetailsListingsItem]): Torn API field `listings`.
        property (BasicProperty): Torn API field `property`.
    """

    # <torn-sdk:custom-class MarketPropertyDetails>
    # </torn-sdk:custom-class MarketPropertyDetails>
    listings: list[MarketPropertyDetailsListingsItem]
    property: BasicProperty


class RequestLinks(TornModel):
    """
    Pydantic model for the RequestLinks Torn API response.

    Attributes:
        next (str | None): Auto-generated link to get the next set of records.
        prev (str | None): Auto-generated link to get the prev set of records.
    """

    # <torn-sdk:custom-class RequestLinks>
    # </torn-sdk:custom-class RequestLinks>
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    """
    Pydantic model for the RequestMetadataWithLinksAndTotal Torn API response.

    Attributes:
        links (RequestLinks): Torn API field `links`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    # </torn-sdk:custom-class RequestMetadataWithLinksAndTotal>
    links: RequestLinks
    total: int | None = None


class MarketPropertyDetailsListingsItem(TornModel):
    """
    Pydantic model for the MarketPropertyDetailsListingsItem Torn API response.

    Attributes:
        happy (int): Torn API field `happy`.
        cost (int): Torn API field `cost`.
        market_price (int): Torn API field `market_price`.
        upkeep (int): Torn API field `upkeep`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
    """

    # <torn-sdk:custom-class MarketPropertyDetailsListingsItem>
    # </torn-sdk:custom-class MarketPropertyDetailsListingsItem>
    happy: int
    cost: int
    market_price: int
    upkeep: int
    modifications: list[PropertyModificationType]


class MarketPropertiesResponse(TornModel):
    """
    Pydantic model for the MarketPropertiesResponse Torn API response.

    Attributes:
        properties (MarketPropertyDetails): Torn API field `properties`.
        properties_timestamp (int): Torn API field `properties_timestamp`.
        properties_delay (int): The minimum amount of time needed before the cache timestamp can change.
        metadata (RequestMetadataWithLinksAndTotal): Torn API field `_metadata`.
    """

    # <torn-sdk:custom-class MarketPropertiesResponse>
    # </torn-sdk:custom-class MarketPropertiesResponse>
    properties: MarketPropertyDetails
    properties_timestamp: int
    properties_delay: int | None = None
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
