"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import Field

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    UserLastActionStatusType,
    UserPlaneImageType,
    UserStatusStateType,
)


class CompanyCustomers(TornModel):
    daily: int
    weekly: int


class CompanyDirector(TornModel):
    id: int
    name: str
    status: UserStatus
    last_action: UserLastAction


class CompanyEmployees(TornModel):
    hired: int
    capacity: int


class CompanyIncome(TornModel):
    daily: int
    weekly: int


class CompanyProfile(TornModel):
    id: int
    name: str
    created_at: int
    days_old: int
    image: str | None
    type: CompanyType
    rating: int
    director: CompanyDirector
    employees: CompanyEmployees
    income: CompanyIncome
    customers: CompanyCustomers
    applications_allowed: bool


class CompanyType(TornModel):
    id: int
    name: str


class RequestLinks(TornModel):
    next: str | None
    prev: str | None


class RequestMetadataWithLinksAndTotal(TornModel):
    links: RequestLinks
    total: int | None = None


class UserLastAction(TornModel):
    status: UserLastActionStatusType
    timestamp: int
    relative: str


class UserStatus(TornModel):
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None


class CompaniesResponse(TornModel):
    companies: list[CompanyProfile]
    companies_timestamp: int
    companies_delay: int
    metadata: RequestMetadataWithLinksAndTotal = Field(alias="_metadata")
