"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    UserLastActionStatusType,
    UserPlaneImageType,
    UserStatusStateType,
)


class CompanyEmployee(TornModel):
    """
    Pydantic model for the CompanyEmployee Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        position (CompanyEmployeePosition): Torn API field `position`.
        days_in_company (int): Torn API field `days_in_company`.
        status (UserStatus): Torn API field `status`.
        last_action (UserLastAction): Torn API field `last_action`.
    """

    # <torn-sdk:custom-class CompanyEmployee>
    # </torn-sdk:custom-class CompanyEmployee>
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction


class CompanyEmployeeEffectiveness(TornModel):
    """
    Pydantic model for the CompanyEmployeeEffectiveness Torn API response.

    Attributes:
        working_stats (int): Torn API field `working_stats`.
        settled_in (int): Torn API field `settled_in`.
        book (int): Torn API field `book`.
        merits (int): Torn API field `merits`.
        director_education (int): Torn API field `director_education`.
        management (int): Torn API field `management`.
        wrong_gender (int): Torn API field `wrong_gender`.
        addiction (int): Torn API field `addiction`.
        inactivity (int): Torn API field `inactivity`.
        total (int): Torn API field `total`.
    """

    # <torn-sdk:custom-class CompanyEmployeeEffectiveness>
    # </torn-sdk:custom-class CompanyEmployeeEffectiveness>
    working_stats: int
    settled_in: int
    book: int
    merits: int
    director_education: int
    management: int
    wrong_gender: int
    addiction: int
    inactivity: int
    total: int


class CompanyEmployeeExtended(TornModel):
    """
    Pydantic model for the CompanyEmployeeExtended Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        position (CompanyEmployeePosition): Torn API field `position`.
        days_in_company (int): Torn API field `days_in_company`.
        status (UserStatus): Torn API field `status`.
        last_action (UserLastAction): Torn API field `last_action`.
        stats (CompanyEmployeeStats): Torn API field `stats`.
        effectiveness (CompanyEmployeeEffectiveness): Torn API field `effectiveness`.
    """

    # <torn-sdk:custom-class CompanyEmployeeExtended>
    # </torn-sdk:custom-class CompanyEmployeeExtended>
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction
    stats: CompanyEmployeeStats
    effectiveness: CompanyEmployeeEffectiveness


class CompanyEmployeeFull(TornModel):
    """
    Pydantic model for the CompanyEmployeeFull Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        position (CompanyEmployeePosition): Torn API field `position`.
        days_in_company (int): Torn API field `days_in_company`.
        status (UserStatus): Torn API field `status`.
        last_action (UserLastAction): Torn API field `last_action`.
        stats (CompanyEmployeeStats): Torn API field `stats`.
        effectiveness (CompanyEmployeeEffectiveness): Torn API field `effectiveness`.
        joined_at (int): Torn API field `joined_at`.
        wage (int): Torn API field `wage`.
        value (int | None): This value is null if you don't have a secretary.
    """

    # <torn-sdk:custom-class CompanyEmployeeFull>
    # </torn-sdk:custom-class CompanyEmployeeFull>
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction
    stats: CompanyEmployeeStats
    effectiveness: CompanyEmployeeEffectiveness
    joined_at: int
    wage: int
    value: int | None


class CompanyEmployeePosition(TornModel):
    """
    Pydantic model for the CompanyEmployeePosition Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class CompanyEmployeePosition>
    # </torn-sdk:custom-class CompanyEmployeePosition>
    id: int
    name: str


class CompanyEmployeeStats(TornModel):
    """
    Pydantic model for the CompanyEmployeeStats Torn API response.

    Attributes:
        manual_labor (int): Torn API field `manual_labor`.
        intelligence (int): Torn API field `intelligence`.
        endurance (int): Torn API field `endurance`.
    """

    # <torn-sdk:custom-class CompanyEmployeeStats>
    # </torn-sdk:custom-class CompanyEmployeeStats>
    manual_labor: int
    intelligence: int
    endurance: int


class UserLastAction(TornModel):
    """
    Details about a user's last action.

    Attributes:
        status (UserLastActionStatusType): Torn API field `status`.
        timestamp (int): Torn API field `timestamp`.
        relative (str): Torn API field `relative`.
    """

    # <torn-sdk:custom-class UserLastAction>
    # </torn-sdk:custom-class UserLastAction>
    status: UserLastActionStatusType
    timestamp: int
    relative: str


class UserStatus(TornModel):
    """
    Details about a user's status.

    Attributes:
        description (str): Torn API field `description`.
        details (str | None): Torn API field `details`.
        state (UserStatusStateType | str): Torn API field `state`.
        color (str): Torn API field `color`.
        until (int | None): Torn API field `until`.
        plane_image_type (UserPlaneImageType): This field is populated only if the state is 'Traveling'.
    """

    # <torn-sdk:custom-class UserStatus>
    # </torn-sdk:custom-class UserStatus>
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None


class CompanyEmployeesResponse(
    RootModel[
        list[CompanyEmployee | CompanyEmployeeExtended | CompanyEmployeeFull]
        | list[CompanyEmployee]
    ]
):
    """
    Pydantic model for the CompanyEmployeesResponse Torn API response.
    """

    # <torn-sdk:custom-class CompanyEmployeesResponse>
    # </torn-sdk:custom-class CompanyEmployeesResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
