"""Pydantic response models generated from the Torn OpenAPI specification."""

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    UserLastActionStatusType,
    UserPlaneImageType,
    UserStatusStateType,
)


class CompanyEmployee(TornModel):
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction


class CompanyEmployeeEffectiveness(TornModel):
    working_stats: int
    settled_in: int
    book: int
    merits: int
    director_education: int
    management: int
    wrong_gender: int
    addiction: int
    inactivity: int
    total: int


class CompanyEmployeeExtended(TornModel):
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction
    stats: CompanyEmployeeStats
    effectiveness: CompanyEmployeeEffectiveness


class CompanyEmployeeFull(TornModel):
    id: int
    name: str
    position: CompanyEmployeePosition
    days_in_company: int
    status: UserStatus
    last_action: UserLastAction
    stats: CompanyEmployeeStats
    effectiveness: CompanyEmployeeEffectiveness
    joined_at: int
    wage: int
    value: int | None


class CompanyEmployeePosition(TornModel):
    id: int
    name: str


class CompanyEmployeeStats(TornModel):
    manual_labor: int
    intelligence: int
    endurance: int


class UserLastAction(TornModel):
    status: UserLastActionStatusType
    timestamp: int
    relative: str


class UserStatus(TornModel):
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None


class CompanyEmployeesResponse(
    RootModel[
        list[CompanyEmployee | CompanyEmployeeExtended | CompanyEmployeeFull]
        | list[CompanyEmployee]
    ]
):
    pass
