"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    CompanyStaffRoomSizeType,
    UserLastActionStatusType,
    UserPlaneImageType,
    UserStatusStateType,
)


class CompanyCustomers(TornModel):
    """
    Pydantic model for the CompanyCustomers Torn API response.

    Attributes:
        daily (int): Torn API field `daily`.
        weekly (int): Torn API field `weekly`.
    """

    # <torn-sdk:custom-class CompanyCustomers>
    # </torn-sdk:custom-class CompanyCustomers>
    daily: int
    weekly: int


class CompanyDirector(TornModel):
    """
    Pydantic model for the CompanyDirector Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        status (UserStatus): Torn API field `status`.
        last_action (UserLastAction): Torn API field `last_action`.
    """

    # <torn-sdk:custom-class CompanyDirector>
    # </torn-sdk:custom-class CompanyDirector>
    id: int
    name: str
    status: UserStatus
    last_action: UserLastAction


class CompanyEmployees(TornModel):
    """
    Pydantic model for the CompanyEmployees Torn API response.

    Attributes:
        hired (int): Torn API field `hired`.
        capacity (int): Torn API field `capacity`.
    """

    # <torn-sdk:custom-class CompanyEmployees>
    # </torn-sdk:custom-class CompanyEmployees>
    hired: int
    capacity: int


class CompanyIncome(TornModel):
    """
    Pydantic model for the CompanyIncome Torn API response.

    Attributes:
        daily (int): Torn API field `daily`.
        weekly (int): Torn API field `weekly`.
    """

    # <torn-sdk:custom-class CompanyIncome>
    # </torn-sdk:custom-class CompanyIncome>
    daily: int
    weekly: int


class CompanyProfile(TornModel):
    """
    Pydantic model for the CompanyProfile Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        created_at (int): Torn API field `created_at`.
        days_old (int): Torn API field `days_old`.
        image (str | None): Torn API field `image`.
        type (CompanyType): Torn API field `type`.
        rating (int): Torn API field `rating`.
        director (CompanyDirector): Torn API field `director`.
        employees (CompanyEmployees): Torn API field `employees`.
        income (CompanyIncome): Torn API field `income`.
        customers (CompanyCustomers): Torn API field `customers`.
        applications_allowed (bool): Torn API field `applications_allowed`.
    """

    # <torn-sdk:custom-class CompanyProfile>
    # </torn-sdk:custom-class CompanyProfile>
    id: int
    name: str
    created_at: int
    days_old: int
    image: str | None
    type: CompanyType
    rating: int
    director: CompanyDirector
    employees: CompanyEmployees
    income: CompanyIncome
    customers: CompanyCustomers
    applications_allowed: bool


class CompanyProfileExtended(TornModel):
    """
    Pydantic model for the CompanyProfileExtended Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
        created_at (int): Torn API field `created_at`.
        days_old (int): Torn API field `days_old`.
        image (str | None): Torn API field `image`.
        type (CompanyType): Torn API field `type`.
        rating (int): Torn API field `rating`.
        director (CompanyDirector): Torn API field `director`.
        employees (CompanyEmployees): Torn API field `employees`.
        income (CompanyIncome): Torn API field `income`.
        customers (CompanyCustomers): Torn API field `customers`.
        applications_allowed (bool): Torn API field `applications_allowed`.
        funds (int): Torn API field `funds`.
        popularity (int): Torn API field `popularity`.
        efficiency (int): Torn API field `efficiency`.
        environment (int): Torn API field `environment`.
        trains (int): Torn API field `trains`.
        advertisement_budget (int): Torn API field `advertisement_budget`.
        upgrades (CompanyUpgrades): Torn API field `upgrades`.
        value (int): Torn API field `value`.
    """

    # <torn-sdk:custom-class CompanyProfileExtended>
    # </torn-sdk:custom-class CompanyProfileExtended>
    id: int
    name: str
    created_at: int
    days_old: int
    image: str | None
    type: CompanyType
    rating: int
    director: CompanyDirector
    employees: CompanyEmployees
    income: CompanyIncome
    customers: CompanyCustomers
    applications_allowed: bool
    funds: int
    popularity: int
    efficiency: int
    environment: int
    trains: int
    advertisement_budget: int
    upgrades: CompanyUpgrades
    value: int


class CompanyType(TornModel):
    """
    Pydantic model for the CompanyType Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class CompanyType>
    # </torn-sdk:custom-class CompanyType>
    id: int
    name: str


class CompanyUpgrades(TornModel):
    """
    Pydantic model for the CompanyUpgrades Torn API response.

    Attributes:
        staff_room (CompanyStaffRoomSizeType): Torn API field `staff_room`.
        storage (str): Torn API field `storage`.
        storage_capacity (int): Torn API field `storage_capacity`.
    """

    # <torn-sdk:custom-class CompanyUpgrades>
    # </torn-sdk:custom-class CompanyUpgrades>
    staff_room: CompanyStaffRoomSizeType
    storage: str
    storage_capacity: int


class UserLastAction(TornModel):
    """
    Details about a user's last action.

    Attributes:
        status (UserLastActionStatusType): Torn API field `status`.
        timestamp (int): Torn API field `timestamp`.
        relative (str): Torn API field `relative`.
    """

    # <torn-sdk:custom-class UserLastAction>
    # </torn-sdk:custom-class UserLastAction>
    status: UserLastActionStatusType
    timestamp: int
    relative: str


class UserStatus(TornModel):
    """
    Details about a user's status.

    Attributes:
        description (str): Torn API field `description`.
        details (str | None): Torn API field `details`.
        state (UserStatusStateType | str): Torn API field `state`.
        color (str): Torn API field `color`.
        until (int | None): Torn API field `until`.
        plane_image_type (UserPlaneImageType): This field is populated only if the state is 'Traveling'.
    """

    # <torn-sdk:custom-class UserStatus>
    # </torn-sdk:custom-class UserStatus>
    description: str
    details: str | None
    state: UserStatusStateType | str
    color: str
    until: int | None
    plane_image_type: UserPlaneImageType | None = None


class CompanyProfileResponse(
    RootModel[CompanyProfile | CompanyProfileExtended | CompanyProfile]
):
    """
    Pydantic model for the CompanyProfileResponse Torn API response.
    """

    # <torn-sdk:custom-class CompanyProfileResponse>
    # </torn-sdk:custom-class CompanyProfileResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
