# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from pydantic import Field

class CompanyCustomers(TornModel):
    daily: int
    weekly: int

class CompanyEmployees(TornModel):
    hired: int
    capacity: int

class CompanyIncome(TornModel):
    daily: int
    weekly: int

class CompanySearchProfile(TornModel):
    id: int
    name: str
    created_at: int
    days_old: int
    image: str | None
    type: CompanyType
    rating: int
    employees: CompanyEmployees
    income: CompanyIncome
    customers: CompanyCustomers
    applications_allowed: bool

class CompanyType(TornModel):
    id: int
    name: str

class RequestLinks(TornModel):
    next: str | None
    prev: str | None

class RequestMetadataWithLinks(TornModel):
    links: RequestLinks

class CompaniesSearchResponse(TornModel):
    search: list[CompanySearchProfile]
    metadata: RequestMetadataWithLinks = Field(alias='_metadata')
