# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel

class CompanyStockItem(TornModel):
    name: str
    id: int
    cost: int
    rrp: int
    price: int
    in_stock: int
    on_order: int
    sold_amount: int
    sold_worth: int

class CompanyStockResponse(TornListModel[CompanyStockItem]):
    pass
