"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from pydantic import RootModel

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import PropertySelectionNameVariant1Type


class PropertyLookupResponse(
    RootModel[list[PropertySelectionNameVariant1Type | str]]
):
    """
    Pydantic model for the PropertyLookupResponse Torn API response.
    """

    # <torn-sdk:custom-class PropertyLookupResponse>
    # </torn-sdk:custom-class PropertyLookupResponse>


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
