# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import PropertyModificationType, PropertyStaffType, UserPropertyDetailsExtendedWithRentStatusType

class BasicProperty(TornModel):
    id: int
    name: str

class BasicUser(TornModel):
    id: int
    name: str

class UserPropertyBasicDetails(TornModel):
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyBasicDetailsUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyBasicDetailsStaffItem]

class UserPropertyBasicDetailsStaffItem(TornModel):
    type: PropertyStaffType
    amount: int

class UserPropertyBasicDetailsUpkeep(TornModel):
    property: int
    staff: int

class UserPropertyDetailsExtendedWithRentStaffItem(TornModel):
    type: PropertyStaffType
    amount: int

class UserPropertyDetailsExtendedWithRentUpkeep(TornModel):
    property: int
    staff: int

class UserPropertyDetailsExtendedWithRent(TornModel):
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedWithRentUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedWithRentStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedWithRentStatusType
    rented_by: BasicUser | None = None
