"""Pydantic response models generated from the Torn OpenAPI specification."""

# <torn-sdk:custom-header>
# </torn-sdk:custom-header>

# AUTO-GENERATED BY torn_sdk_codegen.py v-0.1.0. DO NOT EDIT MANUALLY outside custom blocks.
from __future__ import annotations

from torn_sdk.models.base import TornListModel, TornModel
from torn_sdk.models.types import (
    PropertyModificationType,
    PropertyStaffType,
    UserPropertyDetailsExtendedWithRentStatusType,
)


class BasicProperty(TornModel):
    """
    Pydantic model for the BasicProperty Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class BasicProperty>
    # </torn-sdk:custom-class BasicProperty>
    id: int
    name: str


class BasicUser(TornModel):
    """
    Pydantic model for the BasicUser Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        name (str): Torn API field `name`.
    """

    # <torn-sdk:custom-class BasicUser>
    # </torn-sdk:custom-class BasicUser>
    id: int
    name: str


class UserPropertyBasicDetails(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetails Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyBasicDetailsUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyBasicDetailsStaffItem]): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetails>
    # </torn-sdk:custom-class UserPropertyBasicDetails>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyBasicDetailsUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyBasicDetailsStaffItem]


class UserPropertyBasicDetailsStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetailsStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetailsStaffItem>
    # </torn-sdk:custom-class UserPropertyBasicDetailsStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyBasicDetailsUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyBasicDetailsUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyBasicDetailsUpkeep>
    # </torn-sdk:custom-class UserPropertyBasicDetailsUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedWithRentStaffItem(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedWithRentStaffItem Torn API response.

    Attributes:
        type (PropertyStaffType): Torn API field `type`.
        amount (int): Torn API field `amount`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedWithRentStaffItem>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedWithRentStaffItem>
    type: PropertyStaffType
    amount: int


class UserPropertyDetailsExtendedWithRentUpkeep(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedWithRentUpkeep Torn API response.

    Attributes:
        property (int): Torn API field `property`.
        staff (int): Torn API field `staff`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedWithRentUpkeep>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedWithRentUpkeep>
    property: int
    staff: int


class UserPropertyDetailsExtendedWithRent(TornModel):
    """
    Pydantic model for the UserPropertyDetailsExtendedWithRent Torn API response.

    Attributes:
        id (int): Torn API field `id`.
        owner (BasicUser): Torn API field `owner`.
        property (BasicProperty): Torn API field `property`.
        happy (int): Torn API field `happy`.
        upkeep (UserPropertyDetailsExtendedWithRentUpkeep): Torn API field `upkeep`.
        market_price (int): Torn API field `market_price`.
        modifications (list[PropertyModificationType]): Torn API field `modifications`.
        staff (list[UserPropertyDetailsExtendedWithRentStaffItem]): Torn API field `staff`.
        used_by (list[BasicUser]): Torn API field `used_by`.
        status (UserPropertyDetailsExtendedWithRentStatusType): Torn API field `status`.
        rented_by (BasicUser): Torn API field `rented_by`.
    """

    # <torn-sdk:custom-class UserPropertyDetailsExtendedWithRent>
    # </torn-sdk:custom-class UserPropertyDetailsExtendedWithRent>
    id: int
    owner: BasicUser
    property: BasicProperty
    happy: int
    upkeep: UserPropertyDetailsExtendedWithRentUpkeep
    market_price: int
    modifications: list[PropertyModificationType]
    staff: list[UserPropertyDetailsExtendedWithRentStaffItem]
    used_by: list[BasicUser]
    status: UserPropertyDetailsExtendedWithRentStatusType
    rented_by: BasicUser | None = None


# <torn-sdk:custom-footer>
# </torn-sdk:custom-footer>
